// flow-typed signature: b59cca67adabb8b30802b2f0379715cc
// flow-typed version: <<STUB>>/accepts_v^1.3.3/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'accepts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'accepts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'accepts/index' {
  declare module.exports: $Exports<'accepts'>;
}
declare module 'accepts/index.js' {
  declare module.exports: $Exports<'accepts'>;
}
