// flow-typed signature: c6a18d2063e32f56b48bb9212a66ab3d
// flow-typed version: <<STUB>>/ajv_v^5.3.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ajv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ajv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ajv/dist/ajv.bundle' {
  declare module.exports: any;
}

declare module 'ajv/dist/ajv.min' {
  declare module.exports: any;
}

declare module 'ajv/dist/nodent.min' {
  declare module.exports: any;
}

declare module 'ajv/dist/regenerator.min' {
  declare module.exports: any;
}

declare module 'ajv/lib/$data' {
  declare module.exports: any;
}

declare module 'ajv/lib/ajv' {
  declare module.exports: any;
}

declare module 'ajv/lib/cache' {
  declare module.exports: any;
}

declare module 'ajv/lib/compile/_rules' {
  declare module.exports: any;
}

declare module 'ajv/lib/compile/async' {
  declare module.exports: any;
}

declare module 'ajv/lib/compile/equal' {
  declare module.exports: any;
}

declare module 'ajv/lib/compile/error_classes' {
  declare module.exports: any;
}

declare module 'ajv/lib/compile/formats' {
  declare module.exports: any;
}

declare module 'ajv/lib/compile/index' {
  declare module.exports: any;
}

declare module 'ajv/lib/compile/resolve' {
  declare module.exports: any;
}

declare module 'ajv/lib/compile/rules' {
  declare module.exports: any;
}

declare module 'ajv/lib/compile/schema_obj' {
  declare module.exports: any;
}

declare module 'ajv/lib/compile/ucs2length' {
  declare module.exports: any;
}

declare module 'ajv/lib/compile/util' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/_limit' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/_limitItems' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/_limitLength' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/_limitProperties' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/allOf' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/anyOf' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/const' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/contains' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/custom' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/dependencies' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/enum' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/format' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/items' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/multipleOf' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/not' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/oneOf' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/pattern' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/properties' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/propertyNames' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/ref' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/required' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/uniqueItems' {
  declare module.exports: any;
}

declare module 'ajv/lib/dotjs/validate' {
  declare module.exports: any;
}

declare module 'ajv/lib/keyword' {
  declare module.exports: any;
}

declare module 'ajv/lib/patternGroups' {
  declare module.exports: any;
}

declare module 'ajv/scripts/bundle' {
  declare module.exports: any;
}

declare module 'ajv/scripts/compile-dots' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ajv/dist/ajv.bundle.js' {
  declare module.exports: $Exports<'ajv/dist/ajv.bundle'>;
}
declare module 'ajv/dist/ajv.min.js' {
  declare module.exports: $Exports<'ajv/dist/ajv.min'>;
}
declare module 'ajv/dist/nodent.min.js' {
  declare module.exports: $Exports<'ajv/dist/nodent.min'>;
}
declare module 'ajv/dist/regenerator.min.js' {
  declare module.exports: $Exports<'ajv/dist/regenerator.min'>;
}
declare module 'ajv/lib/$data.js' {
  declare module.exports: $Exports<'ajv/lib/$data'>;
}
declare module 'ajv/lib/ajv.js' {
  declare module.exports: $Exports<'ajv/lib/ajv'>;
}
declare module 'ajv/lib/cache.js' {
  declare module.exports: $Exports<'ajv/lib/cache'>;
}
declare module 'ajv/lib/compile/_rules.js' {
  declare module.exports: $Exports<'ajv/lib/compile/_rules'>;
}
declare module 'ajv/lib/compile/async.js' {
  declare module.exports: $Exports<'ajv/lib/compile/async'>;
}
declare module 'ajv/lib/compile/equal.js' {
  declare module.exports: $Exports<'ajv/lib/compile/equal'>;
}
declare module 'ajv/lib/compile/error_classes.js' {
  declare module.exports: $Exports<'ajv/lib/compile/error_classes'>;
}
declare module 'ajv/lib/compile/formats.js' {
  declare module.exports: $Exports<'ajv/lib/compile/formats'>;
}
declare module 'ajv/lib/compile/index.js' {
  declare module.exports: $Exports<'ajv/lib/compile/index'>;
}
declare module 'ajv/lib/compile/resolve.js' {
  declare module.exports: $Exports<'ajv/lib/compile/resolve'>;
}
declare module 'ajv/lib/compile/rules.js' {
  declare module.exports: $Exports<'ajv/lib/compile/rules'>;
}
declare module 'ajv/lib/compile/schema_obj.js' {
  declare module.exports: $Exports<'ajv/lib/compile/schema_obj'>;
}
declare module 'ajv/lib/compile/ucs2length.js' {
  declare module.exports: $Exports<'ajv/lib/compile/ucs2length'>;
}
declare module 'ajv/lib/compile/util.js' {
  declare module.exports: $Exports<'ajv/lib/compile/util'>;
}
declare module 'ajv/lib/dotjs/_limit.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/_limit'>;
}
declare module 'ajv/lib/dotjs/_limitItems.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/_limitItems'>;
}
declare module 'ajv/lib/dotjs/_limitLength.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/_limitLength'>;
}
declare module 'ajv/lib/dotjs/_limitProperties.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/_limitProperties'>;
}
declare module 'ajv/lib/dotjs/allOf.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/allOf'>;
}
declare module 'ajv/lib/dotjs/anyOf.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/anyOf'>;
}
declare module 'ajv/lib/dotjs/const.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/const'>;
}
declare module 'ajv/lib/dotjs/contains.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/contains'>;
}
declare module 'ajv/lib/dotjs/custom.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/custom'>;
}
declare module 'ajv/lib/dotjs/dependencies.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/dependencies'>;
}
declare module 'ajv/lib/dotjs/enum.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/enum'>;
}
declare module 'ajv/lib/dotjs/format.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/format'>;
}
declare module 'ajv/lib/dotjs/items.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/items'>;
}
declare module 'ajv/lib/dotjs/multipleOf.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/multipleOf'>;
}
declare module 'ajv/lib/dotjs/not.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/not'>;
}
declare module 'ajv/lib/dotjs/oneOf.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/oneOf'>;
}
declare module 'ajv/lib/dotjs/pattern.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/pattern'>;
}
declare module 'ajv/lib/dotjs/properties.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/properties'>;
}
declare module 'ajv/lib/dotjs/propertyNames.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/propertyNames'>;
}
declare module 'ajv/lib/dotjs/ref.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/ref'>;
}
declare module 'ajv/lib/dotjs/required.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/required'>;
}
declare module 'ajv/lib/dotjs/uniqueItems.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/uniqueItems'>;
}
declare module 'ajv/lib/dotjs/validate.js' {
  declare module.exports: $Exports<'ajv/lib/dotjs/validate'>;
}
declare module 'ajv/lib/keyword.js' {
  declare module.exports: $Exports<'ajv/lib/keyword'>;
}
declare module 'ajv/lib/patternGroups.js' {
  declare module.exports: $Exports<'ajv/lib/patternGroups'>;
}
declare module 'ajv/scripts/bundle.js' {
  declare module.exports: $Exports<'ajv/scripts/bundle'>;
}
declare module 'ajv/scripts/compile-dots.js' {
  declare module.exports: $Exports<'ajv/scripts/compile-dots'>;
}
