// flow-typed signature: c078382d7e796699b092573b6f3a8d8b
// flow-typed version: <<STUB>>/array-equal_v^1.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'array-equal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'array-equal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'array-equal/index' {
  declare module.exports: $Exports<'array-equal'>;
}
declare module 'array-equal/index.js' {
  declare module.exports: $Exports<'array-equal'>;
}
