// flow-typed signature: 89bfb20d284bc0f3db502c4026a3e237
// flow-typed version: <<STUB>>/array-equal_v^1.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'array-equal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'array-equal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'array-equal/index' {
  declare module.exports: $Exports<'array-equal'>;
}
declare module 'array-equal/index.js' {
  declare module.exports: $Exports<'array-equal'>;
}
