// flow-typed signature: 6d4f68ccfebee5f2cb15c54bed464b65
// flow-typed version: <<STUB>>/auth0-lock_v^10.14.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'auth0-lock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'auth0-lock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'auth0-lock/lib/__tests__/auth_button' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/__tests__/core/tenant' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/__tests__/core/web_api/legacy_api' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/__tests__/core/web_api/p2_api' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/__tests__/engine/classic/login' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/__tests__/engine/classic/mfa_login_screen' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/__tests__/engine/classic/sign_up_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/__tests__/engine/classic/sign_up_screen' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/__tests__/field/custom_input' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/__tests__/field/email_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/__tests__/field/login_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/__tests__/field/mfa_code_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/__tests__/field/option_selection_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/__tests__/field/password_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/__tests__/field/phone_number_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/__tests__/field/social_buttons_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/__tests__/field/username_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/__tests__/field/vcode_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/__tests__/testUtils' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/avatar' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/avatar/gravatar_provider' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/browser' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/database/actions' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/database/index' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/database/login_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/database/login_sign_up_tabs' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/database/mfa_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/database/password_reset_confirmation' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/database/reset_password_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/database/reset_password' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/database/sign_up_terms' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/database/signed_up_confirmation' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/enterprise' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/enterprise/actions' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/enterprise/hrd_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/enterprise/hrd_screen' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/enterprise/kerberos_screen' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/enterprise/quick_auth_screen' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/enterprise/single_sign_on_notice' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/passwordless/actions' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/passwordless/ask_vcode' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/passwordless/email_sent_confirmation' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/passwordless/index' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/connection/social/index' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/core' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/core/actions' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/core/client/index' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/core/client/settings' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/core/error_screen' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/core/index' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/core/loading_screen' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/core/pane_separator' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/core/remote_data' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/core/screen' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/core/signed_in_confirmation' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/core/sso/data' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/core/sso/index' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/core/sso/last_login_screen' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/core/tenant/index' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/core/tenant/settings' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/core/web_api' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/core/web_api/helper' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/core/web_api/legacy_api' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/core/web_api/p2_api' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/engine/classic' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/engine/classic/login' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/engine/classic/mfa_login_screen' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/engine/classic/sign_up_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/engine/classic/sign_up_screen' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/engine/passwordless' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/engine/passwordless/social_or_email_login_screen' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/engine/passwordless/social_or_phone_number_login_screen' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/field/actions' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/field/custom_input' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/field/email' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/field/email/email_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/field/index' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/field/mfa_code' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/field/mfa-code/mfa_code_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/field/option_selection_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/field/password' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/field/password/password_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/field/phone_number' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/field/phone-number/locations' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/field/phone-number/phone_number_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/field/social/social_buttons_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/field/username' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/field/username/username_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/field/vcode' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/field/vcode/vcode_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/ca' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/cs' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/da' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/de' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/en' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/es' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/fa' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/fi' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/fr' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/hu' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/it' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/ja' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/nb' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/nl' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/pl' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/pt-br' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/ru' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/sk' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/sv' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/tr' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/ua' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/vi' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/zh-tw' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/i18n/zh' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/index' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/passwordless' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/quick_auth' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/quick-auth/actions' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/store/index' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/sync' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/box' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/box/button' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/box/chrome' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/box/confirmation_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/box/container' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/box/global_message' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/box/header' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/box/multisize_slide' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/box/success_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/button/auth_button' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/input/checkbox_input' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/input/email_input' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/input/input_wrap' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/input/location_input' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/input/mfa_code_input' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/input/password_input' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/input/password/password_strength' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/input/phone_number_input' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/input/select_input' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/input/text_input' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/input/username_input' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/input/vcode_input' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/list' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/ui/pane/quick_auth_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/utils/atom' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/utils/cache' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/utils/cdn_utils' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/utils/data_utils' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/utils/fn_utils' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/utils/id_utils' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/utils/jsonp_utils' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/utils/media_utils' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/utils/preload_utils' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/utils/string_utils' {
  declare module.exports: any;
}

declare module 'auth0-lock/lib/utils/url_utils' {
  declare module.exports: any;
}

declare module 'auth0-lock/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'auth0-lock/lib/__tests__/auth_button.js' {
  declare module.exports: $Exports<'auth0-lock/lib/__tests__/auth_button'>;
}
declare module 'auth0-lock/lib/__tests__/core/tenant.js' {
  declare module.exports: $Exports<'auth0-lock/lib/__tests__/core/tenant'>;
}
declare module 'auth0-lock/lib/__tests__/core/web_api/legacy_api.js' {
  declare module.exports: $Exports<'auth0-lock/lib/__tests__/core/web_api/legacy_api'>;
}
declare module 'auth0-lock/lib/__tests__/core/web_api/p2_api.js' {
  declare module.exports: $Exports<'auth0-lock/lib/__tests__/core/web_api/p2_api'>;
}
declare module 'auth0-lock/lib/__tests__/engine/classic/login.js' {
  declare module.exports: $Exports<'auth0-lock/lib/__tests__/engine/classic/login'>;
}
declare module 'auth0-lock/lib/__tests__/engine/classic/mfa_login_screen.js' {
  declare module.exports: $Exports<'auth0-lock/lib/__tests__/engine/classic/mfa_login_screen'>;
}
declare module 'auth0-lock/lib/__tests__/engine/classic/sign_up_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/__tests__/engine/classic/sign_up_pane'>;
}
declare module 'auth0-lock/lib/__tests__/engine/classic/sign_up_screen.js' {
  declare module.exports: $Exports<'auth0-lock/lib/__tests__/engine/classic/sign_up_screen'>;
}
declare module 'auth0-lock/lib/__tests__/field/custom_input.js' {
  declare module.exports: $Exports<'auth0-lock/lib/__tests__/field/custom_input'>;
}
declare module 'auth0-lock/lib/__tests__/field/email_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/__tests__/field/email_pane'>;
}
declare module 'auth0-lock/lib/__tests__/field/login_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/__tests__/field/login_pane'>;
}
declare module 'auth0-lock/lib/__tests__/field/mfa_code_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/__tests__/field/mfa_code_pane'>;
}
declare module 'auth0-lock/lib/__tests__/field/option_selection_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/__tests__/field/option_selection_pane'>;
}
declare module 'auth0-lock/lib/__tests__/field/password_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/__tests__/field/password_pane'>;
}
declare module 'auth0-lock/lib/__tests__/field/phone_number_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/__tests__/field/phone_number_pane'>;
}
declare module 'auth0-lock/lib/__tests__/field/social_buttons_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/__tests__/field/social_buttons_pane'>;
}
declare module 'auth0-lock/lib/__tests__/field/username_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/__tests__/field/username_pane'>;
}
declare module 'auth0-lock/lib/__tests__/field/vcode_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/__tests__/field/vcode_pane'>;
}
declare module 'auth0-lock/lib/__tests__/testUtils.js' {
  declare module.exports: $Exports<'auth0-lock/lib/__tests__/testUtils'>;
}
declare module 'auth0-lock/lib/avatar.js' {
  declare module.exports: $Exports<'auth0-lock/lib/avatar'>;
}
declare module 'auth0-lock/lib/avatar/gravatar_provider.js' {
  declare module.exports: $Exports<'auth0-lock/lib/avatar/gravatar_provider'>;
}
declare module 'auth0-lock/lib/browser.js' {
  declare module.exports: $Exports<'auth0-lock/lib/browser'>;
}
declare module 'auth0-lock/lib/connection/database/actions.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/database/actions'>;
}
declare module 'auth0-lock/lib/connection/database/index.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/database/index'>;
}
declare module 'auth0-lock/lib/connection/database/login_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/database/login_pane'>;
}
declare module 'auth0-lock/lib/connection/database/login_sign_up_tabs.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/database/login_sign_up_tabs'>;
}
declare module 'auth0-lock/lib/connection/database/mfa_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/database/mfa_pane'>;
}
declare module 'auth0-lock/lib/connection/database/password_reset_confirmation.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/database/password_reset_confirmation'>;
}
declare module 'auth0-lock/lib/connection/database/reset_password_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/database/reset_password_pane'>;
}
declare module 'auth0-lock/lib/connection/database/reset_password.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/database/reset_password'>;
}
declare module 'auth0-lock/lib/connection/database/sign_up_terms.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/database/sign_up_terms'>;
}
declare module 'auth0-lock/lib/connection/database/signed_up_confirmation.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/database/signed_up_confirmation'>;
}
declare module 'auth0-lock/lib/connection/enterprise.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/enterprise'>;
}
declare module 'auth0-lock/lib/connection/enterprise/actions.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/enterprise/actions'>;
}
declare module 'auth0-lock/lib/connection/enterprise/hrd_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/enterprise/hrd_pane'>;
}
declare module 'auth0-lock/lib/connection/enterprise/hrd_screen.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/enterprise/hrd_screen'>;
}
declare module 'auth0-lock/lib/connection/enterprise/kerberos_screen.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/enterprise/kerberos_screen'>;
}
declare module 'auth0-lock/lib/connection/enterprise/quick_auth_screen.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/enterprise/quick_auth_screen'>;
}
declare module 'auth0-lock/lib/connection/enterprise/single_sign_on_notice.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/enterprise/single_sign_on_notice'>;
}
declare module 'auth0-lock/lib/connection/passwordless/actions.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/passwordless/actions'>;
}
declare module 'auth0-lock/lib/connection/passwordless/ask_vcode.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/passwordless/ask_vcode'>;
}
declare module 'auth0-lock/lib/connection/passwordless/email_sent_confirmation.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/passwordless/email_sent_confirmation'>;
}
declare module 'auth0-lock/lib/connection/passwordless/index.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/passwordless/index'>;
}
declare module 'auth0-lock/lib/connection/social/index.js' {
  declare module.exports: $Exports<'auth0-lock/lib/connection/social/index'>;
}
declare module 'auth0-lock/lib/core.js' {
  declare module.exports: $Exports<'auth0-lock/lib/core'>;
}
declare module 'auth0-lock/lib/core/actions.js' {
  declare module.exports: $Exports<'auth0-lock/lib/core/actions'>;
}
declare module 'auth0-lock/lib/core/client/index.js' {
  declare module.exports: $Exports<'auth0-lock/lib/core/client/index'>;
}
declare module 'auth0-lock/lib/core/client/settings.js' {
  declare module.exports: $Exports<'auth0-lock/lib/core/client/settings'>;
}
declare module 'auth0-lock/lib/core/error_screen.js' {
  declare module.exports: $Exports<'auth0-lock/lib/core/error_screen'>;
}
declare module 'auth0-lock/lib/core/index.js' {
  declare module.exports: $Exports<'auth0-lock/lib/core/index'>;
}
declare module 'auth0-lock/lib/core/loading_screen.js' {
  declare module.exports: $Exports<'auth0-lock/lib/core/loading_screen'>;
}
declare module 'auth0-lock/lib/core/pane_separator.js' {
  declare module.exports: $Exports<'auth0-lock/lib/core/pane_separator'>;
}
declare module 'auth0-lock/lib/core/remote_data.js' {
  declare module.exports: $Exports<'auth0-lock/lib/core/remote_data'>;
}
declare module 'auth0-lock/lib/core/screen.js' {
  declare module.exports: $Exports<'auth0-lock/lib/core/screen'>;
}
declare module 'auth0-lock/lib/core/signed_in_confirmation.js' {
  declare module.exports: $Exports<'auth0-lock/lib/core/signed_in_confirmation'>;
}
declare module 'auth0-lock/lib/core/sso/data.js' {
  declare module.exports: $Exports<'auth0-lock/lib/core/sso/data'>;
}
declare module 'auth0-lock/lib/core/sso/index.js' {
  declare module.exports: $Exports<'auth0-lock/lib/core/sso/index'>;
}
declare module 'auth0-lock/lib/core/sso/last_login_screen.js' {
  declare module.exports: $Exports<'auth0-lock/lib/core/sso/last_login_screen'>;
}
declare module 'auth0-lock/lib/core/tenant/index.js' {
  declare module.exports: $Exports<'auth0-lock/lib/core/tenant/index'>;
}
declare module 'auth0-lock/lib/core/tenant/settings.js' {
  declare module.exports: $Exports<'auth0-lock/lib/core/tenant/settings'>;
}
declare module 'auth0-lock/lib/core/web_api.js' {
  declare module.exports: $Exports<'auth0-lock/lib/core/web_api'>;
}
declare module 'auth0-lock/lib/core/web_api/helper.js' {
  declare module.exports: $Exports<'auth0-lock/lib/core/web_api/helper'>;
}
declare module 'auth0-lock/lib/core/web_api/legacy_api.js' {
  declare module.exports: $Exports<'auth0-lock/lib/core/web_api/legacy_api'>;
}
declare module 'auth0-lock/lib/core/web_api/p2_api.js' {
  declare module.exports: $Exports<'auth0-lock/lib/core/web_api/p2_api'>;
}
declare module 'auth0-lock/lib/engine/classic.js' {
  declare module.exports: $Exports<'auth0-lock/lib/engine/classic'>;
}
declare module 'auth0-lock/lib/engine/classic/login.js' {
  declare module.exports: $Exports<'auth0-lock/lib/engine/classic/login'>;
}
declare module 'auth0-lock/lib/engine/classic/mfa_login_screen.js' {
  declare module.exports: $Exports<'auth0-lock/lib/engine/classic/mfa_login_screen'>;
}
declare module 'auth0-lock/lib/engine/classic/sign_up_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/engine/classic/sign_up_pane'>;
}
declare module 'auth0-lock/lib/engine/classic/sign_up_screen.js' {
  declare module.exports: $Exports<'auth0-lock/lib/engine/classic/sign_up_screen'>;
}
declare module 'auth0-lock/lib/engine/passwordless.js' {
  declare module.exports: $Exports<'auth0-lock/lib/engine/passwordless'>;
}
declare module 'auth0-lock/lib/engine/passwordless/social_or_email_login_screen.js' {
  declare module.exports: $Exports<'auth0-lock/lib/engine/passwordless/social_or_email_login_screen'>;
}
declare module 'auth0-lock/lib/engine/passwordless/social_or_phone_number_login_screen.js' {
  declare module.exports: $Exports<'auth0-lock/lib/engine/passwordless/social_or_phone_number_login_screen'>;
}
declare module 'auth0-lock/lib/field/actions.js' {
  declare module.exports: $Exports<'auth0-lock/lib/field/actions'>;
}
declare module 'auth0-lock/lib/field/custom_input.js' {
  declare module.exports: $Exports<'auth0-lock/lib/field/custom_input'>;
}
declare module 'auth0-lock/lib/field/email.js' {
  declare module.exports: $Exports<'auth0-lock/lib/field/email'>;
}
declare module 'auth0-lock/lib/field/email/email_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/field/email/email_pane'>;
}
declare module 'auth0-lock/lib/field/index.js' {
  declare module.exports: $Exports<'auth0-lock/lib/field/index'>;
}
declare module 'auth0-lock/lib/field/mfa_code.js' {
  declare module.exports: $Exports<'auth0-lock/lib/field/mfa_code'>;
}
declare module 'auth0-lock/lib/field/mfa-code/mfa_code_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/field/mfa-code/mfa_code_pane'>;
}
declare module 'auth0-lock/lib/field/option_selection_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/field/option_selection_pane'>;
}
declare module 'auth0-lock/lib/field/password.js' {
  declare module.exports: $Exports<'auth0-lock/lib/field/password'>;
}
declare module 'auth0-lock/lib/field/password/password_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/field/password/password_pane'>;
}
declare module 'auth0-lock/lib/field/phone_number.js' {
  declare module.exports: $Exports<'auth0-lock/lib/field/phone_number'>;
}
declare module 'auth0-lock/lib/field/phone-number/locations.js' {
  declare module.exports: $Exports<'auth0-lock/lib/field/phone-number/locations'>;
}
declare module 'auth0-lock/lib/field/phone-number/phone_number_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/field/phone-number/phone_number_pane'>;
}
declare module 'auth0-lock/lib/field/social/social_buttons_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/field/social/social_buttons_pane'>;
}
declare module 'auth0-lock/lib/field/username.js' {
  declare module.exports: $Exports<'auth0-lock/lib/field/username'>;
}
declare module 'auth0-lock/lib/field/username/username_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/field/username/username_pane'>;
}
declare module 'auth0-lock/lib/field/vcode.js' {
  declare module.exports: $Exports<'auth0-lock/lib/field/vcode'>;
}
declare module 'auth0-lock/lib/field/vcode/vcode_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/field/vcode/vcode_pane'>;
}
declare module 'auth0-lock/lib/i18n.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n'>;
}
declare module 'auth0-lock/lib/i18n/ca.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/ca'>;
}
declare module 'auth0-lock/lib/i18n/cs.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/cs'>;
}
declare module 'auth0-lock/lib/i18n/da.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/da'>;
}
declare module 'auth0-lock/lib/i18n/de.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/de'>;
}
declare module 'auth0-lock/lib/i18n/en.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/en'>;
}
declare module 'auth0-lock/lib/i18n/es.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/es'>;
}
declare module 'auth0-lock/lib/i18n/fa.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/fa'>;
}
declare module 'auth0-lock/lib/i18n/fi.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/fi'>;
}
declare module 'auth0-lock/lib/i18n/fr.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/fr'>;
}
declare module 'auth0-lock/lib/i18n/hu.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/hu'>;
}
declare module 'auth0-lock/lib/i18n/it.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/it'>;
}
declare module 'auth0-lock/lib/i18n/ja.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/ja'>;
}
declare module 'auth0-lock/lib/i18n/nb.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/nb'>;
}
declare module 'auth0-lock/lib/i18n/nl.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/nl'>;
}
declare module 'auth0-lock/lib/i18n/pl.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/pl'>;
}
declare module 'auth0-lock/lib/i18n/pt-br.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/pt-br'>;
}
declare module 'auth0-lock/lib/i18n/ru.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/ru'>;
}
declare module 'auth0-lock/lib/i18n/sk.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/sk'>;
}
declare module 'auth0-lock/lib/i18n/sv.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/sv'>;
}
declare module 'auth0-lock/lib/i18n/tr.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/tr'>;
}
declare module 'auth0-lock/lib/i18n/ua.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/ua'>;
}
declare module 'auth0-lock/lib/i18n/vi.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/vi'>;
}
declare module 'auth0-lock/lib/i18n/zh-tw.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/zh-tw'>;
}
declare module 'auth0-lock/lib/i18n/zh.js' {
  declare module.exports: $Exports<'auth0-lock/lib/i18n/zh'>;
}
declare module 'auth0-lock/lib/index.js' {
  declare module.exports: $Exports<'auth0-lock/lib/index'>;
}
declare module 'auth0-lock/lib/passwordless.js' {
  declare module.exports: $Exports<'auth0-lock/lib/passwordless'>;
}
declare module 'auth0-lock/lib/quick_auth.js' {
  declare module.exports: $Exports<'auth0-lock/lib/quick_auth'>;
}
declare module 'auth0-lock/lib/quick-auth/actions.js' {
  declare module.exports: $Exports<'auth0-lock/lib/quick-auth/actions'>;
}
declare module 'auth0-lock/lib/store/index.js' {
  declare module.exports: $Exports<'auth0-lock/lib/store/index'>;
}
declare module 'auth0-lock/lib/sync.js' {
  declare module.exports: $Exports<'auth0-lock/lib/sync'>;
}
declare module 'auth0-lock/lib/ui/box.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/box'>;
}
declare module 'auth0-lock/lib/ui/box/button.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/box/button'>;
}
declare module 'auth0-lock/lib/ui/box/chrome.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/box/chrome'>;
}
declare module 'auth0-lock/lib/ui/box/confirmation_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/box/confirmation_pane'>;
}
declare module 'auth0-lock/lib/ui/box/container.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/box/container'>;
}
declare module 'auth0-lock/lib/ui/box/global_message.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/box/global_message'>;
}
declare module 'auth0-lock/lib/ui/box/header.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/box/header'>;
}
declare module 'auth0-lock/lib/ui/box/multisize_slide.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/box/multisize_slide'>;
}
declare module 'auth0-lock/lib/ui/box/success_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/box/success_pane'>;
}
declare module 'auth0-lock/lib/ui/button/auth_button.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/button/auth_button'>;
}
declare module 'auth0-lock/lib/ui/input/checkbox_input.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/input/checkbox_input'>;
}
declare module 'auth0-lock/lib/ui/input/email_input.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/input/email_input'>;
}
declare module 'auth0-lock/lib/ui/input/input_wrap.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/input/input_wrap'>;
}
declare module 'auth0-lock/lib/ui/input/location_input.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/input/location_input'>;
}
declare module 'auth0-lock/lib/ui/input/mfa_code_input.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/input/mfa_code_input'>;
}
declare module 'auth0-lock/lib/ui/input/password_input.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/input/password_input'>;
}
declare module 'auth0-lock/lib/ui/input/password/password_strength.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/input/password/password_strength'>;
}
declare module 'auth0-lock/lib/ui/input/phone_number_input.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/input/phone_number_input'>;
}
declare module 'auth0-lock/lib/ui/input/select_input.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/input/select_input'>;
}
declare module 'auth0-lock/lib/ui/input/text_input.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/input/text_input'>;
}
declare module 'auth0-lock/lib/ui/input/username_input.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/input/username_input'>;
}
declare module 'auth0-lock/lib/ui/input/vcode_input.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/input/vcode_input'>;
}
declare module 'auth0-lock/lib/ui/list.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/list'>;
}
declare module 'auth0-lock/lib/ui/pane/quick_auth_pane.js' {
  declare module.exports: $Exports<'auth0-lock/lib/ui/pane/quick_auth_pane'>;
}
declare module 'auth0-lock/lib/utils/atom.js' {
  declare module.exports: $Exports<'auth0-lock/lib/utils/atom'>;
}
declare module 'auth0-lock/lib/utils/cache.js' {
  declare module.exports: $Exports<'auth0-lock/lib/utils/cache'>;
}
declare module 'auth0-lock/lib/utils/cdn_utils.js' {
  declare module.exports: $Exports<'auth0-lock/lib/utils/cdn_utils'>;
}
declare module 'auth0-lock/lib/utils/data_utils.js' {
  declare module.exports: $Exports<'auth0-lock/lib/utils/data_utils'>;
}
declare module 'auth0-lock/lib/utils/fn_utils.js' {
  declare module.exports: $Exports<'auth0-lock/lib/utils/fn_utils'>;
}
declare module 'auth0-lock/lib/utils/id_utils.js' {
  declare module.exports: $Exports<'auth0-lock/lib/utils/id_utils'>;
}
declare module 'auth0-lock/lib/utils/jsonp_utils.js' {
  declare module.exports: $Exports<'auth0-lock/lib/utils/jsonp_utils'>;
}
declare module 'auth0-lock/lib/utils/media_utils.js' {
  declare module.exports: $Exports<'auth0-lock/lib/utils/media_utils'>;
}
declare module 'auth0-lock/lib/utils/preload_utils.js' {
  declare module.exports: $Exports<'auth0-lock/lib/utils/preload_utils'>;
}
declare module 'auth0-lock/lib/utils/string_utils.js' {
  declare module.exports: $Exports<'auth0-lock/lib/utils/string_utils'>;
}
declare module 'auth0-lock/lib/utils/url_utils.js' {
  declare module.exports: $Exports<'auth0-lock/lib/utils/url_utils'>;
}
declare module 'auth0-lock/webpack.config.js' {
  declare module.exports: $Exports<'auth0-lock/webpack.config'>;
}
