// flow-typed signature: 7e6efad11a6014fa4f6d216224ee263e
// flow-typed version: <<STUB>>/babel-plugin-transform-inline-environment-variables_v^0.4.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-inline-environment-variables'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-inline-environment-variables' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-inline-environment-variables/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-inline-environment-variables/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-inline-environment-variables/lib/index'>;
}
