// flow-typed signature: 73328285f9626f2a56e1ef32a6b2564d
// flow-typed version: <<STUB>>/babel-plugin-inline-dotenv_v^1.1.2/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-inline-dotenv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-inline-dotenv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-inline-dotenv/src/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-inline-dotenv/test/fixtures/code-simple-env-variable/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-inline-dotenv/test/fixtures/code-simple-env-variable/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-inline-dotenv/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-inline-dotenv/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-inline-dotenv/src/index'>;
}
declare module 'babel-plugin-inline-dotenv/test/fixtures/code-simple-env-variable/actual.js' {
  declare module.exports: $Exports<'babel-plugin-inline-dotenv/test/fixtures/code-simple-env-variable/actual'>;
}
declare module 'babel-plugin-inline-dotenv/test/fixtures/code-simple-env-variable/expected.js' {
  declare module.exports: $Exports<'babel-plugin-inline-dotenv/test/fixtures/code-simple-env-variable/expected'>;
}
declare module 'babel-plugin-inline-dotenv/test/index.js' {
  declare module.exports: $Exports<'babel-plugin-inline-dotenv/test/index'>;
}
