// flow-typed signature: dc8aa53ff66d1f7b9ca82becc1c3b3a0
// flow-typed version: <<STUB>>/babel-plugin-transform-react-constant-elements_v^6.3.13/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-react-constant-elements'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-react-constant-elements' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-react-constant-elements/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-react-constant-elements/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-constant-elements/lib/index'>;
}
