// flow-typed signature: d4c7ae2de79f9f4d70baac341b8a3ba3
// flow-typed version: <<STUB>>/babel-plugin-module-resolver_v^3.1.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-module-resolver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-module-resolver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-module-resolver/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-module-resolver/lib/log' {
  declare module.exports: any;
}

declare module 'babel-plugin-module-resolver/lib/mapToRelative' {
  declare module.exports: any;
}

declare module 'babel-plugin-module-resolver/lib/normalizeOptions' {
  declare module.exports: any;
}

declare module 'babel-plugin-module-resolver/lib/resolvePath' {
  declare module.exports: any;
}

declare module 'babel-plugin-module-resolver/lib/transformers/call' {
  declare module.exports: any;
}

declare module 'babel-plugin-module-resolver/lib/transformers/import' {
  declare module.exports: any;
}

declare module 'babel-plugin-module-resolver/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-module-resolver/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-module-resolver/lib/index'>;
}
declare module 'babel-plugin-module-resolver/lib/log.js' {
  declare module.exports: $Exports<'babel-plugin-module-resolver/lib/log'>;
}
declare module 'babel-plugin-module-resolver/lib/mapToRelative.js' {
  declare module.exports: $Exports<'babel-plugin-module-resolver/lib/mapToRelative'>;
}
declare module 'babel-plugin-module-resolver/lib/normalizeOptions.js' {
  declare module.exports: $Exports<'babel-plugin-module-resolver/lib/normalizeOptions'>;
}
declare module 'babel-plugin-module-resolver/lib/resolvePath.js' {
  declare module.exports: $Exports<'babel-plugin-module-resolver/lib/resolvePath'>;
}
declare module 'babel-plugin-module-resolver/lib/transformers/call.js' {
  declare module.exports: $Exports<'babel-plugin-module-resolver/lib/transformers/call'>;
}
declare module 'babel-plugin-module-resolver/lib/transformers/import.js' {
  declare module.exports: $Exports<'babel-plugin-module-resolver/lib/transformers/import'>;
}
declare module 'babel-plugin-module-resolver/lib/utils.js' {
  declare module.exports: $Exports<'babel-plugin-module-resolver/lib/utils'>;
}
