// flow-typed signature: ce78cb77524ea17d404b5db9f21ea3d4
// flow-typed version: <<STUB>>/bcryptjs_v^2.4.3/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bcryptjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bcryptjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bcryptjs/dist/bcrypt' {
  declare module.exports: any;
}

declare module 'bcryptjs/dist/bcrypt.min' {
  declare module.exports: any;
}

declare module 'bcryptjs/externs/bcrypt' {
  declare module.exports: any;
}

declare module 'bcryptjs/externs/minimal-env' {
  declare module.exports: any;
}

declare module 'bcryptjs/scripts/build' {
  declare module.exports: any;
}

declare module 'bcryptjs/src/bcrypt' {
  declare module.exports: any;
}

declare module 'bcryptjs/src/bcrypt/impl' {
  declare module.exports: any;
}

declare module 'bcryptjs/src/bcrypt/prng/accum' {
  declare module.exports: any;
}

declare module 'bcryptjs/src/bcrypt/prng/isaac' {
  declare module.exports: any;
}

declare module 'bcryptjs/src/bcrypt/util' {
  declare module.exports: any;
}

declare module 'bcryptjs/src/bcrypt/util/base64' {
  declare module.exports: any;
}

declare module 'bcryptjs/src/wrap' {
  declare module.exports: any;
}

declare module 'bcryptjs/tests/suite' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bcryptjs/dist/bcrypt.js' {
  declare module.exports: $Exports<'bcryptjs/dist/bcrypt'>;
}
declare module 'bcryptjs/dist/bcrypt.min.js' {
  declare module.exports: $Exports<'bcryptjs/dist/bcrypt.min'>;
}
declare module 'bcryptjs/externs/bcrypt.js' {
  declare module.exports: $Exports<'bcryptjs/externs/bcrypt'>;
}
declare module 'bcryptjs/externs/minimal-env.js' {
  declare module.exports: $Exports<'bcryptjs/externs/minimal-env'>;
}
declare module 'bcryptjs/index' {
  declare module.exports: $Exports<'bcryptjs'>;
}
declare module 'bcryptjs/index.js' {
  declare module.exports: $Exports<'bcryptjs'>;
}
declare module 'bcryptjs/scripts/build.js' {
  declare module.exports: $Exports<'bcryptjs/scripts/build'>;
}
declare module 'bcryptjs/src/bcrypt.js' {
  declare module.exports: $Exports<'bcryptjs/src/bcrypt'>;
}
declare module 'bcryptjs/src/bcrypt/impl.js' {
  declare module.exports: $Exports<'bcryptjs/src/bcrypt/impl'>;
}
declare module 'bcryptjs/src/bcrypt/prng/accum.js' {
  declare module.exports: $Exports<'bcryptjs/src/bcrypt/prng/accum'>;
}
declare module 'bcryptjs/src/bcrypt/prng/isaac.js' {
  declare module.exports: $Exports<'bcryptjs/src/bcrypt/prng/isaac'>;
}
declare module 'bcryptjs/src/bcrypt/util.js' {
  declare module.exports: $Exports<'bcryptjs/src/bcrypt/util'>;
}
declare module 'bcryptjs/src/bcrypt/util/base64.js' {
  declare module.exports: $Exports<'bcryptjs/src/bcrypt/util/base64'>;
}
declare module 'bcryptjs/src/wrap.js' {
  declare module.exports: $Exports<'bcryptjs/src/wrap'>;
}
declare module 'bcryptjs/tests/suite.js' {
  declare module.exports: $Exports<'bcryptjs/tests/suite'>;
}
