// flow-typed signature: c1637160cef5355bc4fe46c6bf66c64b
// flow-typed version: <<STUB>>/caniuse-api_v^1.5.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'caniuse-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'caniuse-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'caniuse-api/dist/index' {
  declare module.exports: any;
}

declare module 'caniuse-api/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'caniuse-api/dist/index.js' {
  declare module.exports: $Exports<'caniuse-api/dist/index'>;
}
declare module 'caniuse-api/dist/utils.js' {
  declare module.exports: $Exports<'caniuse-api/dist/utils'>;
}
