// flow-typed signature: 2987905fff4cc1b8e60198a5fd1691ee
// flow-typed version: <<STUB>>/cookie_v^0.3.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cookie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cookie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'cookie/index' {
  declare module.exports: $Exports<'cookie'>;
}
declare module 'cookie/index.js' {
  declare module.exports: $Exports<'cookie'>;
}
