// flow-typed signature: 609218ad35ad59d86d8be6045238ee8d
// flow-typed version: <<STUB>>/diacritics-map_v^0.1.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'diacritics-map'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'diacritics-map' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'diacritics-map/index' {
  declare module.exports: $Exports<'diacritics-map'>;
}
declare module 'diacritics-map/index.js' {
  declare module.exports: $Exports<'diacritics-map'>;
}
