// flow-typed signature: 1664657b7af3997d762a3189ba1760e4
// flow-typed version: <<STUB>>/dotenv_v^6.0.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dotenv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dotenv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dotenv/config' {
  declare module.exports: any;
}

declare module 'dotenv/lib/cli-options' {
  declare module.exports: any;
}

declare module 'dotenv/lib/main' {
  declare module.exports: any;
}

declare module 'dotenv/tests/test-cli-options' {
  declare module.exports: any;
}

declare module 'dotenv/tests/test-config-cli' {
  declare module.exports: any;
}

declare module 'dotenv/tests/test-config' {
  declare module.exports: any;
}

declare module 'dotenv/tests/test-parse' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dotenv/config.js' {
  declare module.exports: $Exports<'dotenv/config'>;
}
declare module 'dotenv/lib/cli-options.js' {
  declare module.exports: $Exports<'dotenv/lib/cli-options'>;
}
declare module 'dotenv/lib/main.js' {
  declare module.exports: $Exports<'dotenv/lib/main'>;
}
declare module 'dotenv/tests/test-cli-options.js' {
  declare module.exports: $Exports<'dotenv/tests/test-cli-options'>;
}
declare module 'dotenv/tests/test-config-cli.js' {
  declare module.exports: $Exports<'dotenv/tests/test-config-cli'>;
}
declare module 'dotenv/tests/test-config.js' {
  declare module.exports: $Exports<'dotenv/tests/test-config'>;
}
declare module 'dotenv/tests/test-parse.js' {
  declare module.exports: $Exports<'dotenv/tests/test-parse'>;
}
