// flow-typed signature: 3f812f3275662d591d48505cec05b998
// flow-typed version: <<STUB>>/dotenv_v^6.0.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dotenv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dotenv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dotenv/config' {
  declare module.exports: any;
}

declare module 'dotenv/flow-typed/npm/sinon_vx.x.x' {
  declare module.exports: any;
}

declare module 'dotenv/flow-typed/npm/tap_vx.x.x' {
  declare module.exports: any;
}

declare module 'dotenv/lib/cli-options' {
  declare module.exports: any;
}

declare module 'dotenv/lib/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dotenv/config.js' {
  declare module.exports: $Exports<'dotenv/config'>;
}
declare module 'dotenv/flow-typed/npm/sinon_vx.x.x.js' {
  declare module.exports: $Exports<'dotenv/flow-typed/npm/sinon_vx.x.x'>;
}
declare module 'dotenv/flow-typed/npm/tap_vx.x.x.js' {
  declare module.exports: $Exports<'dotenv/flow-typed/npm/tap_vx.x.x'>;
}
declare module 'dotenv/lib/cli-options.js' {
  declare module.exports: $Exports<'dotenv/lib/cli-options'>;
}
declare module 'dotenv/lib/main.js' {
  declare module.exports: $Exports<'dotenv/lib/main'>;
}
