// flow-typed signature: 8ee78ddcff9d58e786b9f6484a9de970
// flow-typed version: <<STUB>>/empty_v^0.10.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'empty'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'empty' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'empty/array' {
  declare module.exports: any;
}

declare module 'empty/function' {
  declare module.exports: any;
}

declare module 'empty/functionThatReturns' {
  declare module.exports: any;
}

declare module 'empty/functionThatReturnsArgument' {
  declare module.exports: any;
}

declare module 'empty/functionThatReturnsFalse' {
  declare module.exports: any;
}

declare module 'empty/functionThatReturnsNull' {
  declare module.exports: any;
}

declare module 'empty/functionThatReturnsThis' {
  declare module.exports: any;
}

declare module 'empty/functionThatReturnsTrue' {
  declare module.exports: any;
}

declare module 'empty/object' {
  declare module.exports: any;
}

// Filename aliases
declare module 'empty/array.js' {
  declare module.exports: $Exports<'empty/array'>;
}
declare module 'empty/function.js' {
  declare module.exports: $Exports<'empty/function'>;
}
declare module 'empty/functionThatReturns.js' {
  declare module.exports: $Exports<'empty/functionThatReturns'>;
}
declare module 'empty/functionThatReturnsArgument.js' {
  declare module.exports: $Exports<'empty/functionThatReturnsArgument'>;
}
declare module 'empty/functionThatReturnsFalse.js' {
  declare module.exports: $Exports<'empty/functionThatReturnsFalse'>;
}
declare module 'empty/functionThatReturnsNull.js' {
  declare module.exports: $Exports<'empty/functionThatReturnsNull'>;
}
declare module 'empty/functionThatReturnsThis.js' {
  declare module.exports: $Exports<'empty/functionThatReturnsThis'>;
}
declare module 'empty/functionThatReturnsTrue.js' {
  declare module.exports: $Exports<'empty/functionThatReturnsTrue'>;
}
declare module 'empty/index' {
  declare module.exports: $Exports<'empty'>;
}
declare module 'empty/index.js' {
  declare module.exports: $Exports<'empty'>;
}
declare module 'empty/object.js' {
  declare module.exports: $Exports<'empty/object'>;
}
