// flow-typed signature: 394b5ea6a31991b07d70cdf7b28db460
// flow-typed version: <<STUB>>/env-cmd_v^7.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'env-cmd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'env-cmd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'env-cmd/bin/env-cmd' {
  declare module.exports: any;
}

declare module 'env-cmd/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'env-cmd/bin/env-cmd.js' {
  declare module.exports: $Exports<'env-cmd/bin/env-cmd'>;
}
declare module 'env-cmd/lib/index.js' {
  declare module.exports: $Exports<'env-cmd/lib/index'>;
}
