// flow-typed signature: a8cf3887e9ba17af7993a523b70f0667
// flow-typed version: <<STUB>>/eslint-plugin-fp_v^2.2.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-fp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-fp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-fp/rules/no-arguments' {
  declare module.exports: any;
}

declare module 'eslint-plugin-fp/rules/no-class' {
  declare module.exports: any;
}

declare module 'eslint-plugin-fp/rules/no-delete' {
  declare module.exports: any;
}

declare module 'eslint-plugin-fp/rules/no-events' {
  declare module.exports: any;
}

declare module 'eslint-plugin-fp/rules/no-get-set' {
  declare module.exports: any;
}

declare module 'eslint-plugin-fp/rules/no-let' {
  declare module.exports: any;
}

declare module 'eslint-plugin-fp/rules/no-loops' {
  declare module.exports: any;
}

declare module 'eslint-plugin-fp/rules/no-mutating-assign' {
  declare module.exports: any;
}

declare module 'eslint-plugin-fp/rules/no-mutating-methods' {
  declare module.exports: any;
}

declare module 'eslint-plugin-fp/rules/no-mutation' {
  declare module.exports: any;
}

declare module 'eslint-plugin-fp/rules/no-nil' {
  declare module.exports: any;
}

declare module 'eslint-plugin-fp/rules/no-proxy' {
  declare module.exports: any;
}

declare module 'eslint-plugin-fp/rules/no-rest-parameters' {
  declare module.exports: any;
}

declare module 'eslint-plugin-fp/rules/no-this' {
  declare module.exports: any;
}

declare module 'eslint-plugin-fp/rules/no-throw' {
  declare module.exports: any;
}

declare module 'eslint-plugin-fp/rules/no-unused-expression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-fp/rules/no-valueof-field' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-fp/index' {
  declare module.exports: $Exports<'eslint-plugin-fp'>;
}
declare module 'eslint-plugin-fp/index.js' {
  declare module.exports: $Exports<'eslint-plugin-fp'>;
}
declare module 'eslint-plugin-fp/rules/no-arguments.js' {
  declare module.exports: $Exports<'eslint-plugin-fp/rules/no-arguments'>;
}
declare module 'eslint-plugin-fp/rules/no-class.js' {
  declare module.exports: $Exports<'eslint-plugin-fp/rules/no-class'>;
}
declare module 'eslint-plugin-fp/rules/no-delete.js' {
  declare module.exports: $Exports<'eslint-plugin-fp/rules/no-delete'>;
}
declare module 'eslint-plugin-fp/rules/no-events.js' {
  declare module.exports: $Exports<'eslint-plugin-fp/rules/no-events'>;
}
declare module 'eslint-plugin-fp/rules/no-get-set.js' {
  declare module.exports: $Exports<'eslint-plugin-fp/rules/no-get-set'>;
}
declare module 'eslint-plugin-fp/rules/no-let.js' {
  declare module.exports: $Exports<'eslint-plugin-fp/rules/no-let'>;
}
declare module 'eslint-plugin-fp/rules/no-loops.js' {
  declare module.exports: $Exports<'eslint-plugin-fp/rules/no-loops'>;
}
declare module 'eslint-plugin-fp/rules/no-mutating-assign.js' {
  declare module.exports: $Exports<'eslint-plugin-fp/rules/no-mutating-assign'>;
}
declare module 'eslint-plugin-fp/rules/no-mutating-methods.js' {
  declare module.exports: $Exports<'eslint-plugin-fp/rules/no-mutating-methods'>;
}
declare module 'eslint-plugin-fp/rules/no-mutation.js' {
  declare module.exports: $Exports<'eslint-plugin-fp/rules/no-mutation'>;
}
declare module 'eslint-plugin-fp/rules/no-nil.js' {
  declare module.exports: $Exports<'eslint-plugin-fp/rules/no-nil'>;
}
declare module 'eslint-plugin-fp/rules/no-proxy.js' {
  declare module.exports: $Exports<'eslint-plugin-fp/rules/no-proxy'>;
}
declare module 'eslint-plugin-fp/rules/no-rest-parameters.js' {
  declare module.exports: $Exports<'eslint-plugin-fp/rules/no-rest-parameters'>;
}
declare module 'eslint-plugin-fp/rules/no-this.js' {
  declare module.exports: $Exports<'eslint-plugin-fp/rules/no-this'>;
}
declare module 'eslint-plugin-fp/rules/no-throw.js' {
  declare module.exports: $Exports<'eslint-plugin-fp/rules/no-throw'>;
}
declare module 'eslint-plugin-fp/rules/no-unused-expression.js' {
  declare module.exports: $Exports<'eslint-plugin-fp/rules/no-unused-expression'>;
}
declare module 'eslint-plugin-fp/rules/no-valueof-field.js' {
  declare module.exports: $Exports<'eslint-plugin-fp/rules/no-valueof-field'>;
}
