// flow-typed signature: 258d4e2d572c2861c3cafe4da14a51e2
// flow-typed version: <<STUB>>/esm_v^3.0.71/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esm/esm' {
  declare module.exports: any;
}

declare module 'esm/esm/loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esm/esm.js' {
  declare module.exports: $Exports<'esm/esm'>;
}
declare module 'esm/esm/loader.js' {
  declare module.exports: $Exports<'esm/esm/loader'>;
}
declare module 'esm/index' {
  declare module.exports: $Exports<'esm'>;
}
declare module 'esm/index.js' {
  declare module.exports: $Exports<'esm'>;
}
