// flow-typed signature: ade6fee19a28af50791a6ac094022629
// flow-typed version: <<STUB>>/fela-plugin-validator_v^4.1.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fela-plugin-validator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fela-plugin-validator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fela-plugin-validator/dist/fela-plugin-validator' {
  declare module.exports: any;
}

declare module 'fela-plugin-validator/dist/fela-plugin-validator.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fela-plugin-validator/dist/fela-plugin-validator.js' {
  declare module.exports: $Exports<'fela-plugin-validator/dist/fela-plugin-validator'>;
}
declare module 'fela-plugin-validator/dist/fela-plugin-validator.min.js' {
  declare module.exports: $Exports<'fela-plugin-validator/dist/fela-plugin-validator.min'>;
}
declare module 'fela-plugin-validator/index' {
  declare module.exports: $Exports<'fela-plugin-validator'>;
}
declare module 'fela-plugin-validator/index.js' {
  declare module.exports: $Exports<'fela-plugin-validator'>;
}
