// flow-typed signature: 16bf8bf937459ec092a882e8cfaafaa1
// flow-typed version: <<STUB>>/fela-plugin-placeholder-prefixer_v^5.0.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fela-plugin-placeholder-prefixer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fela-plugin-placeholder-prefixer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fela-plugin-placeholder-prefixer/es/index' {
  declare module.exports: any;
}

declare module 'fela-plugin-placeholder-prefixer/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fela-plugin-placeholder-prefixer/es/index.js' {
  declare module.exports: $Exports<'fela-plugin-placeholder-prefixer/es/index'>;
}
declare module 'fela-plugin-placeholder-prefixer/lib/index.js' {
  declare module.exports: $Exports<'fela-plugin-placeholder-prefixer/lib/index'>;
}
