// flow-typed signature: 55d655e1723cd7e11b6c89f3eb9b21dc
// flow-typed version: <<STUB>>/fela-dom_v^6.0.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fela-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fela-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fela-dom/es/dom/connectDOMNodes' {
  declare module.exports: any;
}

declare module 'fela-dom/es/dom/createDOMNode' {
  declare module.exports: any;
}

declare module 'fela-dom/es/dom/createDOMSubscription' {
  declare module.exports: any;
}

declare module 'fela-dom/es/dom/findDOMNodes' {
  declare module.exports: any;
}

declare module 'fela-dom/es/dom/getDOMNode' {
  declare module.exports: any;
}

declare module 'fela-dom/es/dom/initDOMNode' {
  declare module.exports: any;
}

declare module 'fela-dom/es/dom/rehydration/rehydrateCache' {
  declare module.exports: any;
}

declare module 'fela-dom/es/dom/rehydration/rehydrateRules' {
  declare module.exports: any;
}

declare module 'fela-dom/es/dom/rehydration/rehydrateSupportRules' {
  declare module.exports: any;
}

declare module 'fela-dom/es/dom/render' {
  declare module.exports: any;
}

declare module 'fela-dom/es/index' {
  declare module.exports: any;
}

declare module 'fela-dom/es/server/renderToMarkup' {
  declare module.exports: any;
}

declare module 'fela-dom/es/server/renderToSheetList' {
  declare module.exports: any;
}

declare module 'fela-dom/lib/dom/connectDOMNodes' {
  declare module.exports: any;
}

declare module 'fela-dom/lib/dom/createDOMNode' {
  declare module.exports: any;
}

declare module 'fela-dom/lib/dom/createDOMSubscription' {
  declare module.exports: any;
}

declare module 'fela-dom/lib/dom/findDOMNodes' {
  declare module.exports: any;
}

declare module 'fela-dom/lib/dom/getDOMNode' {
  declare module.exports: any;
}

declare module 'fela-dom/lib/dom/initDOMNode' {
  declare module.exports: any;
}

declare module 'fela-dom/lib/dom/rehydration/rehydrateCache' {
  declare module.exports: any;
}

declare module 'fela-dom/lib/dom/rehydration/rehydrateRules' {
  declare module.exports: any;
}

declare module 'fela-dom/lib/dom/rehydration/rehydrateSupportRules' {
  declare module.exports: any;
}

declare module 'fela-dom/lib/dom/render' {
  declare module.exports: any;
}

declare module 'fela-dom/lib/index' {
  declare module.exports: any;
}

declare module 'fela-dom/lib/server/renderToMarkup' {
  declare module.exports: any;
}

declare module 'fela-dom/lib/server/renderToSheetList' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fela-dom/es/dom/connectDOMNodes.js' {
  declare module.exports: $Exports<'fela-dom/es/dom/connectDOMNodes'>;
}
declare module 'fela-dom/es/dom/createDOMNode.js' {
  declare module.exports: $Exports<'fela-dom/es/dom/createDOMNode'>;
}
declare module 'fela-dom/es/dom/createDOMSubscription.js' {
  declare module.exports: $Exports<'fela-dom/es/dom/createDOMSubscription'>;
}
declare module 'fela-dom/es/dom/findDOMNodes.js' {
  declare module.exports: $Exports<'fela-dom/es/dom/findDOMNodes'>;
}
declare module 'fela-dom/es/dom/getDOMNode.js' {
  declare module.exports: $Exports<'fela-dom/es/dom/getDOMNode'>;
}
declare module 'fela-dom/es/dom/initDOMNode.js' {
  declare module.exports: $Exports<'fela-dom/es/dom/initDOMNode'>;
}
declare module 'fela-dom/es/dom/rehydration/rehydrateCache.js' {
  declare module.exports: $Exports<'fela-dom/es/dom/rehydration/rehydrateCache'>;
}
declare module 'fela-dom/es/dom/rehydration/rehydrateRules.js' {
  declare module.exports: $Exports<'fela-dom/es/dom/rehydration/rehydrateRules'>;
}
declare module 'fela-dom/es/dom/rehydration/rehydrateSupportRules.js' {
  declare module.exports: $Exports<'fela-dom/es/dom/rehydration/rehydrateSupportRules'>;
}
declare module 'fela-dom/es/dom/render.js' {
  declare module.exports: $Exports<'fela-dom/es/dom/render'>;
}
declare module 'fela-dom/es/index.js' {
  declare module.exports: $Exports<'fela-dom/es/index'>;
}
declare module 'fela-dom/es/server/renderToMarkup.js' {
  declare module.exports: $Exports<'fela-dom/es/server/renderToMarkup'>;
}
declare module 'fela-dom/es/server/renderToSheetList.js' {
  declare module.exports: $Exports<'fela-dom/es/server/renderToSheetList'>;
}
declare module 'fela-dom/lib/dom/connectDOMNodes.js' {
  declare module.exports: $Exports<'fela-dom/lib/dom/connectDOMNodes'>;
}
declare module 'fela-dom/lib/dom/createDOMNode.js' {
  declare module.exports: $Exports<'fela-dom/lib/dom/createDOMNode'>;
}
declare module 'fela-dom/lib/dom/createDOMSubscription.js' {
  declare module.exports: $Exports<'fela-dom/lib/dom/createDOMSubscription'>;
}
declare module 'fela-dom/lib/dom/findDOMNodes.js' {
  declare module.exports: $Exports<'fela-dom/lib/dom/findDOMNodes'>;
}
declare module 'fela-dom/lib/dom/getDOMNode.js' {
  declare module.exports: $Exports<'fela-dom/lib/dom/getDOMNode'>;
}
declare module 'fela-dom/lib/dom/initDOMNode.js' {
  declare module.exports: $Exports<'fela-dom/lib/dom/initDOMNode'>;
}
declare module 'fela-dom/lib/dom/rehydration/rehydrateCache.js' {
  declare module.exports: $Exports<'fela-dom/lib/dom/rehydration/rehydrateCache'>;
}
declare module 'fela-dom/lib/dom/rehydration/rehydrateRules.js' {
  declare module.exports: $Exports<'fela-dom/lib/dom/rehydration/rehydrateRules'>;
}
declare module 'fela-dom/lib/dom/rehydration/rehydrateSupportRules.js' {
  declare module.exports: $Exports<'fela-dom/lib/dom/rehydration/rehydrateSupportRules'>;
}
declare module 'fela-dom/lib/dom/render.js' {
  declare module.exports: $Exports<'fela-dom/lib/dom/render'>;
}
declare module 'fela-dom/lib/index.js' {
  declare module.exports: $Exports<'fela-dom/lib/index'>;
}
declare module 'fela-dom/lib/server/renderToMarkup.js' {
  declare module.exports: $Exports<'fela-dom/lib/server/renderToMarkup'>;
}
declare module 'fela-dom/lib/server/renderToSheetList.js' {
  declare module.exports: $Exports<'fela-dom/lib/server/renderToSheetList'>;
}
