// flow-typed signature: f892188f4385b5110300e2e02755f807
// flow-typed version: <<STUB>>/fela-plugin-placeholder-prefixer_v^4.2.2/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fela-plugin-placeholder-prefixer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fela-plugin-placeholder-prefixer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fela-plugin-placeholder-prefixer/dist/fela-plugin-placeholder-prefixer' {
  declare module.exports: any;
}

declare module 'fela-plugin-placeholder-prefixer/dist/fela-plugin-placeholder-prefixer.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fela-plugin-placeholder-prefixer/dist/fela-plugin-placeholder-prefixer.js' {
  declare module.exports: $Exports<'fela-plugin-placeholder-prefixer/dist/fela-plugin-placeholder-prefixer'>;
}
declare module 'fela-plugin-placeholder-prefixer/dist/fela-plugin-placeholder-prefixer.min.js' {
  declare module.exports: $Exports<'fela-plugin-placeholder-prefixer/dist/fela-plugin-placeholder-prefixer.min'>;
}
declare module 'fela-plugin-placeholder-prefixer/index' {
  declare module.exports: $Exports<'fela-plugin-placeholder-prefixer'>;
}
declare module 'fela-plugin-placeholder-prefixer/index.js' {
  declare module.exports: $Exports<'fela-plugin-placeholder-prefixer'>;
}
