// flow-typed signature: f72b09136c9c7e19f5424ffc27f0b702
// flow-typed version: <<STUB>>/fela_v^3.0.8/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fela'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fela' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fela/dist/fela' {
  declare module.exports: any;
}

declare module 'fela/dist/fela.min' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/react/connect' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/react/createComponent' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/react/index' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/react/Provider' {
  declare module.exports: any;
}

declare module 'fela/lib/combineRules' {
  declare module.exports: any;
}

declare module 'fela/lib/createRenderer' {
  declare module.exports: any;
}

declare module 'fela/lib/enhance' {
  declare module.exports: any;
}

declare module 'fela/lib/enhancers/beautifier' {
  declare module.exports: any;
}

declare module 'fela/lib/enhancers/fontRenderer' {
  declare module.exports: any;
}

declare module 'fela/lib/enhancers/logger' {
  declare module.exports: any;
}

declare module 'fela/lib/enhancers/perf' {
  declare module.exports: any;
}

declare module 'fela/lib/index' {
  declare module.exports: any;
}

declare module 'fela/lib/native/createRenderer' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/customProperty' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/debugLayout' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/dynamicPrefixer' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/extend' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/fallbackValue' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/friendlyPseudoClass' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/logger' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/LVHA' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/placeholderPrefixer' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/prefixer' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/removeUndefined' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/unit' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/validator' {
  declare module.exports: any;
}

declare module 'fela/lib/presets/dev' {
  declare module.exports: any;
}

declare module 'fela/lib/presets/web' {
  declare module.exports: any;
}

declare module 'fela/lib/render' {
  declare module.exports: any;
}

declare module 'fela/lib/tools/StyleSheet' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/assign' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/cssifyKeyframe' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/cssifyObject' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/diffStyle' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/DOMInterface' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/generateContentHash' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/generatePropsReference' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/getFontFormat' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/processStyle' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/sortedStringify' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/warning' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fela/dist/fela.js' {
  declare module.exports: $Exports<'fela/dist/fela'>;
}
declare module 'fela/dist/fela.min.js' {
  declare module.exports: $Exports<'fela/dist/fela.min'>;
}
declare module 'fela/index' {
  declare module.exports: $Exports<'fela'>;
}
declare module 'fela/index.js' {
  declare module.exports: $Exports<'fela'>;
}
declare module 'fela/lib/bindings/react/connect.js' {
  declare module.exports: $Exports<'fela/lib/bindings/react/connect'>;
}
declare module 'fela/lib/bindings/react/createComponent.js' {
  declare module.exports: $Exports<'fela/lib/bindings/react/createComponent'>;
}
declare module 'fela/lib/bindings/react/index.js' {
  declare module.exports: $Exports<'fela/lib/bindings/react/index'>;
}
declare module 'fela/lib/bindings/react/Provider.js' {
  declare module.exports: $Exports<'fela/lib/bindings/react/Provider'>;
}
declare module 'fela/lib/combineRules.js' {
  declare module.exports: $Exports<'fela/lib/combineRules'>;
}
declare module 'fela/lib/createRenderer.js' {
  declare module.exports: $Exports<'fela/lib/createRenderer'>;
}
declare module 'fela/lib/enhance.js' {
  declare module.exports: $Exports<'fela/lib/enhance'>;
}
declare module 'fela/lib/enhancers/beautifier.js' {
  declare module.exports: $Exports<'fela/lib/enhancers/beautifier'>;
}
declare module 'fela/lib/enhancers/fontRenderer.js' {
  declare module.exports: $Exports<'fela/lib/enhancers/fontRenderer'>;
}
declare module 'fela/lib/enhancers/logger.js' {
  declare module.exports: $Exports<'fela/lib/enhancers/logger'>;
}
declare module 'fela/lib/enhancers/perf.js' {
  declare module.exports: $Exports<'fela/lib/enhancers/perf'>;
}
declare module 'fela/lib/index.js' {
  declare module.exports: $Exports<'fela/lib/index'>;
}
declare module 'fela/lib/native/createRenderer.js' {
  declare module.exports: $Exports<'fela/lib/native/createRenderer'>;
}
declare module 'fela/lib/plugins/customProperty.js' {
  declare module.exports: $Exports<'fela/lib/plugins/customProperty'>;
}
declare module 'fela/lib/plugins/debugLayout.js' {
  declare module.exports: $Exports<'fela/lib/plugins/debugLayout'>;
}
declare module 'fela/lib/plugins/dynamicPrefixer.js' {
  declare module.exports: $Exports<'fela/lib/plugins/dynamicPrefixer'>;
}
declare module 'fela/lib/plugins/extend.js' {
  declare module.exports: $Exports<'fela/lib/plugins/extend'>;
}
declare module 'fela/lib/plugins/fallbackValue.js' {
  declare module.exports: $Exports<'fela/lib/plugins/fallbackValue'>;
}
declare module 'fela/lib/plugins/friendlyPseudoClass.js' {
  declare module.exports: $Exports<'fela/lib/plugins/friendlyPseudoClass'>;
}
declare module 'fela/lib/plugins/logger.js' {
  declare module.exports: $Exports<'fela/lib/plugins/logger'>;
}
declare module 'fela/lib/plugins/LVHA.js' {
  declare module.exports: $Exports<'fela/lib/plugins/LVHA'>;
}
declare module 'fela/lib/plugins/placeholderPrefixer.js' {
  declare module.exports: $Exports<'fela/lib/plugins/placeholderPrefixer'>;
}
declare module 'fela/lib/plugins/prefixer.js' {
  declare module.exports: $Exports<'fela/lib/plugins/prefixer'>;
}
declare module 'fela/lib/plugins/removeUndefined.js' {
  declare module.exports: $Exports<'fela/lib/plugins/removeUndefined'>;
}
declare module 'fela/lib/plugins/unit.js' {
  declare module.exports: $Exports<'fela/lib/plugins/unit'>;
}
declare module 'fela/lib/plugins/validator.js' {
  declare module.exports: $Exports<'fela/lib/plugins/validator'>;
}
declare module 'fela/lib/presets/dev.js' {
  declare module.exports: $Exports<'fela/lib/presets/dev'>;
}
declare module 'fela/lib/presets/web.js' {
  declare module.exports: $Exports<'fela/lib/presets/web'>;
}
declare module 'fela/lib/render.js' {
  declare module.exports: $Exports<'fela/lib/render'>;
}
declare module 'fela/lib/tools/StyleSheet.js' {
  declare module.exports: $Exports<'fela/lib/tools/StyleSheet'>;
}
declare module 'fela/lib/utils/assign.js' {
  declare module.exports: $Exports<'fela/lib/utils/assign'>;
}
declare module 'fela/lib/utils/cssifyKeyframe.js' {
  declare module.exports: $Exports<'fela/lib/utils/cssifyKeyframe'>;
}
declare module 'fela/lib/utils/cssifyObject.js' {
  declare module.exports: $Exports<'fela/lib/utils/cssifyObject'>;
}
declare module 'fela/lib/utils/diffStyle.js' {
  declare module.exports: $Exports<'fela/lib/utils/diffStyle'>;
}
declare module 'fela/lib/utils/DOMInterface.js' {
  declare module.exports: $Exports<'fela/lib/utils/DOMInterface'>;
}
declare module 'fela/lib/utils/generateContentHash.js' {
  declare module.exports: $Exports<'fela/lib/utils/generateContentHash'>;
}
declare module 'fela/lib/utils/generatePropsReference.js' {
  declare module.exports: $Exports<'fela/lib/utils/generatePropsReference'>;
}
declare module 'fela/lib/utils/getFontFormat.js' {
  declare module.exports: $Exports<'fela/lib/utils/getFontFormat'>;
}
declare module 'fela/lib/utils/processStyle.js' {
  declare module.exports: $Exports<'fela/lib/utils/processStyle'>;
}
declare module 'fela/lib/utils/sortedStringify.js' {
  declare module.exports: $Exports<'fela/lib/utils/sortedStringify'>;
}
declare module 'fela/lib/utils/warning.js' {
  declare module.exports: $Exports<'fela/lib/utils/warning'>;
}
