// flow-typed signature: b65fd7b169ec43b63d0904097fdc1cb2
// flow-typed version: <<STUB>>/fela_v^5.0.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fela'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fela' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fela/es/bindings/connectFactory' {
  declare module.exports: any;
}

declare module 'fela/es/bindings/createComponentFactory' {
  declare module.exports: any;
}

declare module 'fela/es/bindings/generateDisplayName' {
  declare module.exports: any;
}

declare module 'fela/es/combineRules' {
  declare module.exports: any;
}

declare module 'fela/es/createRenderer' {
  declare module.exports: any;
}

declare module 'fela/es/enhance' {
  declare module.exports: any;
}

declare module 'fela/es/index' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/connectFactory' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/createComponentFactory' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/generateDisplayName' {
  declare module.exports: any;
}

declare module 'fela/lib/combineRules' {
  declare module.exports: any;
}

declare module 'fela/lib/createRenderer' {
  declare module.exports: any;
}

declare module 'fela/lib/enhance' {
  declare module.exports: any;
}

declare module 'fela/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fela/es/bindings/connectFactory.js' {
  declare module.exports: $Exports<'fela/es/bindings/connectFactory'>;
}
declare module 'fela/es/bindings/createComponentFactory.js' {
  declare module.exports: $Exports<'fela/es/bindings/createComponentFactory'>;
}
declare module 'fela/es/bindings/generateDisplayName.js' {
  declare module.exports: $Exports<'fela/es/bindings/generateDisplayName'>;
}
declare module 'fela/es/combineRules.js' {
  declare module.exports: $Exports<'fela/es/combineRules'>;
}
declare module 'fela/es/createRenderer.js' {
  declare module.exports: $Exports<'fela/es/createRenderer'>;
}
declare module 'fela/es/enhance.js' {
  declare module.exports: $Exports<'fela/es/enhance'>;
}
declare module 'fela/es/index.js' {
  declare module.exports: $Exports<'fela/es/index'>;
}
declare module 'fela/lib/bindings/connectFactory.js' {
  declare module.exports: $Exports<'fela/lib/bindings/connectFactory'>;
}
declare module 'fela/lib/bindings/createComponentFactory.js' {
  declare module.exports: $Exports<'fela/lib/bindings/createComponentFactory'>;
}
declare module 'fela/lib/bindings/generateDisplayName.js' {
  declare module.exports: $Exports<'fela/lib/bindings/generateDisplayName'>;
}
declare module 'fela/lib/combineRules.js' {
  declare module.exports: $Exports<'fela/lib/combineRules'>;
}
declare module 'fela/lib/createRenderer.js' {
  declare module.exports: $Exports<'fela/lib/createRenderer'>;
}
declare module 'fela/lib/enhance.js' {
  declare module.exports: $Exports<'fela/lib/enhance'>;
}
declare module 'fela/lib/index.js' {
  declare module.exports: $Exports<'fela/lib/index'>;
}
