// flow-typed signature: 4347626dc20ec7cc849f2d8df540f060
// flow-typed version: <<STUB>>/fela_v^4.3.2/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fela'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fela' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fela/dist/fela' {
  declare module.exports: any;
}

declare module 'fela/dist/fela.min' {
  declare module.exports: any;
}

declare module 'fela/lib/__tests__/combineRules-test' {
  declare module.exports: any;
}

declare module 'fela/lib/__tests__/createRenderer-test' {
  declare module.exports: any;
}

declare module 'fela/lib/__tests__/enhance-test' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/inferno/connect' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/inferno/createComponent' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/inferno/index' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/inferno/Provider' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/inferno/ThemeProvider' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/preact/connect' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/preact/createComponent' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/preact/index' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/preact/Provider' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/preact/ThemeProvider' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/react/__tests__/createComponent-test' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/react/connect' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/react/createComponent' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/react/index' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/react/Provider' {
  declare module.exports: any;
}

declare module 'fela/lib/bindings/react/ThemeProvider' {
  declare module.exports: any;
}

declare module 'fela/lib/combineRules' {
  declare module.exports: any;
}

declare module 'fela/lib/createRenderer' {
  declare module.exports: any;
}

declare module 'fela/lib/dom/__tests__/DOMInterface-test' {
  declare module.exports: any;
}

declare module 'fela/lib/dom/__tests__/mocks/DOMNode' {
  declare module.exports: any;
}

declare module 'fela/lib/dom/__tests__/render-test' {
  declare module.exports: any;
}

declare module 'fela/lib/dom/DOMInterface' {
  declare module.exports: any;
}

declare module 'fela/lib/dom/index' {
  declare module.exports: any;
}

declare module 'fela/lib/dom/render' {
  declare module.exports: any;
}

declare module 'fela/lib/enhance' {
  declare module.exports: any;
}

declare module 'fela/lib/enhancers/__tests__/monolithic-test' {
  declare module.exports: any;
}

declare module 'fela/lib/enhancers/beautifier' {
  declare module.exports: any;
}

declare module 'fela/lib/enhancers/debugLayout' {
  declare module.exports: any;
}

declare module 'fela/lib/enhancers/fontRenderer' {
  declare module.exports: any;
}

declare module 'fela/lib/enhancers/layoutDebugger' {
  declare module.exports: any;
}

declare module 'fela/lib/enhancers/logger' {
  declare module.exports: any;
}

declare module 'fela/lib/enhancers/monolithic' {
  declare module.exports: any;
}

declare module 'fela/lib/enhancers/perf' {
  declare module.exports: any;
}

declare module 'fela/lib/enhancers/statistics' {
  declare module.exports: any;
}

declare module 'fela/lib/index' {
  declare module.exports: any;
}

declare module 'fela/lib/native/createRenderer' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/__tests__/customProperty-test' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/__tests__/dynamicPrefixer-test' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/__tests__/extend-test' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/__tests__/fallbackValue-test' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/__tests__/friendlyPseudoClass-test' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/__tests__/LVHA-test' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/__tests__/namedMediaQuery-test' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/__tests__/placeholderPrefixer-test' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/__tests__/prefixer-test' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/__tests__/removeUndefined-test' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/__tests__/unit-test' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/customProperty' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/debugLayout' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/dynamicPrefixer' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/extend' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/fallbackValue' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/friendlyPseudoClass' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/isolation' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/logger' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/LVHA' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/namedMediaQuery' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/placeholderPrefixer' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/prefixer' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/removeUndefined' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/typeableSyntax' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/unit' {
  declare module.exports: any;
}

declare module 'fela/lib/plugins/validator' {
  declare module.exports: any;
}

declare module 'fela/lib/presets/dev' {
  declare module.exports: any;
}

declare module 'fela/lib/presets/web' {
  declare module.exports: any;
}

declare module 'fela/lib/tools/__tests__/mapValueToMediaQuery-test' {
  declare module.exports: any;
}

declare module 'fela/lib/tools/__tests__/StyleSheet-test' {
  declare module.exports: any;
}

declare module 'fela/lib/tools/index' {
  declare module.exports: any;
}

declare module 'fela/lib/tools/mapValueToMediaQuery' {
  declare module.exports: any;
}

declare module 'fela/lib/tools/StyleSheet' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/__tests__/applyMediaRulesInOrder-test' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/__tests__/checkFontFormat-test' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/__tests__/cssifyFontFace-test' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/__tests__/cssifyKeyframe-test' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/__tests__/cssifyMediaQueryRules-test' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/__tests__/cssifyStaticStyle-test' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/__tests__/generateAnimationName-test' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/__tests__/generateClassName-test' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/__tests__/generateCombinedMediaQuery-test' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/__tests__/generateCSSRule-test' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/__tests__/generateCSSSelector-test' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/__tests__/generateStaticReference-test' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/__tests__/isMediaQuery-test' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/__tests__/isNestedSelector-test' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/__tests__/minifyCSSString-test' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/__tests__/processStyleWithPlugins-test' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/__tests__/toCSSString-test' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/applyMediaRulesInOrder' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/arrayEach' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/arrayReduce' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/assign' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/assignStyles' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/checkFontFormat' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/cssifyFontFace' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/cssifyKeyframe' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/cssifyMediaQueryRules' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/cssifyObject' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/cssifyStaticStyle' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/extractPassThroughProps' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/generateAnimationName' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/generateClassName' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/generateCombinedMediaQuery' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/generateCSSDeclaration' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/generateCSSRule' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/generateCSSSelector' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/generateStaticReference' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/isAttributeSelector' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/isChildSelector' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/isMediaQuery' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/isNestedSelector' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/isObject' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/isPseudoSelector' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/isUndefinedValue' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/isValidHTMLElement' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/minifyCSSString' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/normalizeNestedProperty' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/objectReduce' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/processStyleWithPlugins' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/resolvePassThrough' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/styleTypes' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/toCSSString' {
  declare module.exports: any;
}

declare module 'fela/lib/utils/warning' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fela/dist/fela.js' {
  declare module.exports: $Exports<'fela/dist/fela'>;
}
declare module 'fela/dist/fela.min.js' {
  declare module.exports: $Exports<'fela/dist/fela.min'>;
}
declare module 'fela/index' {
  declare module.exports: $Exports<'fela'>;
}
declare module 'fela/index.js' {
  declare module.exports: $Exports<'fela'>;
}
declare module 'fela/lib/__tests__/combineRules-test.js' {
  declare module.exports: $Exports<'fela/lib/__tests__/combineRules-test'>;
}
declare module 'fela/lib/__tests__/createRenderer-test.js' {
  declare module.exports: $Exports<'fela/lib/__tests__/createRenderer-test'>;
}
declare module 'fela/lib/__tests__/enhance-test.js' {
  declare module.exports: $Exports<'fela/lib/__tests__/enhance-test'>;
}
declare module 'fela/lib/bindings/inferno/connect.js' {
  declare module.exports: $Exports<'fela/lib/bindings/inferno/connect'>;
}
declare module 'fela/lib/bindings/inferno/createComponent.js' {
  declare module.exports: $Exports<'fela/lib/bindings/inferno/createComponent'>;
}
declare module 'fela/lib/bindings/inferno/index.js' {
  declare module.exports: $Exports<'fela/lib/bindings/inferno/index'>;
}
declare module 'fela/lib/bindings/inferno/Provider.js' {
  declare module.exports: $Exports<'fela/lib/bindings/inferno/Provider'>;
}
declare module 'fela/lib/bindings/inferno/ThemeProvider.js' {
  declare module.exports: $Exports<'fela/lib/bindings/inferno/ThemeProvider'>;
}
declare module 'fela/lib/bindings/preact/connect.js' {
  declare module.exports: $Exports<'fela/lib/bindings/preact/connect'>;
}
declare module 'fela/lib/bindings/preact/createComponent.js' {
  declare module.exports: $Exports<'fela/lib/bindings/preact/createComponent'>;
}
declare module 'fela/lib/bindings/preact/index.js' {
  declare module.exports: $Exports<'fela/lib/bindings/preact/index'>;
}
declare module 'fela/lib/bindings/preact/Provider.js' {
  declare module.exports: $Exports<'fela/lib/bindings/preact/Provider'>;
}
declare module 'fela/lib/bindings/preact/ThemeProvider.js' {
  declare module.exports: $Exports<'fela/lib/bindings/preact/ThemeProvider'>;
}
declare module 'fela/lib/bindings/react/__tests__/createComponent-test.js' {
  declare module.exports: $Exports<'fela/lib/bindings/react/__tests__/createComponent-test'>;
}
declare module 'fela/lib/bindings/react/connect.js' {
  declare module.exports: $Exports<'fela/lib/bindings/react/connect'>;
}
declare module 'fela/lib/bindings/react/createComponent.js' {
  declare module.exports: $Exports<'fela/lib/bindings/react/createComponent'>;
}
declare module 'fela/lib/bindings/react/index.js' {
  declare module.exports: $Exports<'fela/lib/bindings/react/index'>;
}
declare module 'fela/lib/bindings/react/Provider.js' {
  declare module.exports: $Exports<'fela/lib/bindings/react/Provider'>;
}
declare module 'fela/lib/bindings/react/ThemeProvider.js' {
  declare module.exports: $Exports<'fela/lib/bindings/react/ThemeProvider'>;
}
declare module 'fela/lib/combineRules.js' {
  declare module.exports: $Exports<'fela/lib/combineRules'>;
}
declare module 'fela/lib/createRenderer.js' {
  declare module.exports: $Exports<'fela/lib/createRenderer'>;
}
declare module 'fela/lib/dom/__tests__/DOMInterface-test.js' {
  declare module.exports: $Exports<'fela/lib/dom/__tests__/DOMInterface-test'>;
}
declare module 'fela/lib/dom/__tests__/mocks/DOMNode.js' {
  declare module.exports: $Exports<'fela/lib/dom/__tests__/mocks/DOMNode'>;
}
declare module 'fela/lib/dom/__tests__/render-test.js' {
  declare module.exports: $Exports<'fela/lib/dom/__tests__/render-test'>;
}
declare module 'fela/lib/dom/DOMInterface.js' {
  declare module.exports: $Exports<'fela/lib/dom/DOMInterface'>;
}
declare module 'fela/lib/dom/index.js' {
  declare module.exports: $Exports<'fela/lib/dom/index'>;
}
declare module 'fela/lib/dom/render.js' {
  declare module.exports: $Exports<'fela/lib/dom/render'>;
}
declare module 'fela/lib/enhance.js' {
  declare module.exports: $Exports<'fela/lib/enhance'>;
}
declare module 'fela/lib/enhancers/__tests__/monolithic-test.js' {
  declare module.exports: $Exports<'fela/lib/enhancers/__tests__/monolithic-test'>;
}
declare module 'fela/lib/enhancers/beautifier.js' {
  declare module.exports: $Exports<'fela/lib/enhancers/beautifier'>;
}
declare module 'fela/lib/enhancers/debugLayout.js' {
  declare module.exports: $Exports<'fela/lib/enhancers/debugLayout'>;
}
declare module 'fela/lib/enhancers/fontRenderer.js' {
  declare module.exports: $Exports<'fela/lib/enhancers/fontRenderer'>;
}
declare module 'fela/lib/enhancers/layoutDebugger.js' {
  declare module.exports: $Exports<'fela/lib/enhancers/layoutDebugger'>;
}
declare module 'fela/lib/enhancers/logger.js' {
  declare module.exports: $Exports<'fela/lib/enhancers/logger'>;
}
declare module 'fela/lib/enhancers/monolithic.js' {
  declare module.exports: $Exports<'fela/lib/enhancers/monolithic'>;
}
declare module 'fela/lib/enhancers/perf.js' {
  declare module.exports: $Exports<'fela/lib/enhancers/perf'>;
}
declare module 'fela/lib/enhancers/statistics.js' {
  declare module.exports: $Exports<'fela/lib/enhancers/statistics'>;
}
declare module 'fela/lib/index.js' {
  declare module.exports: $Exports<'fela/lib/index'>;
}
declare module 'fela/lib/native/createRenderer.js' {
  declare module.exports: $Exports<'fela/lib/native/createRenderer'>;
}
declare module 'fela/lib/plugins/__tests__/customProperty-test.js' {
  declare module.exports: $Exports<'fela/lib/plugins/__tests__/customProperty-test'>;
}
declare module 'fela/lib/plugins/__tests__/dynamicPrefixer-test.js' {
  declare module.exports: $Exports<'fela/lib/plugins/__tests__/dynamicPrefixer-test'>;
}
declare module 'fela/lib/plugins/__tests__/extend-test.js' {
  declare module.exports: $Exports<'fela/lib/plugins/__tests__/extend-test'>;
}
declare module 'fela/lib/plugins/__tests__/fallbackValue-test.js' {
  declare module.exports: $Exports<'fela/lib/plugins/__tests__/fallbackValue-test'>;
}
declare module 'fela/lib/plugins/__tests__/friendlyPseudoClass-test.js' {
  declare module.exports: $Exports<'fela/lib/plugins/__tests__/friendlyPseudoClass-test'>;
}
declare module 'fela/lib/plugins/__tests__/LVHA-test.js' {
  declare module.exports: $Exports<'fela/lib/plugins/__tests__/LVHA-test'>;
}
declare module 'fela/lib/plugins/__tests__/namedMediaQuery-test.js' {
  declare module.exports: $Exports<'fela/lib/plugins/__tests__/namedMediaQuery-test'>;
}
declare module 'fela/lib/plugins/__tests__/placeholderPrefixer-test.js' {
  declare module.exports: $Exports<'fela/lib/plugins/__tests__/placeholderPrefixer-test'>;
}
declare module 'fela/lib/plugins/__tests__/prefixer-test.js' {
  declare module.exports: $Exports<'fela/lib/plugins/__tests__/prefixer-test'>;
}
declare module 'fela/lib/plugins/__tests__/removeUndefined-test.js' {
  declare module.exports: $Exports<'fela/lib/plugins/__tests__/removeUndefined-test'>;
}
declare module 'fela/lib/plugins/__tests__/unit-test.js' {
  declare module.exports: $Exports<'fela/lib/plugins/__tests__/unit-test'>;
}
declare module 'fela/lib/plugins/customProperty.js' {
  declare module.exports: $Exports<'fela/lib/plugins/customProperty'>;
}
declare module 'fela/lib/plugins/debugLayout.js' {
  declare module.exports: $Exports<'fela/lib/plugins/debugLayout'>;
}
declare module 'fela/lib/plugins/dynamicPrefixer.js' {
  declare module.exports: $Exports<'fela/lib/plugins/dynamicPrefixer'>;
}
declare module 'fela/lib/plugins/extend.js' {
  declare module.exports: $Exports<'fela/lib/plugins/extend'>;
}
declare module 'fela/lib/plugins/fallbackValue.js' {
  declare module.exports: $Exports<'fela/lib/plugins/fallbackValue'>;
}
declare module 'fela/lib/plugins/friendlyPseudoClass.js' {
  declare module.exports: $Exports<'fela/lib/plugins/friendlyPseudoClass'>;
}
declare module 'fela/lib/plugins/isolation.js' {
  declare module.exports: $Exports<'fela/lib/plugins/isolation'>;
}
declare module 'fela/lib/plugins/logger.js' {
  declare module.exports: $Exports<'fela/lib/plugins/logger'>;
}
declare module 'fela/lib/plugins/LVHA.js' {
  declare module.exports: $Exports<'fela/lib/plugins/LVHA'>;
}
declare module 'fela/lib/plugins/namedMediaQuery.js' {
  declare module.exports: $Exports<'fela/lib/plugins/namedMediaQuery'>;
}
declare module 'fela/lib/plugins/placeholderPrefixer.js' {
  declare module.exports: $Exports<'fela/lib/plugins/placeholderPrefixer'>;
}
declare module 'fela/lib/plugins/prefixer.js' {
  declare module.exports: $Exports<'fela/lib/plugins/prefixer'>;
}
declare module 'fela/lib/plugins/removeUndefined.js' {
  declare module.exports: $Exports<'fela/lib/plugins/removeUndefined'>;
}
declare module 'fela/lib/plugins/typeableSyntax.js' {
  declare module.exports: $Exports<'fela/lib/plugins/typeableSyntax'>;
}
declare module 'fela/lib/plugins/unit.js' {
  declare module.exports: $Exports<'fela/lib/plugins/unit'>;
}
declare module 'fela/lib/plugins/validator.js' {
  declare module.exports: $Exports<'fela/lib/plugins/validator'>;
}
declare module 'fela/lib/presets/dev.js' {
  declare module.exports: $Exports<'fela/lib/presets/dev'>;
}
declare module 'fela/lib/presets/web.js' {
  declare module.exports: $Exports<'fela/lib/presets/web'>;
}
declare module 'fela/lib/tools/__tests__/mapValueToMediaQuery-test.js' {
  declare module.exports: $Exports<'fela/lib/tools/__tests__/mapValueToMediaQuery-test'>;
}
declare module 'fela/lib/tools/__tests__/StyleSheet-test.js' {
  declare module.exports: $Exports<'fela/lib/tools/__tests__/StyleSheet-test'>;
}
declare module 'fela/lib/tools/index.js' {
  declare module.exports: $Exports<'fela/lib/tools/index'>;
}
declare module 'fela/lib/tools/mapValueToMediaQuery.js' {
  declare module.exports: $Exports<'fela/lib/tools/mapValueToMediaQuery'>;
}
declare module 'fela/lib/tools/StyleSheet.js' {
  declare module.exports: $Exports<'fela/lib/tools/StyleSheet'>;
}
declare module 'fela/lib/utils/__tests__/applyMediaRulesInOrder-test.js' {
  declare module.exports: $Exports<'fela/lib/utils/__tests__/applyMediaRulesInOrder-test'>;
}
declare module 'fela/lib/utils/__tests__/checkFontFormat-test.js' {
  declare module.exports: $Exports<'fela/lib/utils/__tests__/checkFontFormat-test'>;
}
declare module 'fela/lib/utils/__tests__/cssifyFontFace-test.js' {
  declare module.exports: $Exports<'fela/lib/utils/__tests__/cssifyFontFace-test'>;
}
declare module 'fela/lib/utils/__tests__/cssifyKeyframe-test.js' {
  declare module.exports: $Exports<'fela/lib/utils/__tests__/cssifyKeyframe-test'>;
}
declare module 'fela/lib/utils/__tests__/cssifyMediaQueryRules-test.js' {
  declare module.exports: $Exports<'fela/lib/utils/__tests__/cssifyMediaQueryRules-test'>;
}
declare module 'fela/lib/utils/__tests__/cssifyStaticStyle-test.js' {
  declare module.exports: $Exports<'fela/lib/utils/__tests__/cssifyStaticStyle-test'>;
}
declare module 'fela/lib/utils/__tests__/generateAnimationName-test.js' {
  declare module.exports: $Exports<'fela/lib/utils/__tests__/generateAnimationName-test'>;
}
declare module 'fela/lib/utils/__tests__/generateClassName-test.js' {
  declare module.exports: $Exports<'fela/lib/utils/__tests__/generateClassName-test'>;
}
declare module 'fela/lib/utils/__tests__/generateCombinedMediaQuery-test.js' {
  declare module.exports: $Exports<'fela/lib/utils/__tests__/generateCombinedMediaQuery-test'>;
}
declare module 'fela/lib/utils/__tests__/generateCSSRule-test.js' {
  declare module.exports: $Exports<'fela/lib/utils/__tests__/generateCSSRule-test'>;
}
declare module 'fela/lib/utils/__tests__/generateCSSSelector-test.js' {
  declare module.exports: $Exports<'fela/lib/utils/__tests__/generateCSSSelector-test'>;
}
declare module 'fela/lib/utils/__tests__/generateStaticReference-test.js' {
  declare module.exports: $Exports<'fela/lib/utils/__tests__/generateStaticReference-test'>;
}
declare module 'fela/lib/utils/__tests__/isMediaQuery-test.js' {
  declare module.exports: $Exports<'fela/lib/utils/__tests__/isMediaQuery-test'>;
}
declare module 'fela/lib/utils/__tests__/isNestedSelector-test.js' {
  declare module.exports: $Exports<'fela/lib/utils/__tests__/isNestedSelector-test'>;
}
declare module 'fela/lib/utils/__tests__/minifyCSSString-test.js' {
  declare module.exports: $Exports<'fela/lib/utils/__tests__/minifyCSSString-test'>;
}
declare module 'fela/lib/utils/__tests__/processStyleWithPlugins-test.js' {
  declare module.exports: $Exports<'fela/lib/utils/__tests__/processStyleWithPlugins-test'>;
}
declare module 'fela/lib/utils/__tests__/toCSSString-test.js' {
  declare module.exports: $Exports<'fela/lib/utils/__tests__/toCSSString-test'>;
}
declare module 'fela/lib/utils/applyMediaRulesInOrder.js' {
  declare module.exports: $Exports<'fela/lib/utils/applyMediaRulesInOrder'>;
}
declare module 'fela/lib/utils/arrayEach.js' {
  declare module.exports: $Exports<'fela/lib/utils/arrayEach'>;
}
declare module 'fela/lib/utils/arrayReduce.js' {
  declare module.exports: $Exports<'fela/lib/utils/arrayReduce'>;
}
declare module 'fela/lib/utils/assign.js' {
  declare module.exports: $Exports<'fela/lib/utils/assign'>;
}
declare module 'fela/lib/utils/assignStyles.js' {
  declare module.exports: $Exports<'fela/lib/utils/assignStyles'>;
}
declare module 'fela/lib/utils/checkFontFormat.js' {
  declare module.exports: $Exports<'fela/lib/utils/checkFontFormat'>;
}
declare module 'fela/lib/utils/cssifyFontFace.js' {
  declare module.exports: $Exports<'fela/lib/utils/cssifyFontFace'>;
}
declare module 'fela/lib/utils/cssifyKeyframe.js' {
  declare module.exports: $Exports<'fela/lib/utils/cssifyKeyframe'>;
}
declare module 'fela/lib/utils/cssifyMediaQueryRules.js' {
  declare module.exports: $Exports<'fela/lib/utils/cssifyMediaQueryRules'>;
}
declare module 'fela/lib/utils/cssifyObject.js' {
  declare module.exports: $Exports<'fela/lib/utils/cssifyObject'>;
}
declare module 'fela/lib/utils/cssifyStaticStyle.js' {
  declare module.exports: $Exports<'fela/lib/utils/cssifyStaticStyle'>;
}
declare module 'fela/lib/utils/extractPassThroughProps.js' {
  declare module.exports: $Exports<'fela/lib/utils/extractPassThroughProps'>;
}
declare module 'fela/lib/utils/generateAnimationName.js' {
  declare module.exports: $Exports<'fela/lib/utils/generateAnimationName'>;
}
declare module 'fela/lib/utils/generateClassName.js' {
  declare module.exports: $Exports<'fela/lib/utils/generateClassName'>;
}
declare module 'fela/lib/utils/generateCombinedMediaQuery.js' {
  declare module.exports: $Exports<'fela/lib/utils/generateCombinedMediaQuery'>;
}
declare module 'fela/lib/utils/generateCSSDeclaration.js' {
  declare module.exports: $Exports<'fela/lib/utils/generateCSSDeclaration'>;
}
declare module 'fela/lib/utils/generateCSSRule.js' {
  declare module.exports: $Exports<'fela/lib/utils/generateCSSRule'>;
}
declare module 'fela/lib/utils/generateCSSSelector.js' {
  declare module.exports: $Exports<'fela/lib/utils/generateCSSSelector'>;
}
declare module 'fela/lib/utils/generateStaticReference.js' {
  declare module.exports: $Exports<'fela/lib/utils/generateStaticReference'>;
}
declare module 'fela/lib/utils/isAttributeSelector.js' {
  declare module.exports: $Exports<'fela/lib/utils/isAttributeSelector'>;
}
declare module 'fela/lib/utils/isChildSelector.js' {
  declare module.exports: $Exports<'fela/lib/utils/isChildSelector'>;
}
declare module 'fela/lib/utils/isMediaQuery.js' {
  declare module.exports: $Exports<'fela/lib/utils/isMediaQuery'>;
}
declare module 'fela/lib/utils/isNestedSelector.js' {
  declare module.exports: $Exports<'fela/lib/utils/isNestedSelector'>;
}
declare module 'fela/lib/utils/isObject.js' {
  declare module.exports: $Exports<'fela/lib/utils/isObject'>;
}
declare module 'fela/lib/utils/isPseudoSelector.js' {
  declare module.exports: $Exports<'fela/lib/utils/isPseudoSelector'>;
}
declare module 'fela/lib/utils/isUndefinedValue.js' {
  declare module.exports: $Exports<'fela/lib/utils/isUndefinedValue'>;
}
declare module 'fela/lib/utils/isValidHTMLElement.js' {
  declare module.exports: $Exports<'fela/lib/utils/isValidHTMLElement'>;
}
declare module 'fela/lib/utils/minifyCSSString.js' {
  declare module.exports: $Exports<'fela/lib/utils/minifyCSSString'>;
}
declare module 'fela/lib/utils/normalizeNestedProperty.js' {
  declare module.exports: $Exports<'fela/lib/utils/normalizeNestedProperty'>;
}
declare module 'fela/lib/utils/objectReduce.js' {
  declare module.exports: $Exports<'fela/lib/utils/objectReduce'>;
}
declare module 'fela/lib/utils/processStyleWithPlugins.js' {
  declare module.exports: $Exports<'fela/lib/utils/processStyleWithPlugins'>;
}
declare module 'fela/lib/utils/resolvePassThrough.js' {
  declare module.exports: $Exports<'fela/lib/utils/resolvePassThrough'>;
}
declare module 'fela/lib/utils/styleTypes.js' {
  declare module.exports: $Exports<'fela/lib/utils/styleTypes'>;
}
declare module 'fela/lib/utils/toCSSString.js' {
  declare module.exports: $Exports<'fela/lib/utils/toCSSString'>;
}
declare module 'fela/lib/utils/warning.js' {
  declare module.exports: $Exports<'fela/lib/utils/warning'>;
}
