// flow-typed signature: 7c293ee142800023d1dbed977965073e
// flow-typed version: <<STUB>>/fela-plugin-logger_v^4.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fela-plugin-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fela-plugin-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fela-plugin-logger/dist/fela-plugin-logger' {
  declare module.exports: any;
}

declare module 'fela-plugin-logger/dist/fela-plugin-logger.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fela-plugin-logger/dist/fela-plugin-logger.js' {
  declare module.exports: $Exports<'fela-plugin-logger/dist/fela-plugin-logger'>;
}
declare module 'fela-plugin-logger/dist/fela-plugin-logger.min.js' {
  declare module.exports: $Exports<'fela-plugin-logger/dist/fela-plugin-logger.min'>;
}
declare module 'fela-plugin-logger/index' {
  declare module.exports: $Exports<'fela-plugin-logger'>;
}
declare module 'fela-plugin-logger/index.js' {
  declare module.exports: $Exports<'fela-plugin-logger'>;
}
