// flow-typed signature: a0d178e346554e93985fe4f2e537cff6
// flow-typed version: <<STUB>>/fela-preset-web_v^5.0.2/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fela-preset-web'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fela-preset-web' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fela-preset-web/es/index' {
  declare module.exports: any;
}

declare module 'fela-preset-web/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fela-preset-web/es/index.js' {
  declare module.exports: $Exports<'fela-preset-web/es/index'>;
}
declare module 'fela-preset-web/lib/index.js' {
  declare module.exports: $Exports<'fela-preset-web/lib/index'>;
}
