// flow-typed signature: 0861e36170bc299c29dbd507af11b426
// flow-typed version: <<STUB>>/fela-preset-web_v^4.3.2/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fela-preset-web'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fela-preset-web' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fela-preset-web/dist/fela-preset-web' {
  declare module.exports: any;
}

declare module 'fela-preset-web/dist/fela-preset-web.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fela-preset-web/dist/fela-preset-web.js' {
  declare module.exports: $Exports<'fela-preset-web/dist/fela-preset-web'>;
}
declare module 'fela-preset-web/dist/fela-preset-web.min.js' {
  declare module.exports: $Exports<'fela-preset-web/dist/fela-preset-web.min'>;
}
declare module 'fela-preset-web/index' {
  declare module.exports: $Exports<'fela-preset-web'>;
}
declare module 'fela-preset-web/index.js' {
  declare module.exports: $Exports<'fela-preset-web'>;
}
