// flow-typed signature: 116d84aab4823f319330901abf671dcd
// flow-typed version: <<STUB>>/focusable_v^2.1.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'focusable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'focusable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'focusable/index' {
  declare module.exports: $Exports<'focusable'>;
}
declare module 'focusable/index.js' {
  declare module.exports: $Exports<'focusable'>;
}
