// flow-typed signature: 1d5446427651e5915a17a6af132171da
// flow-typed version: <<STUB>>/found-scroll_v^0.1.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'found-scroll'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'found-scroll' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'found-scroll/lib/index' {
  declare module.exports: any;
}

declare module 'found-scroll/lib/ScrollManager' {
  declare module.exports: any;
}

// Filename aliases
declare module 'found-scroll/lib/index.js' {
  declare module.exports: $Exports<'found-scroll/lib/index'>;
}
declare module 'found-scroll/lib/ScrollManager.js' {
  declare module.exports: $Exports<'found-scroll/lib/ScrollManager'>;
}
