// flow-typed signature: 4f8c4ad9d7e282b1cb51b8c7c561a635
// flow-typed version: <<STUB>>/graphql-cli_v^1.0.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-cli/dist/bin' {
  declare module.exports: any;
}

declare module 'graphql-cli/dist/cmds/add-endpoint' {
  declare module.exports: any;
}

declare module 'graphql-cli/dist/cmds/diff' {
  declare module.exports: any;
}

declare module 'graphql-cli/dist/cmds/get-schema' {
  declare module.exports: any;
}

declare module 'graphql-cli/dist/cmds/index' {
  declare module.exports: any;
}

declare module 'graphql-cli/dist/cmds/init' {
  declare module.exports: any;
}

declare module 'graphql-cli/dist/cmds/lint' {
  declare module.exports: any;
}

declare module 'graphql-cli/dist/cmds/ping' {
  declare module.exports: any;
}

declare module 'graphql-cli/dist/cmds/playground' {
  declare module.exports: any;
}

declare module 'graphql-cli/dist/cmds/schema-status' {
  declare module.exports: any;
}

declare module 'graphql-cli/dist/index' {
  declare module.exports: any;
}

declare module 'graphql-cli/dist/types' {
  declare module.exports: any;
}

declare module 'graphql-cli/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-cli/dist/bin.js' {
  declare module.exports: $Exports<'graphql-cli/dist/bin'>;
}
declare module 'graphql-cli/dist/cmds/add-endpoint.js' {
  declare module.exports: $Exports<'graphql-cli/dist/cmds/add-endpoint'>;
}
declare module 'graphql-cli/dist/cmds/diff.js' {
  declare module.exports: $Exports<'graphql-cli/dist/cmds/diff'>;
}
declare module 'graphql-cli/dist/cmds/get-schema.js' {
  declare module.exports: $Exports<'graphql-cli/dist/cmds/get-schema'>;
}
declare module 'graphql-cli/dist/cmds/index.js' {
  declare module.exports: $Exports<'graphql-cli/dist/cmds/index'>;
}
declare module 'graphql-cli/dist/cmds/init.js' {
  declare module.exports: $Exports<'graphql-cli/dist/cmds/init'>;
}
declare module 'graphql-cli/dist/cmds/lint.js' {
  declare module.exports: $Exports<'graphql-cli/dist/cmds/lint'>;
}
declare module 'graphql-cli/dist/cmds/ping.js' {
  declare module.exports: $Exports<'graphql-cli/dist/cmds/ping'>;
}
declare module 'graphql-cli/dist/cmds/playground.js' {
  declare module.exports: $Exports<'graphql-cli/dist/cmds/playground'>;
}
declare module 'graphql-cli/dist/cmds/schema-status.js' {
  declare module.exports: $Exports<'graphql-cli/dist/cmds/schema-status'>;
}
declare module 'graphql-cli/dist/index.js' {
  declare module.exports: $Exports<'graphql-cli/dist/index'>;
}
declare module 'graphql-cli/dist/types.js' {
  declare module.exports: $Exports<'graphql-cli/dist/types'>;
}
declare module 'graphql-cli/dist/utils.js' {
  declare module.exports: $Exports<'graphql-cli/dist/utils'>;
}
