// flow-typed signature: 4ab36610a4804dfde9e4d74e1412ebdc
// flow-typed version: <<STUB>>/graphql-yoga_v^1.2.1/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-yoga'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-yoga' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-yoga/dist/src/index' {
  declare module.exports: any;
}

declare module 'graphql-yoga/dist/src/lambda' {
  declare module.exports: any;
}

declare module 'graphql-yoga/dist/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-yoga/dist/src/index.js' {
  declare module.exports: $Exports<'graphql-yoga/dist/src/index'>;
}
declare module 'graphql-yoga/dist/src/lambda.js' {
  declare module.exports: $Exports<'graphql-yoga/dist/src/lambda'>;
}
declare module 'graphql-yoga/dist/src/types.js' {
  declare module.exports: $Exports<'graphql-yoga/dist/src/types'>;
}
