// flow-typed signature: fdefb7a790fd52e76992387b0e5571ee
// flow-typed version: <<STUB>>/gravatar-api_v^1.4.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gravatar-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gravatar-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gravatar-api/index' {
  declare module.exports: $Exports<'gravatar-api'>;
}
declare module 'gravatar-api/index.js' {
  declare module.exports: $Exports<'gravatar-api'>;
}
