// flow-typed signature: 45c0cc6854d826dd7cf69b3a6946c43d
// flow-typed version: <<STUB>>/gulp-real-favicon_v^0.2.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-real-favicon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-real-favicon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-real-favicon/test/check_for_updates' {
  declare module.exports: any;
}

declare module 'gulp-real-favicon/test/generate_favicon' {
  declare module.exports: any;
}

declare module 'gulp-real-favicon/test/inject_favicon_markups' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-real-favicon/index' {
  declare module.exports: $Exports<'gulp-real-favicon'>;
}
declare module 'gulp-real-favicon/index.js' {
  declare module.exports: $Exports<'gulp-real-favicon'>;
}
declare module 'gulp-real-favicon/test/check_for_updates.js' {
  declare module.exports: $Exports<'gulp-real-favicon/test/check_for_updates'>;
}
declare module 'gulp-real-favicon/test/generate_favicon.js' {
  declare module.exports: $Exports<'gulp-real-favicon/test/generate_favicon'>;
}
declare module 'gulp-real-favicon/test/inject_favicon_markups.js' {
  declare module.exports: $Exports<'gulp-real-favicon/test/inject_favicon_markups'>;
}
