// flow-typed signature: 65542c34fe8401880a531c639e9ef364
// flow-typed version: <<STUB>>/gulp-bg_v^0.0.8/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-bg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-bg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-bg/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-bg/gulpfile.js' {
  declare module.exports: $Exports<'gulp-bg/gulpfile'>;
}
declare module 'gulp-bg/index' {
  declare module.exports: $Exports<'gulp-bg'>;
}
declare module 'gulp-bg/index.js' {
  declare module.exports: $Exports<'gulp-bg'>;
}
