// flow-typed signature: 549daefed270fa34609b874a61d4888d
// flow-typed version: <<STUB>>/intl-locales-supported_v^1.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'intl-locales-supported'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'intl-locales-supported' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'intl-locales-supported/test/unit/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'intl-locales-supported/index' {
  declare module.exports: $Exports<'intl-locales-supported'>;
}
declare module 'intl-locales-supported/index.js' {
  declare module.exports: $Exports<'intl-locales-supported'>;
}
declare module 'intl-locales-supported/test/unit/index.js' {
  declare module.exports: $Exports<'intl-locales-supported/test/unit/index'>;
}
