// flow-typed signature: b3e8a9943bce2e105d7b02d2a4ac0743
// flow-typed version: <<STUB>>/is-hotkey_v^0.1.4/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-hotkey'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-hotkey' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'is-hotkey/lib/index' {
  declare module.exports: any;
}

declare module 'is-hotkey/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'is-hotkey/lib/index.js' {
  declare module.exports: $Exports<'is-hotkey/lib/index'>;
}
declare module 'is-hotkey/src/index.js' {
  declare module.exports: $Exports<'is-hotkey/src/index'>;
}
