// flow-typed signature: 7982ff2eb7688d3bb1b9b321471b2674
// flow-typed version: <<STUB>>/lodash.throttle_v^4.1.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.throttle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.throttle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.throttle/index' {
  declare module.exports: $Exports<'lodash.throttle'>;
}
declare module 'lodash.throttle/index.js' {
  declare module.exports: $Exports<'lodash.throttle'>;
}
