// flow-typed signature: 2f1b471a50731f42600b41970b6cdf1b
// flow-typed version: <<STUB>>/make-error_v^1.0.4/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'make-error'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'make-error' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'make-error/index' {
  declare module.exports: $Exports<'make-error'>;
}
declare module 'make-error/index.js' {
  declare module.exports: $Exports<'make-error'>;
}
