// flow-typed signature: 19711e4eca02f0f330d5a195d15e28b7
// flow-typed version: <<STUB>>/next_v^6.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next/app' {
  declare module.exports: any;
}

declare module 'next/asset' {
  declare module.exports: any;
}

declare module 'next/babel' {
  declare module.exports: any;
}

declare module 'next/client' {
  declare module.exports: any;
}

declare module 'next/config' {
  declare module.exports: any;
}

declare module 'next/constants' {
  declare module.exports: any;
}

declare module 'next/dist/client/head-manager' {
  declare module.exports: any;
}

declare module 'next/dist/client/index' {
  declare module.exports: any;
}

declare module 'next/dist/client/next-dev' {
  declare module.exports: any;
}

declare module 'next/dist/client/next' {
  declare module.exports: any;
}

declare module 'next/dist/client/on-demand-entries-client' {
  declare module.exports: any;
}

declare module 'next/dist/client/source-map-support' {
  declare module.exports: any;
}

declare module 'next/dist/client/webpack-hot-middleware-client' {
  declare module.exports: any;
}

declare module 'next/dist/lib/app' {
  declare module.exports: any;
}

declare module 'next/dist/lib/asset' {
  declare module.exports: any;
}

declare module 'next/dist/lib/constants' {
  declare module.exports: any;
}

declare module 'next/dist/lib/dynamic' {
  declare module.exports: any;
}

declare module 'next/dist/lib/error-debug' {
  declare module.exports: any;
}

declare module 'next/dist/lib/error' {
  declare module.exports: any;
}

declare module 'next/dist/lib/EventEmitter' {
  declare module.exports: any;
}

declare module 'next/dist/lib/head' {
  declare module.exports: any;
}

declare module 'next/dist/lib/link' {
  declare module.exports: any;
}

declare module 'next/dist/lib/p-queue' {
  declare module.exports: any;
}

declare module 'next/dist/lib/page-loader' {
  declare module.exports: any;
}

declare module 'next/dist/lib/prefetch' {
  declare module.exports: any;
}

declare module 'next/dist/lib/router/index' {
  declare module.exports: any;
}

declare module 'next/dist/lib/router/router' {
  declare module.exports: any;
}

declare module 'next/dist/lib/router/with-router' {
  declare module.exports: any;
}

declare module 'next/dist/lib/runtime-config' {
  declare module.exports: any;
}

declare module 'next/dist/lib/shallow-equals' {
  declare module.exports: any;
}

declare module 'next/dist/lib/side-effect' {
  declare module.exports: any;
}

declare module 'next/dist/lib/utils' {
  declare module.exports: any;
}

declare module 'next/dist/pages/_app' {
  declare module.exports: any;
}

declare module 'next/dist/pages/_document' {
  declare module.exports: any;
}

declare module 'next/dist/pages/_error' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/babel/plugins/handle-import' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/babel/preset' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/index' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/loaders/emit-file-loader' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/loaders/hot-self-accept-loader' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/plugins/build-manifest-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/plugins/dynamic-chunks-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/plugins/nextjs-ssr-import' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/plugins/pages-manifest-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/plugins/pages-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/plugins/unlink-file-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/webpack' {
  declare module.exports: any;
}

declare module 'next/dist/server/build/webpack/utils' {
  declare module.exports: any;
}

declare module 'next/dist/server/config' {
  declare module.exports: any;
}

declare module 'next/dist/server/document' {
  declare module.exports: any;
}

declare module 'next/dist/server/export' {
  declare module.exports: any;
}

declare module 'next/dist/server/hot-reloader' {
  declare module.exports: any;
}

declare module 'next/dist/server/index' {
  declare module.exports: any;
}

declare module 'next/dist/server/lib/is-async-supported' {
  declare module.exports: any;
}

declare module 'next/dist/server/lib/path-match' {
  declare module.exports: any;
}

declare module 'next/dist/server/lib/promisify' {
  declare module.exports: any;
}

declare module 'next/dist/server/lib/source-map-support' {
  declare module.exports: any;
}

declare module 'next/dist/server/next' {
  declare module.exports: any;
}

declare module 'next/dist/server/on-demand-entry-handler' {
  declare module.exports: any;
}

declare module 'next/dist/server/render' {
  declare module.exports: any;
}

declare module 'next/dist/server/require' {
  declare module.exports: any;
}

declare module 'next/dist/server/router' {
  declare module.exports: any;
}

declare module 'next/dist/server/utils' {
  declare module.exports: any;
}

declare module 'next/document' {
  declare module.exports: any;
}

declare module 'next/dynamic' {
  declare module.exports: any;
}

declare module 'next/error' {
  declare module.exports: any;
}

declare module 'next/head' {
  declare module.exports: any;
}

declare module 'next/link' {
  declare module.exports: any;
}

declare module 'next/prefetch' {
  declare module.exports: any;
}

declare module 'next/router' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next/app.js' {
  declare module.exports: $Exports<'next/app'>;
}
declare module 'next/asset.js' {
  declare module.exports: $Exports<'next/asset'>;
}
declare module 'next/babel.js' {
  declare module.exports: $Exports<'next/babel'>;
}
declare module 'next/client.js' {
  declare module.exports: $Exports<'next/client'>;
}
declare module 'next/config.js' {
  declare module.exports: $Exports<'next/config'>;
}
declare module 'next/constants.js' {
  declare module.exports: $Exports<'next/constants'>;
}
declare module 'next/dist/client/head-manager.js' {
  declare module.exports: $Exports<'next/dist/client/head-manager'>;
}
declare module 'next/dist/client/index.js' {
  declare module.exports: $Exports<'next/dist/client/index'>;
}
declare module 'next/dist/client/next-dev.js' {
  declare module.exports: $Exports<'next/dist/client/next-dev'>;
}
declare module 'next/dist/client/next.js' {
  declare module.exports: $Exports<'next/dist/client/next'>;
}
declare module 'next/dist/client/on-demand-entries-client.js' {
  declare module.exports: $Exports<'next/dist/client/on-demand-entries-client'>;
}
declare module 'next/dist/client/source-map-support.js' {
  declare module.exports: $Exports<'next/dist/client/source-map-support'>;
}
declare module 'next/dist/client/webpack-hot-middleware-client.js' {
  declare module.exports: $Exports<'next/dist/client/webpack-hot-middleware-client'>;
}
declare module 'next/dist/lib/app.js' {
  declare module.exports: $Exports<'next/dist/lib/app'>;
}
declare module 'next/dist/lib/asset.js' {
  declare module.exports: $Exports<'next/dist/lib/asset'>;
}
declare module 'next/dist/lib/constants.js' {
  declare module.exports: $Exports<'next/dist/lib/constants'>;
}
declare module 'next/dist/lib/dynamic.js' {
  declare module.exports: $Exports<'next/dist/lib/dynamic'>;
}
declare module 'next/dist/lib/error-debug.js' {
  declare module.exports: $Exports<'next/dist/lib/error-debug'>;
}
declare module 'next/dist/lib/error.js' {
  declare module.exports: $Exports<'next/dist/lib/error'>;
}
declare module 'next/dist/lib/EventEmitter.js' {
  declare module.exports: $Exports<'next/dist/lib/EventEmitter'>;
}
declare module 'next/dist/lib/head.js' {
  declare module.exports: $Exports<'next/dist/lib/head'>;
}
declare module 'next/dist/lib/link.js' {
  declare module.exports: $Exports<'next/dist/lib/link'>;
}
declare module 'next/dist/lib/p-queue.js' {
  declare module.exports: $Exports<'next/dist/lib/p-queue'>;
}
declare module 'next/dist/lib/page-loader.js' {
  declare module.exports: $Exports<'next/dist/lib/page-loader'>;
}
declare module 'next/dist/lib/prefetch.js' {
  declare module.exports: $Exports<'next/dist/lib/prefetch'>;
}
declare module 'next/dist/lib/router/index.js' {
  declare module.exports: $Exports<'next/dist/lib/router/index'>;
}
declare module 'next/dist/lib/router/router.js' {
  declare module.exports: $Exports<'next/dist/lib/router/router'>;
}
declare module 'next/dist/lib/router/with-router.js' {
  declare module.exports: $Exports<'next/dist/lib/router/with-router'>;
}
declare module 'next/dist/lib/runtime-config.js' {
  declare module.exports: $Exports<'next/dist/lib/runtime-config'>;
}
declare module 'next/dist/lib/shallow-equals.js' {
  declare module.exports: $Exports<'next/dist/lib/shallow-equals'>;
}
declare module 'next/dist/lib/side-effect.js' {
  declare module.exports: $Exports<'next/dist/lib/side-effect'>;
}
declare module 'next/dist/lib/utils.js' {
  declare module.exports: $Exports<'next/dist/lib/utils'>;
}
declare module 'next/dist/pages/_app.js' {
  declare module.exports: $Exports<'next/dist/pages/_app'>;
}
declare module 'next/dist/pages/_document.js' {
  declare module.exports: $Exports<'next/dist/pages/_document'>;
}
declare module 'next/dist/pages/_error.js' {
  declare module.exports: $Exports<'next/dist/pages/_error'>;
}
declare module 'next/dist/server/build/babel/plugins/handle-import.js' {
  declare module.exports: $Exports<'next/dist/server/build/babel/plugins/handle-import'>;
}
declare module 'next/dist/server/build/babel/preset.js' {
  declare module.exports: $Exports<'next/dist/server/build/babel/preset'>;
}
declare module 'next/dist/server/build/index.js' {
  declare module.exports: $Exports<'next/dist/server/build/index'>;
}
declare module 'next/dist/server/build/loaders/emit-file-loader.js' {
  declare module.exports: $Exports<'next/dist/server/build/loaders/emit-file-loader'>;
}
declare module 'next/dist/server/build/loaders/hot-self-accept-loader.js' {
  declare module.exports: $Exports<'next/dist/server/build/loaders/hot-self-accept-loader'>;
}
declare module 'next/dist/server/build/plugins/build-manifest-plugin.js' {
  declare module.exports: $Exports<'next/dist/server/build/plugins/build-manifest-plugin'>;
}
declare module 'next/dist/server/build/plugins/dynamic-chunks-plugin.js' {
  declare module.exports: $Exports<'next/dist/server/build/plugins/dynamic-chunks-plugin'>;
}
declare module 'next/dist/server/build/plugins/nextjs-ssr-import.js' {
  declare module.exports: $Exports<'next/dist/server/build/plugins/nextjs-ssr-import'>;
}
declare module 'next/dist/server/build/plugins/pages-manifest-plugin.js' {
  declare module.exports: $Exports<'next/dist/server/build/plugins/pages-manifest-plugin'>;
}
declare module 'next/dist/server/build/plugins/pages-plugin.js' {
  declare module.exports: $Exports<'next/dist/server/build/plugins/pages-plugin'>;
}
declare module 'next/dist/server/build/plugins/unlink-file-plugin.js' {
  declare module.exports: $Exports<'next/dist/server/build/plugins/unlink-file-plugin'>;
}
declare module 'next/dist/server/build/webpack.js' {
  declare module.exports: $Exports<'next/dist/server/build/webpack'>;
}
declare module 'next/dist/server/build/webpack/utils.js' {
  declare module.exports: $Exports<'next/dist/server/build/webpack/utils'>;
}
declare module 'next/dist/server/config.js' {
  declare module.exports: $Exports<'next/dist/server/config'>;
}
declare module 'next/dist/server/document.js' {
  declare module.exports: $Exports<'next/dist/server/document'>;
}
declare module 'next/dist/server/export.js' {
  declare module.exports: $Exports<'next/dist/server/export'>;
}
declare module 'next/dist/server/hot-reloader.js' {
  declare module.exports: $Exports<'next/dist/server/hot-reloader'>;
}
declare module 'next/dist/server/index.js' {
  declare module.exports: $Exports<'next/dist/server/index'>;
}
declare module 'next/dist/server/lib/is-async-supported.js' {
  declare module.exports: $Exports<'next/dist/server/lib/is-async-supported'>;
}
declare module 'next/dist/server/lib/path-match.js' {
  declare module.exports: $Exports<'next/dist/server/lib/path-match'>;
}
declare module 'next/dist/server/lib/promisify.js' {
  declare module.exports: $Exports<'next/dist/server/lib/promisify'>;
}
declare module 'next/dist/server/lib/source-map-support.js' {
  declare module.exports: $Exports<'next/dist/server/lib/source-map-support'>;
}
declare module 'next/dist/server/next.js' {
  declare module.exports: $Exports<'next/dist/server/next'>;
}
declare module 'next/dist/server/on-demand-entry-handler.js' {
  declare module.exports: $Exports<'next/dist/server/on-demand-entry-handler'>;
}
declare module 'next/dist/server/render.js' {
  declare module.exports: $Exports<'next/dist/server/render'>;
}
declare module 'next/dist/server/require.js' {
  declare module.exports: $Exports<'next/dist/server/require'>;
}
declare module 'next/dist/server/router.js' {
  declare module.exports: $Exports<'next/dist/server/router'>;
}
declare module 'next/dist/server/utils.js' {
  declare module.exports: $Exports<'next/dist/server/utils'>;
}
declare module 'next/document.js' {
  declare module.exports: $Exports<'next/document'>;
}
declare module 'next/dynamic.js' {
  declare module.exports: $Exports<'next/dynamic'>;
}
declare module 'next/error.js' {
  declare module.exports: $Exports<'next/error'>;
}
declare module 'next/head.js' {
  declare module.exports: $Exports<'next/head'>;
}
declare module 'next/link.js' {
  declare module.exports: $Exports<'next/link'>;
}
declare module 'next/prefetch.js' {
  declare module.exports: $Exports<'next/prefetch'>;
}
declare module 'next/router.js' {
  declare module.exports: $Exports<'next/router'>;
}
