// flow-typed signature: c838be31b8a0f5e1e7441b3d0699f24a
// flow-typed version: <<STUB>>/nprogress_v^0.2.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nprogress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nprogress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nprogress/nprogress' {
  declare module.exports: any;
}

declare module 'nprogress/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nprogress/nprogress.js' {
  declare module.exports: $Exports<'nprogress/nprogress'>;
}
declare module 'nprogress/test/test.js' {
  declare module.exports: $Exports<'nprogress/test/test'>;
}
