// flow-typed signature: 62fd482707d600ee3df68a18c32d37d6
// flow-typed version: <<STUB>>/path-match_v^1.2.4/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'path-match'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'path-match' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'path-match/index' {
  declare module.exports: $Exports<'path-match'>;
}
declare module 'path-match/index.js' {
  declare module.exports: $Exports<'path-match'>;
}
