// flow-typed signature: 15f6b0129a5914ed9ffa4a332ac80aa1
// flow-typed version: <<STUB>>/prisma-binding_v^1.5.12/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prisma-binding'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prisma-binding' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prisma-binding/dist/src/Handler' {
  declare module.exports: any;
}

declare module 'prisma-binding/dist/src/index' {
  declare module.exports: any;
}

declare module 'prisma-binding/dist/src/info' {
  declare module.exports: any;
}

declare module 'prisma-binding/dist/src/link' {
  declare module.exports: any;
}

declare module 'prisma-binding/dist/src/Prisma' {
  declare module.exports: any;
}

declare module 'prisma-binding/dist/src/SharedLink' {
  declare module.exports: any;
}

declare module 'prisma-binding/dist/src/types' {
  declare module.exports: any;
}

declare module 'prisma-binding/dist/tests/Prisma.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prisma-binding/dist/src/Handler.js' {
  declare module.exports: $Exports<'prisma-binding/dist/src/Handler'>;
}
declare module 'prisma-binding/dist/src/index.js' {
  declare module.exports: $Exports<'prisma-binding/dist/src/index'>;
}
declare module 'prisma-binding/dist/src/info.js' {
  declare module.exports: $Exports<'prisma-binding/dist/src/info'>;
}
declare module 'prisma-binding/dist/src/link.js' {
  declare module.exports: $Exports<'prisma-binding/dist/src/link'>;
}
declare module 'prisma-binding/dist/src/Prisma.js' {
  declare module.exports: $Exports<'prisma-binding/dist/src/Prisma'>;
}
declare module 'prisma-binding/dist/src/SharedLink.js' {
  declare module.exports: $Exports<'prisma-binding/dist/src/SharedLink'>;
}
declare module 'prisma-binding/dist/src/types.js' {
  declare module.exports: $Exports<'prisma-binding/dist/src/types'>;
}
declare module 'prisma-binding/dist/tests/Prisma.test.js' {
  declare module.exports: $Exports<'prisma-binding/dist/tests/Prisma.test'>;
}
