// flow-typed signature: 50f941d559c6ff40ede056611b1fbd0f
// flow-typed version: <<STUB>>/prisma_v^1.2.4/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prisma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prisma' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prisma/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prisma/dist/index.js' {
  declare module.exports: $Exports<'prisma/dist/index'>;
}
