// flow-typed signature: 5034214e002e1cd2f5faf706c1ba5d93
// flow-typed version: <<STUB>>/react-native-side-menu_v^0.20.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-side-menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-side-menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-side-menu/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-side-menu/index' {
  declare module.exports: $Exports<'react-native-side-menu'>;
}
declare module 'react-native-side-menu/index.js' {
  declare module.exports: $Exports<'react-native-side-menu'>;
}
declare module 'react-native-side-menu/styles.js' {
  declare module.exports: $Exports<'react-native-side-menu/styles'>;
}
