// flow-typed signature: 99c3f1e6a52d4093aa148af53732a75d
// flow-typed version: <<STUB>>/react-fela_v^4.3.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-fela'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-fela' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-fela/dist/react-fela' {
  declare module.exports: any;
}

declare module 'react-fela/dist/react-fela.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-fela/dist/react-fela.js' {
  declare module.exports: $Exports<'react-fela/dist/react-fela'>;
}
declare module 'react-fela/dist/react-fela.min.js' {
  declare module.exports: $Exports<'react-fela/dist/react-fela.min'>;
}
declare module 'react-fela/index' {
  declare module.exports: $Exports<'react-fela'>;
}
declare module 'react-fela/index.js' {
  declare module.exports: $Exports<'react-fela'>;
}
