// flow-typed signature: 59cc022b2a5d39e701b9344d3447c249
// flow-typed version: <<STUB>>/react-native-i18n_v^0.1.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-i18n'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-i18n' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-i18n/vendor/i18n' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-i18n/index' {
  declare module.exports: $Exports<'react-native-i18n'>;
}
declare module 'react-native-i18n/index.js' {
  declare module.exports: $Exports<'react-native-i18n'>;
}
declare module 'react-native-i18n/vendor/i18n.js' {
  declare module.exports: $Exports<'react-native-i18n/vendor/i18n'>;
}
