// flow-typed signature: 3bc39de29247cf591d2b38f8fd4922a7
// flow-typed version: <<STUB>>/react-native-fbsdk_v^0.5.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-fbsdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-fbsdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-fbsdk/ios_setup' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/FBAccessToken' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/FBAppEventsLogger' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/FBAppInviteDialog' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/FBGameRequestDialog' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/FBGraphRequest' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/FBGraphRequestManager' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/FBLikeView' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/FBLoginButton' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/FBLoginManager' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/FBMessageDialog' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/FBSendButton' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/FBShareApi' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/FBShareButton' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/FBShareDialog' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/index' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/models/FBAppGroupCreationContent' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/models/FBAppInviteContent' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/models/FBGameRequestContent' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/models/FBObjectIdAndType' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/models/FBShareContent' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/models/FBShareLinkContent' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/models/FBShareOpenGraphAction' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/models/FBShareOpenGraphContent' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/models/FBShareOpenGraphObject' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/models/FBShareOpenGraphValueContainer' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/models/FBSharePhoto' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/models/FBSharePhotoContent' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/models/FBShareVideo' {
  declare module.exports: any;
}

declare module 'react-native-fbsdk/js/models/FBShareVideoContent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-fbsdk/ios_setup.js' {
  declare module.exports: $Exports<'react-native-fbsdk/ios_setup'>;
}
declare module 'react-native-fbsdk/js/FBAccessToken.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/FBAccessToken'>;
}
declare module 'react-native-fbsdk/js/FBAppEventsLogger.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/FBAppEventsLogger'>;
}
declare module 'react-native-fbsdk/js/FBAppInviteDialog.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/FBAppInviteDialog'>;
}
declare module 'react-native-fbsdk/js/FBGameRequestDialog.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/FBGameRequestDialog'>;
}
declare module 'react-native-fbsdk/js/FBGraphRequest.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/FBGraphRequest'>;
}
declare module 'react-native-fbsdk/js/FBGraphRequestManager.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/FBGraphRequestManager'>;
}
declare module 'react-native-fbsdk/js/FBLikeView.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/FBLikeView'>;
}
declare module 'react-native-fbsdk/js/FBLoginButton.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/FBLoginButton'>;
}
declare module 'react-native-fbsdk/js/FBLoginManager.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/FBLoginManager'>;
}
declare module 'react-native-fbsdk/js/FBMessageDialog.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/FBMessageDialog'>;
}
declare module 'react-native-fbsdk/js/FBSendButton.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/FBSendButton'>;
}
declare module 'react-native-fbsdk/js/FBShareApi.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/FBShareApi'>;
}
declare module 'react-native-fbsdk/js/FBShareButton.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/FBShareButton'>;
}
declare module 'react-native-fbsdk/js/FBShareDialog.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/FBShareDialog'>;
}
declare module 'react-native-fbsdk/js/index.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/index'>;
}
declare module 'react-native-fbsdk/js/models/FBAppGroupCreationContent.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/models/FBAppGroupCreationContent'>;
}
declare module 'react-native-fbsdk/js/models/FBAppInviteContent.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/models/FBAppInviteContent'>;
}
declare module 'react-native-fbsdk/js/models/FBGameRequestContent.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/models/FBGameRequestContent'>;
}
declare module 'react-native-fbsdk/js/models/FBObjectIdAndType.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/models/FBObjectIdAndType'>;
}
declare module 'react-native-fbsdk/js/models/FBShareContent.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/models/FBShareContent'>;
}
declare module 'react-native-fbsdk/js/models/FBShareLinkContent.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/models/FBShareLinkContent'>;
}
declare module 'react-native-fbsdk/js/models/FBShareOpenGraphAction.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/models/FBShareOpenGraphAction'>;
}
declare module 'react-native-fbsdk/js/models/FBShareOpenGraphContent.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/models/FBShareOpenGraphContent'>;
}
declare module 'react-native-fbsdk/js/models/FBShareOpenGraphObject.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/models/FBShareOpenGraphObject'>;
}
declare module 'react-native-fbsdk/js/models/FBShareOpenGraphValueContainer.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/models/FBShareOpenGraphValueContainer'>;
}
declare module 'react-native-fbsdk/js/models/FBSharePhoto.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/models/FBSharePhoto'>;
}
declare module 'react-native-fbsdk/js/models/FBSharePhotoContent.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/models/FBSharePhotoContent'>;
}
declare module 'react-native-fbsdk/js/models/FBShareVideo.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/models/FBShareVideo'>;
}
declare module 'react-native-fbsdk/js/models/FBShareVideoContent.js' {
  declare module.exports: $Exports<'react-native-fbsdk/js/models/FBShareVideoContent'>;
}
