// flow-typed signature: 6d4fddbb8f01200c9ef8a528e5dbd526
// flow-typed version: <<STUB>>/react-apollo_v^1.0.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-apollo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-apollo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-apollo/dist/index' {
  declare module.exports: any;
}

declare module 'react-apollo/dist/index.min' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/ApolloProvider' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/browser' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/graphql' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/index' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/parser' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/server' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/test-utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-apollo/dist/index.js' {
  declare module.exports: $Exports<'react-apollo/dist/index'>;
}
declare module 'react-apollo/dist/index.min.js' {
  declare module.exports: $Exports<'react-apollo/dist/index.min'>;
}
declare module 'react-apollo/lib/ApolloProvider.js' {
  declare module.exports: $Exports<'react-apollo/lib/ApolloProvider'>;
}
declare module 'react-apollo/lib/browser.js' {
  declare module.exports: $Exports<'react-apollo/lib/browser'>;
}
declare module 'react-apollo/lib/graphql.js' {
  declare module.exports: $Exports<'react-apollo/lib/graphql'>;
}
declare module 'react-apollo/lib/index.js' {
  declare module.exports: $Exports<'react-apollo/lib/index'>;
}
declare module 'react-apollo/lib/parser.js' {
  declare module.exports: $Exports<'react-apollo/lib/parser'>;
}
declare module 'react-apollo/lib/server.js' {
  declare module.exports: $Exports<'react-apollo/lib/server'>;
}
declare module 'react-apollo/lib/shallowEqual.js' {
  declare module.exports: $Exports<'react-apollo/lib/shallowEqual'>;
}
declare module 'react-apollo/lib/test-utils.js' {
  declare module.exports: $Exports<'react-apollo/lib/test-utils'>;
}
