// flow-typed signature: 2157673e1edb172ada05af3f555d99bc
// flow-typed version: <<STUB>>/react-fela_v^4.0.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-fela'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-fela' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-fela/dist/react-fela' {
  declare module.exports: any;
}

declare module 'react-fela/dist/react-fela.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-fela/dist/react-fela.js' {
  declare module.exports: $Exports<'react-fela/dist/react-fela'>;
}
declare module 'react-fela/dist/react-fela.min.js' {
  declare module.exports: $Exports<'react-fela/dist/react-fela.min'>;
}
declare module 'react-fela/index' {
  declare module.exports: $Exports<'react-fela'>;
}
declare module 'react-fela/index.js' {
  declare module.exports: $Exports<'react-fela'>;
}
