// flow-typed signature: 4599c001967ce2b75c685e0670ea6737
// flow-typed version: <<STUB>>/react-native-uuid_v^1.4.8/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-uuid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-uuid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-uuid/benchmark/benchmark' {
  declare module.exports: any;
}

declare module 'react-native-uuid/test/compare_v1' {
  declare module.exports: any;
}

declare module 'react-native-uuid/test/test' {
  declare module.exports: any;
}

declare module 'react-native-uuid/uuid' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-uuid/benchmark/benchmark.js' {
  declare module.exports: $Exports<'react-native-uuid/benchmark/benchmark'>;
}
declare module 'react-native-uuid/test/compare_v1.js' {
  declare module.exports: $Exports<'react-native-uuid/test/compare_v1'>;
}
declare module 'react-native-uuid/test/test.js' {
  declare module.exports: $Exports<'react-native-uuid/test/test'>;
}
declare module 'react-native-uuid/uuid.js' {
  declare module.exports: $Exports<'react-native-uuid/uuid'>;
}
