// flow-typed signature: de44ddceab0d92b47841e70075dc9e6c
// flow-typed version: <<STUB>>/rebass_v^0.3.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rebass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rebass' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rebass/dist/Arrow' {
  declare module.exports: any;
}

declare module 'rebass/dist/Avatar' {
  declare module.exports: any;
}

declare module 'rebass/dist/Badge' {
  declare module.exports: any;
}

declare module 'rebass/dist/Banner' {
  declare module.exports: any;
}

declare module 'rebass/dist/Base' {
  declare module.exports: any;
}

declare module 'rebass/dist/Block' {
  declare module.exports: any;
}

declare module 'rebass/dist/Blockquote' {
  declare module.exports: any;
}

declare module 'rebass/dist/Breadcrumbs' {
  declare module.exports: any;
}

declare module 'rebass/dist/Button' {
  declare module.exports: any;
}

declare module 'rebass/dist/ButtonCircle' {
  declare module.exports: any;
}

declare module 'rebass/dist/ButtonOutline' {
  declare module.exports: any;
}

declare module 'rebass/dist/Card' {
  declare module.exports: any;
}

declare module 'rebass/dist/CardImage' {
  declare module.exports: any;
}

declare module 'rebass/dist/Checkbox' {
  declare module.exports: any;
}

declare module 'rebass/dist/Close' {
  declare module.exports: any;
}

declare module 'rebass/dist/config' {
  declare module.exports: any;
}

declare module 'rebass/dist/Container' {
  declare module.exports: any;
}

declare module 'rebass/dist/Divider' {
  declare module.exports: any;
}

declare module 'rebass/dist/Donut' {
  declare module.exports: any;
}

declare module 'rebass/dist/DotIndicator' {
  declare module.exports: any;
}

declare module 'rebass/dist/Drawer' {
  declare module.exports: any;
}

declare module 'rebass/dist/Dropdown' {
  declare module.exports: any;
}

declare module 'rebass/dist/DropdownMenu' {
  declare module.exports: any;
}

declare module 'rebass/dist/Embed' {
  declare module.exports: any;
}

declare module 'rebass/dist/Fixed' {
  declare module.exports: any;
}

declare module 'rebass/dist/Footer' {
  declare module.exports: any;
}

declare module 'rebass/dist/Heading' {
  declare module.exports: any;
}

declare module 'rebass/dist/HeadingLink' {
  declare module.exports: any;
}

declare module 'rebass/dist/index' {
  declare module.exports: any;
}

declare module 'rebass/dist/InlineForm' {
  declare module.exports: any;
}

declare module 'rebass/dist/Input' {
  declare module.exports: any;
}

declare module 'rebass/dist/Label' {
  declare module.exports: any;
}

declare module 'rebass/dist/LinkBlock' {
  declare module.exports: any;
}

declare module 'rebass/dist/Media' {
  declare module.exports: any;
}

declare module 'rebass/dist/Menu' {
  declare module.exports: any;
}

declare module 'rebass/dist/Message' {
  declare module.exports: any;
}

declare module 'rebass/dist/NavItem' {
  declare module.exports: any;
}

declare module 'rebass/dist/Overlay' {
  declare module.exports: any;
}

declare module 'rebass/dist/PageHeader' {
  declare module.exports: any;
}

declare module 'rebass/dist/Panel' {
  declare module.exports: any;
}

declare module 'rebass/dist/PanelFooter' {
  declare module.exports: any;
}

declare module 'rebass/dist/PanelHeader' {
  declare module.exports: any;
}

declare module 'rebass/dist/Pre' {
  declare module.exports: any;
}

declare module 'rebass/dist/Progress' {
  declare module.exports: any;
}

declare module 'rebass/dist/Radio' {
  declare module.exports: any;
}

declare module 'rebass/dist/Rating' {
  declare module.exports: any;
}

declare module 'rebass/dist/Section' {
  declare module.exports: any;
}

declare module 'rebass/dist/SectionHeader' {
  declare module.exports: any;
}

declare module 'rebass/dist/Select' {
  declare module.exports: any;
}

declare module 'rebass/dist/SequenceMap' {
  declare module.exports: any;
}

declare module 'rebass/dist/SequenceMapStep' {
  declare module.exports: any;
}

declare module 'rebass/dist/Slider' {
  declare module.exports: any;
}

declare module 'rebass/dist/Space' {
  declare module.exports: any;
}

declare module 'rebass/dist/Stat' {
  declare module.exports: any;
}

declare module 'rebass/dist/Switch' {
  declare module.exports: any;
}

declare module 'rebass/dist/Table' {
  declare module.exports: any;
}

declare module 'rebass/dist/Text' {
  declare module.exports: any;
}

declare module 'rebass/dist/Textarea' {
  declare module.exports: any;
}

declare module 'rebass/dist/Toolbar' {
  declare module.exports: any;
}

declare module 'rebass/dist/Tooltip' {
  declare module.exports: any;
}

declare module 'rebass/dist/util/color-style' {
  declare module.exports: any;
}

declare module 'rebass/dist/util/margins' {
  declare module.exports: any;
}

declare module 'rebass/dist/util/padding' {
  declare module.exports: any;
}

declare module 'rebass/dist/util/radii' {
  declare module.exports: any;
}

declare module 'rebass/dist/withRebass' {
  declare module.exports: any;
}

declare module 'rebass/src/Arrow' {
  declare module.exports: any;
}

declare module 'rebass/src/Avatar' {
  declare module.exports: any;
}

declare module 'rebass/src/Badge' {
  declare module.exports: any;
}

declare module 'rebass/src/Banner' {
  declare module.exports: any;
}

declare module 'rebass/src/Base' {
  declare module.exports: any;
}

declare module 'rebass/src/Block' {
  declare module.exports: any;
}

declare module 'rebass/src/Blockquote' {
  declare module.exports: any;
}

declare module 'rebass/src/Breadcrumbs' {
  declare module.exports: any;
}

declare module 'rebass/src/Button' {
  declare module.exports: any;
}

declare module 'rebass/src/ButtonCircle' {
  declare module.exports: any;
}

declare module 'rebass/src/ButtonOutline' {
  declare module.exports: any;
}

declare module 'rebass/src/Card' {
  declare module.exports: any;
}

declare module 'rebass/src/CardImage' {
  declare module.exports: any;
}

declare module 'rebass/src/Checkbox' {
  declare module.exports: any;
}

declare module 'rebass/src/Close' {
  declare module.exports: any;
}

declare module 'rebass/src/config' {
  declare module.exports: any;
}

declare module 'rebass/src/Container' {
  declare module.exports: any;
}

declare module 'rebass/src/Divider' {
  declare module.exports: any;
}

declare module 'rebass/src/Donut' {
  declare module.exports: any;
}

declare module 'rebass/src/DotIndicator' {
  declare module.exports: any;
}

declare module 'rebass/src/Drawer' {
  declare module.exports: any;
}

declare module 'rebass/src/Dropdown' {
  declare module.exports: any;
}

declare module 'rebass/src/DropdownMenu' {
  declare module.exports: any;
}

declare module 'rebass/src/Embed' {
  declare module.exports: any;
}

declare module 'rebass/src/Fixed' {
  declare module.exports: any;
}

declare module 'rebass/src/Footer' {
  declare module.exports: any;
}

declare module 'rebass/src/Heading' {
  declare module.exports: any;
}

declare module 'rebass/src/HeadingLink' {
  declare module.exports: any;
}

declare module 'rebass/src/index' {
  declare module.exports: any;
}

declare module 'rebass/src/InlineForm' {
  declare module.exports: any;
}

declare module 'rebass/src/Input' {
  declare module.exports: any;
}

declare module 'rebass/src/Label' {
  declare module.exports: any;
}

declare module 'rebass/src/LinkBlock' {
  declare module.exports: any;
}

declare module 'rebass/src/Media' {
  declare module.exports: any;
}

declare module 'rebass/src/Menu' {
  declare module.exports: any;
}

declare module 'rebass/src/Message' {
  declare module.exports: any;
}

declare module 'rebass/src/NavItem' {
  declare module.exports: any;
}

declare module 'rebass/src/Overlay' {
  declare module.exports: any;
}

declare module 'rebass/src/PageHeader' {
  declare module.exports: any;
}

declare module 'rebass/src/Panel' {
  declare module.exports: any;
}

declare module 'rebass/src/PanelFooter' {
  declare module.exports: any;
}

declare module 'rebass/src/PanelHeader' {
  declare module.exports: any;
}

declare module 'rebass/src/Pre' {
  declare module.exports: any;
}

declare module 'rebass/src/Progress' {
  declare module.exports: any;
}

declare module 'rebass/src/Radio' {
  declare module.exports: any;
}

declare module 'rebass/src/Rating' {
  declare module.exports: any;
}

declare module 'rebass/src/Section' {
  declare module.exports: any;
}

declare module 'rebass/src/SectionHeader' {
  declare module.exports: any;
}

declare module 'rebass/src/Select' {
  declare module.exports: any;
}

declare module 'rebass/src/SequenceMap' {
  declare module.exports: any;
}

declare module 'rebass/src/SequenceMapStep' {
  declare module.exports: any;
}

declare module 'rebass/src/Slider' {
  declare module.exports: any;
}

declare module 'rebass/src/Space' {
  declare module.exports: any;
}

declare module 'rebass/src/Stat' {
  declare module.exports: any;
}

declare module 'rebass/src/Switch' {
  declare module.exports: any;
}

declare module 'rebass/src/Table' {
  declare module.exports: any;
}

declare module 'rebass/src/Text' {
  declare module.exports: any;
}

declare module 'rebass/src/Textarea' {
  declare module.exports: any;
}

declare module 'rebass/src/Toolbar' {
  declare module.exports: any;
}

declare module 'rebass/src/Tooltip' {
  declare module.exports: any;
}

declare module 'rebass/src/util/color-style' {
  declare module.exports: any;
}

declare module 'rebass/src/util/margins' {
  declare module.exports: any;
}

declare module 'rebass/src/util/padding' {
  declare module.exports: any;
}

declare module 'rebass/src/util/radii' {
  declare module.exports: any;
}

declare module 'rebass/test/Arrow.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Avatar.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Badge.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Banner.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Base.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Block.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Blockquote.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Breadcrumbs.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Button.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/ButtonCircle.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/ButtonOutline.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Card.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/CardImage.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Checkbox.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Close.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/color-style.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/config.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Container.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Divider.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Donut.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/DotIndicator.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Drawer.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Dropdown.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/DropdownMenu' {
  declare module.exports: any;
}

declare module 'rebass/test/Embed.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Fixed.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Footer.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Heading.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/HeadingLink' {
  declare module.exports: any;
}

declare module 'rebass/test/InlineForm.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Input.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Label.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/LinkBlock.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/margins.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Media.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Menu.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Message.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/NavItem.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Overlay.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/padding.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/PageHeader.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Panel.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/PanelFooter.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/PanelHeader.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Pre.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Progress.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/radii.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Radio.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Rating.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Section.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/SectionHeader.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Select.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/SequenceMap.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Slider.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Space.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Stat.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Switch.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Table.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Text.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Textarea.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Toolbar.spec' {
  declare module.exports: any;
}

declare module 'rebass/test/Tooltip.spec' {
  declare module.exports: any;
}

declare module 'rebass/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rebass/dist/Arrow.js' {
  declare module.exports: $Exports<'rebass/dist/Arrow'>;
}
declare module 'rebass/dist/Avatar.js' {
  declare module.exports: $Exports<'rebass/dist/Avatar'>;
}
declare module 'rebass/dist/Badge.js' {
  declare module.exports: $Exports<'rebass/dist/Badge'>;
}
declare module 'rebass/dist/Banner.js' {
  declare module.exports: $Exports<'rebass/dist/Banner'>;
}
declare module 'rebass/dist/Base.js' {
  declare module.exports: $Exports<'rebass/dist/Base'>;
}
declare module 'rebass/dist/Block.js' {
  declare module.exports: $Exports<'rebass/dist/Block'>;
}
declare module 'rebass/dist/Blockquote.js' {
  declare module.exports: $Exports<'rebass/dist/Blockquote'>;
}
declare module 'rebass/dist/Breadcrumbs.js' {
  declare module.exports: $Exports<'rebass/dist/Breadcrumbs'>;
}
declare module 'rebass/dist/Button.js' {
  declare module.exports: $Exports<'rebass/dist/Button'>;
}
declare module 'rebass/dist/ButtonCircle.js' {
  declare module.exports: $Exports<'rebass/dist/ButtonCircle'>;
}
declare module 'rebass/dist/ButtonOutline.js' {
  declare module.exports: $Exports<'rebass/dist/ButtonOutline'>;
}
declare module 'rebass/dist/Card.js' {
  declare module.exports: $Exports<'rebass/dist/Card'>;
}
declare module 'rebass/dist/CardImage.js' {
  declare module.exports: $Exports<'rebass/dist/CardImage'>;
}
declare module 'rebass/dist/Checkbox.js' {
  declare module.exports: $Exports<'rebass/dist/Checkbox'>;
}
declare module 'rebass/dist/Close.js' {
  declare module.exports: $Exports<'rebass/dist/Close'>;
}
declare module 'rebass/dist/config.js' {
  declare module.exports: $Exports<'rebass/dist/config'>;
}
declare module 'rebass/dist/Container.js' {
  declare module.exports: $Exports<'rebass/dist/Container'>;
}
declare module 'rebass/dist/Divider.js' {
  declare module.exports: $Exports<'rebass/dist/Divider'>;
}
declare module 'rebass/dist/Donut.js' {
  declare module.exports: $Exports<'rebass/dist/Donut'>;
}
declare module 'rebass/dist/DotIndicator.js' {
  declare module.exports: $Exports<'rebass/dist/DotIndicator'>;
}
declare module 'rebass/dist/Drawer.js' {
  declare module.exports: $Exports<'rebass/dist/Drawer'>;
}
declare module 'rebass/dist/Dropdown.js' {
  declare module.exports: $Exports<'rebass/dist/Dropdown'>;
}
declare module 'rebass/dist/DropdownMenu.js' {
  declare module.exports: $Exports<'rebass/dist/DropdownMenu'>;
}
declare module 'rebass/dist/Embed.js' {
  declare module.exports: $Exports<'rebass/dist/Embed'>;
}
declare module 'rebass/dist/Fixed.js' {
  declare module.exports: $Exports<'rebass/dist/Fixed'>;
}
declare module 'rebass/dist/Footer.js' {
  declare module.exports: $Exports<'rebass/dist/Footer'>;
}
declare module 'rebass/dist/Heading.js' {
  declare module.exports: $Exports<'rebass/dist/Heading'>;
}
declare module 'rebass/dist/HeadingLink.js' {
  declare module.exports: $Exports<'rebass/dist/HeadingLink'>;
}
declare module 'rebass/dist/index.js' {
  declare module.exports: $Exports<'rebass/dist/index'>;
}
declare module 'rebass/dist/InlineForm.js' {
  declare module.exports: $Exports<'rebass/dist/InlineForm'>;
}
declare module 'rebass/dist/Input.js' {
  declare module.exports: $Exports<'rebass/dist/Input'>;
}
declare module 'rebass/dist/Label.js' {
  declare module.exports: $Exports<'rebass/dist/Label'>;
}
declare module 'rebass/dist/LinkBlock.js' {
  declare module.exports: $Exports<'rebass/dist/LinkBlock'>;
}
declare module 'rebass/dist/Media.js' {
  declare module.exports: $Exports<'rebass/dist/Media'>;
}
declare module 'rebass/dist/Menu.js' {
  declare module.exports: $Exports<'rebass/dist/Menu'>;
}
declare module 'rebass/dist/Message.js' {
  declare module.exports: $Exports<'rebass/dist/Message'>;
}
declare module 'rebass/dist/NavItem.js' {
  declare module.exports: $Exports<'rebass/dist/NavItem'>;
}
declare module 'rebass/dist/Overlay.js' {
  declare module.exports: $Exports<'rebass/dist/Overlay'>;
}
declare module 'rebass/dist/PageHeader.js' {
  declare module.exports: $Exports<'rebass/dist/PageHeader'>;
}
declare module 'rebass/dist/Panel.js' {
  declare module.exports: $Exports<'rebass/dist/Panel'>;
}
declare module 'rebass/dist/PanelFooter.js' {
  declare module.exports: $Exports<'rebass/dist/PanelFooter'>;
}
declare module 'rebass/dist/PanelHeader.js' {
  declare module.exports: $Exports<'rebass/dist/PanelHeader'>;
}
declare module 'rebass/dist/Pre.js' {
  declare module.exports: $Exports<'rebass/dist/Pre'>;
}
declare module 'rebass/dist/Progress.js' {
  declare module.exports: $Exports<'rebass/dist/Progress'>;
}
declare module 'rebass/dist/Radio.js' {
  declare module.exports: $Exports<'rebass/dist/Radio'>;
}
declare module 'rebass/dist/Rating.js' {
  declare module.exports: $Exports<'rebass/dist/Rating'>;
}
declare module 'rebass/dist/Section.js' {
  declare module.exports: $Exports<'rebass/dist/Section'>;
}
declare module 'rebass/dist/SectionHeader.js' {
  declare module.exports: $Exports<'rebass/dist/SectionHeader'>;
}
declare module 'rebass/dist/Select.js' {
  declare module.exports: $Exports<'rebass/dist/Select'>;
}
declare module 'rebass/dist/SequenceMap.js' {
  declare module.exports: $Exports<'rebass/dist/SequenceMap'>;
}
declare module 'rebass/dist/SequenceMapStep.js' {
  declare module.exports: $Exports<'rebass/dist/SequenceMapStep'>;
}
declare module 'rebass/dist/Slider.js' {
  declare module.exports: $Exports<'rebass/dist/Slider'>;
}
declare module 'rebass/dist/Space.js' {
  declare module.exports: $Exports<'rebass/dist/Space'>;
}
declare module 'rebass/dist/Stat.js' {
  declare module.exports: $Exports<'rebass/dist/Stat'>;
}
declare module 'rebass/dist/Switch.js' {
  declare module.exports: $Exports<'rebass/dist/Switch'>;
}
declare module 'rebass/dist/Table.js' {
  declare module.exports: $Exports<'rebass/dist/Table'>;
}
declare module 'rebass/dist/Text.js' {
  declare module.exports: $Exports<'rebass/dist/Text'>;
}
declare module 'rebass/dist/Textarea.js' {
  declare module.exports: $Exports<'rebass/dist/Textarea'>;
}
declare module 'rebass/dist/Toolbar.js' {
  declare module.exports: $Exports<'rebass/dist/Toolbar'>;
}
declare module 'rebass/dist/Tooltip.js' {
  declare module.exports: $Exports<'rebass/dist/Tooltip'>;
}
declare module 'rebass/dist/util/color-style.js' {
  declare module.exports: $Exports<'rebass/dist/util/color-style'>;
}
declare module 'rebass/dist/util/margins.js' {
  declare module.exports: $Exports<'rebass/dist/util/margins'>;
}
declare module 'rebass/dist/util/padding.js' {
  declare module.exports: $Exports<'rebass/dist/util/padding'>;
}
declare module 'rebass/dist/util/radii.js' {
  declare module.exports: $Exports<'rebass/dist/util/radii'>;
}
declare module 'rebass/dist/withRebass.js' {
  declare module.exports: $Exports<'rebass/dist/withRebass'>;
}
declare module 'rebass/src/Arrow.js' {
  declare module.exports: $Exports<'rebass/src/Arrow'>;
}
declare module 'rebass/src/Avatar.js' {
  declare module.exports: $Exports<'rebass/src/Avatar'>;
}
declare module 'rebass/src/Badge.js' {
  declare module.exports: $Exports<'rebass/src/Badge'>;
}
declare module 'rebass/src/Banner.js' {
  declare module.exports: $Exports<'rebass/src/Banner'>;
}
declare module 'rebass/src/Base.js' {
  declare module.exports: $Exports<'rebass/src/Base'>;
}
declare module 'rebass/src/Block.js' {
  declare module.exports: $Exports<'rebass/src/Block'>;
}
declare module 'rebass/src/Blockquote.js' {
  declare module.exports: $Exports<'rebass/src/Blockquote'>;
}
declare module 'rebass/src/Breadcrumbs.js' {
  declare module.exports: $Exports<'rebass/src/Breadcrumbs'>;
}
declare module 'rebass/src/Button.js' {
  declare module.exports: $Exports<'rebass/src/Button'>;
}
declare module 'rebass/src/ButtonCircle.js' {
  declare module.exports: $Exports<'rebass/src/ButtonCircle'>;
}
declare module 'rebass/src/ButtonOutline.js' {
  declare module.exports: $Exports<'rebass/src/ButtonOutline'>;
}
declare module 'rebass/src/Card.js' {
  declare module.exports: $Exports<'rebass/src/Card'>;
}
declare module 'rebass/src/CardImage.js' {
  declare module.exports: $Exports<'rebass/src/CardImage'>;
}
declare module 'rebass/src/Checkbox.js' {
  declare module.exports: $Exports<'rebass/src/Checkbox'>;
}
declare module 'rebass/src/Close.js' {
  declare module.exports: $Exports<'rebass/src/Close'>;
}
declare module 'rebass/src/config.js' {
  declare module.exports: $Exports<'rebass/src/config'>;
}
declare module 'rebass/src/Container.js' {
  declare module.exports: $Exports<'rebass/src/Container'>;
}
declare module 'rebass/src/Divider.js' {
  declare module.exports: $Exports<'rebass/src/Divider'>;
}
declare module 'rebass/src/Donut.js' {
  declare module.exports: $Exports<'rebass/src/Donut'>;
}
declare module 'rebass/src/DotIndicator.js' {
  declare module.exports: $Exports<'rebass/src/DotIndicator'>;
}
declare module 'rebass/src/Drawer.js' {
  declare module.exports: $Exports<'rebass/src/Drawer'>;
}
declare module 'rebass/src/Dropdown.js' {
  declare module.exports: $Exports<'rebass/src/Dropdown'>;
}
declare module 'rebass/src/DropdownMenu.js' {
  declare module.exports: $Exports<'rebass/src/DropdownMenu'>;
}
declare module 'rebass/src/Embed.js' {
  declare module.exports: $Exports<'rebass/src/Embed'>;
}
declare module 'rebass/src/Fixed.js' {
  declare module.exports: $Exports<'rebass/src/Fixed'>;
}
declare module 'rebass/src/Footer.js' {
  declare module.exports: $Exports<'rebass/src/Footer'>;
}
declare module 'rebass/src/Heading.js' {
  declare module.exports: $Exports<'rebass/src/Heading'>;
}
declare module 'rebass/src/HeadingLink.js' {
  declare module.exports: $Exports<'rebass/src/HeadingLink'>;
}
declare module 'rebass/src/index.js' {
  declare module.exports: $Exports<'rebass/src/index'>;
}
declare module 'rebass/src/InlineForm.js' {
  declare module.exports: $Exports<'rebass/src/InlineForm'>;
}
declare module 'rebass/src/Input.js' {
  declare module.exports: $Exports<'rebass/src/Input'>;
}
declare module 'rebass/src/Label.js' {
  declare module.exports: $Exports<'rebass/src/Label'>;
}
declare module 'rebass/src/LinkBlock.js' {
  declare module.exports: $Exports<'rebass/src/LinkBlock'>;
}
declare module 'rebass/src/Media.js' {
  declare module.exports: $Exports<'rebass/src/Media'>;
}
declare module 'rebass/src/Menu.js' {
  declare module.exports: $Exports<'rebass/src/Menu'>;
}
declare module 'rebass/src/Message.js' {
  declare module.exports: $Exports<'rebass/src/Message'>;
}
declare module 'rebass/src/NavItem.js' {
  declare module.exports: $Exports<'rebass/src/NavItem'>;
}
declare module 'rebass/src/Overlay.js' {
  declare module.exports: $Exports<'rebass/src/Overlay'>;
}
declare module 'rebass/src/PageHeader.js' {
  declare module.exports: $Exports<'rebass/src/PageHeader'>;
}
declare module 'rebass/src/Panel.js' {
  declare module.exports: $Exports<'rebass/src/Panel'>;
}
declare module 'rebass/src/PanelFooter.js' {
  declare module.exports: $Exports<'rebass/src/PanelFooter'>;
}
declare module 'rebass/src/PanelHeader.js' {
  declare module.exports: $Exports<'rebass/src/PanelHeader'>;
}
declare module 'rebass/src/Pre.js' {
  declare module.exports: $Exports<'rebass/src/Pre'>;
}
declare module 'rebass/src/Progress.js' {
  declare module.exports: $Exports<'rebass/src/Progress'>;
}
declare module 'rebass/src/Radio.js' {
  declare module.exports: $Exports<'rebass/src/Radio'>;
}
declare module 'rebass/src/Rating.js' {
  declare module.exports: $Exports<'rebass/src/Rating'>;
}
declare module 'rebass/src/Section.js' {
  declare module.exports: $Exports<'rebass/src/Section'>;
}
declare module 'rebass/src/SectionHeader.js' {
  declare module.exports: $Exports<'rebass/src/SectionHeader'>;
}
declare module 'rebass/src/Select.js' {
  declare module.exports: $Exports<'rebass/src/Select'>;
}
declare module 'rebass/src/SequenceMap.js' {
  declare module.exports: $Exports<'rebass/src/SequenceMap'>;
}
declare module 'rebass/src/SequenceMapStep.js' {
  declare module.exports: $Exports<'rebass/src/SequenceMapStep'>;
}
declare module 'rebass/src/Slider.js' {
  declare module.exports: $Exports<'rebass/src/Slider'>;
}
declare module 'rebass/src/Space.js' {
  declare module.exports: $Exports<'rebass/src/Space'>;
}
declare module 'rebass/src/Stat.js' {
  declare module.exports: $Exports<'rebass/src/Stat'>;
}
declare module 'rebass/src/Switch.js' {
  declare module.exports: $Exports<'rebass/src/Switch'>;
}
declare module 'rebass/src/Table.js' {
  declare module.exports: $Exports<'rebass/src/Table'>;
}
declare module 'rebass/src/Text.js' {
  declare module.exports: $Exports<'rebass/src/Text'>;
}
declare module 'rebass/src/Textarea.js' {
  declare module.exports: $Exports<'rebass/src/Textarea'>;
}
declare module 'rebass/src/Toolbar.js' {
  declare module.exports: $Exports<'rebass/src/Toolbar'>;
}
declare module 'rebass/src/Tooltip.js' {
  declare module.exports: $Exports<'rebass/src/Tooltip'>;
}
declare module 'rebass/src/util/color-style.js' {
  declare module.exports: $Exports<'rebass/src/util/color-style'>;
}
declare module 'rebass/src/util/margins.js' {
  declare module.exports: $Exports<'rebass/src/util/margins'>;
}
declare module 'rebass/src/util/padding.js' {
  declare module.exports: $Exports<'rebass/src/util/padding'>;
}
declare module 'rebass/src/util/radii.js' {
  declare module.exports: $Exports<'rebass/src/util/radii'>;
}
declare module 'rebass/test/Arrow.spec.js' {
  declare module.exports: $Exports<'rebass/test/Arrow.spec'>;
}
declare module 'rebass/test/Avatar.spec.js' {
  declare module.exports: $Exports<'rebass/test/Avatar.spec'>;
}
declare module 'rebass/test/Badge.spec.js' {
  declare module.exports: $Exports<'rebass/test/Badge.spec'>;
}
declare module 'rebass/test/Banner.spec.js' {
  declare module.exports: $Exports<'rebass/test/Banner.spec'>;
}
declare module 'rebass/test/Base.spec.js' {
  declare module.exports: $Exports<'rebass/test/Base.spec'>;
}
declare module 'rebass/test/Block.spec.js' {
  declare module.exports: $Exports<'rebass/test/Block.spec'>;
}
declare module 'rebass/test/Blockquote.spec.js' {
  declare module.exports: $Exports<'rebass/test/Blockquote.spec'>;
}
declare module 'rebass/test/Breadcrumbs.spec.js' {
  declare module.exports: $Exports<'rebass/test/Breadcrumbs.spec'>;
}
declare module 'rebass/test/Button.spec.js' {
  declare module.exports: $Exports<'rebass/test/Button.spec'>;
}
declare module 'rebass/test/ButtonCircle.spec.js' {
  declare module.exports: $Exports<'rebass/test/ButtonCircle.spec'>;
}
declare module 'rebass/test/ButtonOutline.spec.js' {
  declare module.exports: $Exports<'rebass/test/ButtonOutline.spec'>;
}
declare module 'rebass/test/Card.spec.js' {
  declare module.exports: $Exports<'rebass/test/Card.spec'>;
}
declare module 'rebass/test/CardImage.spec.js' {
  declare module.exports: $Exports<'rebass/test/CardImage.spec'>;
}
declare module 'rebass/test/Checkbox.spec.js' {
  declare module.exports: $Exports<'rebass/test/Checkbox.spec'>;
}
declare module 'rebass/test/Close.spec.js' {
  declare module.exports: $Exports<'rebass/test/Close.spec'>;
}
declare module 'rebass/test/color-style.spec.js' {
  declare module.exports: $Exports<'rebass/test/color-style.spec'>;
}
declare module 'rebass/test/config.spec.js' {
  declare module.exports: $Exports<'rebass/test/config.spec'>;
}
declare module 'rebass/test/Container.spec.js' {
  declare module.exports: $Exports<'rebass/test/Container.spec'>;
}
declare module 'rebass/test/Divider.spec.js' {
  declare module.exports: $Exports<'rebass/test/Divider.spec'>;
}
declare module 'rebass/test/Donut.spec.js' {
  declare module.exports: $Exports<'rebass/test/Donut.spec'>;
}
declare module 'rebass/test/DotIndicator.spec.js' {
  declare module.exports: $Exports<'rebass/test/DotIndicator.spec'>;
}
declare module 'rebass/test/Drawer.spec.js' {
  declare module.exports: $Exports<'rebass/test/Drawer.spec'>;
}
declare module 'rebass/test/Dropdown.spec.js' {
  declare module.exports: $Exports<'rebass/test/Dropdown.spec'>;
}
declare module 'rebass/test/DropdownMenu.js' {
  declare module.exports: $Exports<'rebass/test/DropdownMenu'>;
}
declare module 'rebass/test/Embed.spec.js' {
  declare module.exports: $Exports<'rebass/test/Embed.spec'>;
}
declare module 'rebass/test/Fixed.spec.js' {
  declare module.exports: $Exports<'rebass/test/Fixed.spec'>;
}
declare module 'rebass/test/Footer.spec.js' {
  declare module.exports: $Exports<'rebass/test/Footer.spec'>;
}
declare module 'rebass/test/Heading.spec.js' {
  declare module.exports: $Exports<'rebass/test/Heading.spec'>;
}
declare module 'rebass/test/HeadingLink.js' {
  declare module.exports: $Exports<'rebass/test/HeadingLink'>;
}
declare module 'rebass/test/InlineForm.spec.js' {
  declare module.exports: $Exports<'rebass/test/InlineForm.spec'>;
}
declare module 'rebass/test/Input.spec.js' {
  declare module.exports: $Exports<'rebass/test/Input.spec'>;
}
declare module 'rebass/test/Label.spec.js' {
  declare module.exports: $Exports<'rebass/test/Label.spec'>;
}
declare module 'rebass/test/LinkBlock.spec.js' {
  declare module.exports: $Exports<'rebass/test/LinkBlock.spec'>;
}
declare module 'rebass/test/margins.spec.js' {
  declare module.exports: $Exports<'rebass/test/margins.spec'>;
}
declare module 'rebass/test/Media.spec.js' {
  declare module.exports: $Exports<'rebass/test/Media.spec'>;
}
declare module 'rebass/test/Menu.spec.js' {
  declare module.exports: $Exports<'rebass/test/Menu.spec'>;
}
declare module 'rebass/test/Message.spec.js' {
  declare module.exports: $Exports<'rebass/test/Message.spec'>;
}
declare module 'rebass/test/NavItem.spec.js' {
  declare module.exports: $Exports<'rebass/test/NavItem.spec'>;
}
declare module 'rebass/test/Overlay.spec.js' {
  declare module.exports: $Exports<'rebass/test/Overlay.spec'>;
}
declare module 'rebass/test/padding.spec.js' {
  declare module.exports: $Exports<'rebass/test/padding.spec'>;
}
declare module 'rebass/test/PageHeader.spec.js' {
  declare module.exports: $Exports<'rebass/test/PageHeader.spec'>;
}
declare module 'rebass/test/Panel.spec.js' {
  declare module.exports: $Exports<'rebass/test/Panel.spec'>;
}
declare module 'rebass/test/PanelFooter.spec.js' {
  declare module.exports: $Exports<'rebass/test/PanelFooter.spec'>;
}
declare module 'rebass/test/PanelHeader.spec.js' {
  declare module.exports: $Exports<'rebass/test/PanelHeader.spec'>;
}
declare module 'rebass/test/Pre.spec.js' {
  declare module.exports: $Exports<'rebass/test/Pre.spec'>;
}
declare module 'rebass/test/Progress.spec.js' {
  declare module.exports: $Exports<'rebass/test/Progress.spec'>;
}
declare module 'rebass/test/radii.spec.js' {
  declare module.exports: $Exports<'rebass/test/radii.spec'>;
}
declare module 'rebass/test/Radio.spec.js' {
  declare module.exports: $Exports<'rebass/test/Radio.spec'>;
}
declare module 'rebass/test/Rating.spec.js' {
  declare module.exports: $Exports<'rebass/test/Rating.spec'>;
}
declare module 'rebass/test/Section.spec.js' {
  declare module.exports: $Exports<'rebass/test/Section.spec'>;
}
declare module 'rebass/test/SectionHeader.spec.js' {
  declare module.exports: $Exports<'rebass/test/SectionHeader.spec'>;
}
declare module 'rebass/test/Select.spec.js' {
  declare module.exports: $Exports<'rebass/test/Select.spec'>;
}
declare module 'rebass/test/SequenceMap.spec.js' {
  declare module.exports: $Exports<'rebass/test/SequenceMap.spec'>;
}
declare module 'rebass/test/Slider.spec.js' {
  declare module.exports: $Exports<'rebass/test/Slider.spec'>;
}
declare module 'rebass/test/Space.spec.js' {
  declare module.exports: $Exports<'rebass/test/Space.spec'>;
}
declare module 'rebass/test/Stat.spec.js' {
  declare module.exports: $Exports<'rebass/test/Stat.spec'>;
}
declare module 'rebass/test/Switch.spec.js' {
  declare module.exports: $Exports<'rebass/test/Switch.spec'>;
}
declare module 'rebass/test/Table.spec.js' {
  declare module.exports: $Exports<'rebass/test/Table.spec'>;
}
declare module 'rebass/test/Text.spec.js' {
  declare module.exports: $Exports<'rebass/test/Text.spec'>;
}
declare module 'rebass/test/Textarea.spec.js' {
  declare module.exports: $Exports<'rebass/test/Textarea.spec'>;
}
declare module 'rebass/test/Toolbar.spec.js' {
  declare module.exports: $Exports<'rebass/test/Toolbar.spec'>;
}
declare module 'rebass/test/Tooltip.spec.js' {
  declare module.exports: $Exports<'rebass/test/Tooltip.spec'>;
}
declare module 'rebass/webpack.config.js' {
  declare module.exports: $Exports<'rebass/webpack.config'>;
}
