// flow-typed signature: 89b6a28da018b591958ecec64793cbce
// flow-typed version: <<STUB>>/redux-observable_v^0.12.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-observable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-observable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-observable/dist/redux-observable' {
  declare module.exports: any;
}

declare module 'redux-observable/dist/redux-observable.min' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/ActionsObservable' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/combineEpics' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/createEpicMiddleware' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/EPIC_END' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-observable/dist/redux-observable.js' {
  declare module.exports: $Exports<'redux-observable/dist/redux-observable'>;
}
declare module 'redux-observable/dist/redux-observable.min.js' {
  declare module.exports: $Exports<'redux-observable/dist/redux-observable.min'>;
}
declare module 'redux-observable/lib/ActionsObservable.js' {
  declare module.exports: $Exports<'redux-observable/lib/ActionsObservable'>;
}
declare module 'redux-observable/lib/combineEpics.js' {
  declare module.exports: $Exports<'redux-observable/lib/combineEpics'>;
}
declare module 'redux-observable/lib/createEpicMiddleware.js' {
  declare module.exports: $Exports<'redux-observable/lib/createEpicMiddleware'>;
}
declare module 'redux-observable/lib/EPIC_END.js' {
  declare module.exports: $Exports<'redux-observable/lib/EPIC_END'>;
}
declare module 'redux-observable/lib/index.js' {
  declare module.exports: $Exports<'redux-observable/lib/index'>;
}
