// flow-typed signature: cf4a3df538e7bfd2ab4be7a72b3771d0
// flow-typed version: <<STUB>>/redux-observable_v^0.14.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-observable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-observable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-observable/dist/redux-observable' {
  declare module.exports: any;
}

declare module 'redux-observable/dist/redux-observable.min' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/cjs/ActionsObservable' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/cjs/combineEpics' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/cjs/createEpicMiddleware' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/cjs/EPIC_END' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/cjs/index' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/es/ActionsObservable' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/es/combineEpics' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/es/createEpicMiddleware' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/es/EPIC_END' {
  declare module.exports: any;
}

declare module 'redux-observable/lib/es/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-observable/dist/redux-observable.js' {
  declare module.exports: $Exports<'redux-observable/dist/redux-observable'>;
}
declare module 'redux-observable/dist/redux-observable.min.js' {
  declare module.exports: $Exports<'redux-observable/dist/redux-observable.min'>;
}
declare module 'redux-observable/lib/cjs/ActionsObservable.js' {
  declare module.exports: $Exports<'redux-observable/lib/cjs/ActionsObservable'>;
}
declare module 'redux-observable/lib/cjs/combineEpics.js' {
  declare module.exports: $Exports<'redux-observable/lib/cjs/combineEpics'>;
}
declare module 'redux-observable/lib/cjs/createEpicMiddleware.js' {
  declare module.exports: $Exports<'redux-observable/lib/cjs/createEpicMiddleware'>;
}
declare module 'redux-observable/lib/cjs/EPIC_END.js' {
  declare module.exports: $Exports<'redux-observable/lib/cjs/EPIC_END'>;
}
declare module 'redux-observable/lib/cjs/index.js' {
  declare module.exports: $Exports<'redux-observable/lib/cjs/index'>;
}
declare module 'redux-observable/lib/es/ActionsObservable.js' {
  declare module.exports: $Exports<'redux-observable/lib/es/ActionsObservable'>;
}
declare module 'redux-observable/lib/es/combineEpics.js' {
  declare module.exports: $Exports<'redux-observable/lib/es/combineEpics'>;
}
declare module 'redux-observable/lib/es/createEpicMiddleware.js' {
  declare module.exports: $Exports<'redux-observable/lib/es/createEpicMiddleware'>;
}
declare module 'redux-observable/lib/es/EPIC_END.js' {
  declare module.exports: $Exports<'redux-observable/lib/es/EPIC_END'>;
}
declare module 'redux-observable/lib/es/index.js' {
  declare module.exports: $Exports<'redux-observable/lib/es/index'>;
}
