// flow-typed signature: 3d76ea5da0a24721c0ff78d1a1c0f419
// flow-typed version: <<STUB>>/regenerator_v^0.9.5/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'regenerator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'regenerator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'regenerator/lib/util' {
  declare module.exports: any;
}

declare module 'regenerator/lib/visit' {
  declare module.exports: any;
}

declare module 'regenerator/main' {
  declare module.exports: any;
}

declare module 'regenerator/runtime-module' {
  declare module.exports: any;
}

declare module 'regenerator/runtime' {
  declare module.exports: any;
}

// Filename aliases
declare module 'regenerator/lib/util.js' {
  declare module.exports: $Exports<'regenerator/lib/util'>;
}
declare module 'regenerator/lib/visit.js' {
  declare module.exports: $Exports<'regenerator/lib/visit'>;
}
declare module 'regenerator/main.js' {
  declare module.exports: $Exports<'regenerator/main'>;
}
declare module 'regenerator/runtime-module.js' {
  declare module.exports: $Exports<'regenerator/runtime-module'>;
}
declare module 'regenerator/runtime.js' {
  declare module.exports: $Exports<'regenerator/runtime'>;
}
