// flow-typed signature: e27ddd9b33e35705173a3ed4b4a51efa
// flow-typed version: <<STUB>>/regenerator-runtime_v^0.10.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'regenerator-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'regenerator-runtime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'regenerator-runtime/path' {
  declare module.exports: any;
}

declare module 'regenerator-runtime/runtime-module' {
  declare module.exports: any;
}

declare module 'regenerator-runtime/runtime' {
  declare module.exports: any;
}

// Filename aliases
declare module 'regenerator-runtime/path.js' {
  declare module.exports: $Exports<'regenerator-runtime/path'>;
}
declare module 'regenerator-runtime/runtime-module.js' {
  declare module.exports: $Exports<'regenerator-runtime/runtime-module'>;
}
declare module 'regenerator-runtime/runtime.js' {
  declare module.exports: $Exports<'regenerator-runtime/runtime'>;
}
