// flow-typed signature: 60c3d8f006507c316c4667351ce56763
// flow-typed version: <<STUB>>/relay-compiler_v^1.6.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'relay-compiler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'relay-compiler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'relay-compiler/lib/compileRelayArtifacts' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/dedupeJSONStringify' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/deepMergeAssignments' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/FindGraphQLTags' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/formatGeneratedModule' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/getModuleName' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/murmurHash' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayApplyFragmentArgumentTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayCodeGenerator' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayCompilerBin' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayCompilerCache' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayCompilerPublic' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayCompilerScope' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayConnectionConstants' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayConnectionTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayDeferrableFragmentTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayFieldHandleTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayFileWriter' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayFlowBabelFactories' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayFlowGenerator' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayFlowTypeTransformers' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayGenerateIDFieldTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayGenerateTypeNameTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayGraphQLEnumsGenerator' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayIRTransforms' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayJSModuleParser' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayMaskTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayParser' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayRelayDirectiveTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelaySkipHandleFieldTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayTransformUtils' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayValidator' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayViewerHandleTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/requestsForOperation' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/writeRelayGeneratedFile' {
  declare module.exports: any;
}

declare module 'relay-compiler/relay-compiler' {
  declare module.exports: any;
}

declare module 'relay-compiler/relay-compiler.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'relay-compiler/index' {
  declare module.exports: $Exports<'relay-compiler'>;
}
declare module 'relay-compiler/index.js' {
  declare module.exports: $Exports<'relay-compiler'>;
}
declare module 'relay-compiler/lib/compileRelayArtifacts.js' {
  declare module.exports: $Exports<'relay-compiler/lib/compileRelayArtifacts'>;
}
declare module 'relay-compiler/lib/dedupeJSONStringify.js' {
  declare module.exports: $Exports<'relay-compiler/lib/dedupeJSONStringify'>;
}
declare module 'relay-compiler/lib/deepMergeAssignments.js' {
  declare module.exports: $Exports<'relay-compiler/lib/deepMergeAssignments'>;
}
declare module 'relay-compiler/lib/FindGraphQLTags.js' {
  declare module.exports: $Exports<'relay-compiler/lib/FindGraphQLTags'>;
}
declare module 'relay-compiler/lib/formatGeneratedModule.js' {
  declare module.exports: $Exports<'relay-compiler/lib/formatGeneratedModule'>;
}
declare module 'relay-compiler/lib/getModuleName.js' {
  declare module.exports: $Exports<'relay-compiler/lib/getModuleName'>;
}
declare module 'relay-compiler/lib/murmurHash.js' {
  declare module.exports: $Exports<'relay-compiler/lib/murmurHash'>;
}
declare module 'relay-compiler/lib/RelayApplyFragmentArgumentTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayApplyFragmentArgumentTransform'>;
}
declare module 'relay-compiler/lib/RelayCodeGenerator.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayCodeGenerator'>;
}
declare module 'relay-compiler/lib/RelayCompilerBin.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayCompilerBin'>;
}
declare module 'relay-compiler/lib/RelayCompilerCache.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayCompilerCache'>;
}
declare module 'relay-compiler/lib/RelayCompilerPublic.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayCompilerPublic'>;
}
declare module 'relay-compiler/lib/RelayCompilerScope.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayCompilerScope'>;
}
declare module 'relay-compiler/lib/RelayConnectionConstants.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayConnectionConstants'>;
}
declare module 'relay-compiler/lib/RelayConnectionTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayConnectionTransform'>;
}
declare module 'relay-compiler/lib/RelayDeferrableFragmentTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayDeferrableFragmentTransform'>;
}
declare module 'relay-compiler/lib/RelayFieldHandleTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayFieldHandleTransform'>;
}
declare module 'relay-compiler/lib/RelayFileWriter.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayFileWriter'>;
}
declare module 'relay-compiler/lib/RelayFlowBabelFactories.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayFlowBabelFactories'>;
}
declare module 'relay-compiler/lib/RelayFlowGenerator.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayFlowGenerator'>;
}
declare module 'relay-compiler/lib/RelayFlowTypeTransformers.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayFlowTypeTransformers'>;
}
declare module 'relay-compiler/lib/RelayGenerateIDFieldTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayGenerateIDFieldTransform'>;
}
declare module 'relay-compiler/lib/RelayGenerateTypeNameTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayGenerateTypeNameTransform'>;
}
declare module 'relay-compiler/lib/RelayGraphQLEnumsGenerator.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayGraphQLEnumsGenerator'>;
}
declare module 'relay-compiler/lib/RelayIRTransforms.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayIRTransforms'>;
}
declare module 'relay-compiler/lib/RelayJSModuleParser.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayJSModuleParser'>;
}
declare module 'relay-compiler/lib/RelayMaskTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayMaskTransform'>;
}
declare module 'relay-compiler/lib/RelayParser.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayParser'>;
}
declare module 'relay-compiler/lib/RelayRelayDirectiveTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayRelayDirectiveTransform'>;
}
declare module 'relay-compiler/lib/RelaySkipHandleFieldTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelaySkipHandleFieldTransform'>;
}
declare module 'relay-compiler/lib/RelayTransformUtils.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayTransformUtils'>;
}
declare module 'relay-compiler/lib/RelayValidator.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayValidator'>;
}
declare module 'relay-compiler/lib/RelayViewerHandleTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayViewerHandleTransform'>;
}
declare module 'relay-compiler/lib/requestsForOperation.js' {
  declare module.exports: $Exports<'relay-compiler/lib/requestsForOperation'>;
}
declare module 'relay-compiler/lib/writeRelayGeneratedFile.js' {
  declare module.exports: $Exports<'relay-compiler/lib/writeRelayGeneratedFile'>;
}
declare module 'relay-compiler/relay-compiler.js' {
  declare module.exports: $Exports<'relay-compiler/relay-compiler'>;
}
declare module 'relay-compiler/relay-compiler.min.js' {
  declare module.exports: $Exports<'relay-compiler/relay-compiler.min'>;
}
