// flow-typed signature: 06faf44f053ad298f2026b6f9451ec83
// flow-typed version: <<STUB>>/relay-devtools_v^1.4.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'relay-devtools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'relay-devtools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'relay-devtools/app' {
  declare module.exports: any;
}

declare module 'relay-devtools/launchApp' {
  declare module.exports: any;
}

declare module 'relay-devtools/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'relay-devtools/app.js' {
  declare module.exports: $Exports<'relay-devtools/app'>;
}
declare module 'relay-devtools/index' {
  declare module.exports: $Exports<'relay-devtools'>;
}
declare module 'relay-devtools/index.js' {
  declare module.exports: $Exports<'relay-devtools'>;
}
declare module 'relay-devtools/launchApp.js' {
  declare module.exports: $Exports<'relay-devtools/launchApp'>;
}
declare module 'relay-devtools/main.js' {
  declare module.exports: $Exports<'relay-devtools/main'>;
}
