// flow-typed signature: b2ab3b05cb97e876fa882d6ceaa571ef
// flow-typed version: <<STUB>>/require-dir_v^0.3.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'require-dir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'require-dir' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'require-dir/test/camelcase' {
  declare module.exports: any;
}

declare module 'require-dir/test/camelcase/a_main' {
  declare module.exports: any;
}

declare module 'require-dir/test/camelcase/sub-dir/a-sub' {
  declare module.exports: any;
}

declare module 'require-dir/test/duplicates' {
  declare module.exports: any;
}

declare module 'require-dir/test/duplicates/a' {
  declare module.exports: any;
}

declare module 'require-dir/test/duplicates/b/1' {
  declare module.exports: any;
}

declare module 'require-dir/test/duplicates/b/2' {
  declare module.exports: any;
}

declare module 'require-dir/test/duplicates/d' {
  declare module.exports: any;
}

declare module 'require-dir/test/index' {
  declare module.exports: any;
}

declare module 'require-dir/test/recurse' {
  declare module.exports: any;
}

declare module 'require-dir/test/recurse/a' {
  declare module.exports: any;
}

declare module 'require-dir/test/recurse/b/1/foo' {
  declare module.exports: any;
}

declare module 'require-dir/test/simple' {
  declare module.exports: any;
}

declare module 'require-dir/test/simple/a' {
  declare module.exports: any;
}

// Filename aliases
declare module 'require-dir/index' {
  declare module.exports: $Exports<'require-dir'>;
}
declare module 'require-dir/index.js' {
  declare module.exports: $Exports<'require-dir'>;
}
declare module 'require-dir/test/camelcase.js' {
  declare module.exports: $Exports<'require-dir/test/camelcase'>;
}
declare module 'require-dir/test/camelcase/a_main.js' {
  declare module.exports: $Exports<'require-dir/test/camelcase/a_main'>;
}
declare module 'require-dir/test/camelcase/sub-dir/a-sub.js' {
  declare module.exports: $Exports<'require-dir/test/camelcase/sub-dir/a-sub'>;
}
declare module 'require-dir/test/duplicates.js' {
  declare module.exports: $Exports<'require-dir/test/duplicates'>;
}
declare module 'require-dir/test/duplicates/a.js' {
  declare module.exports: $Exports<'require-dir/test/duplicates/a'>;
}
declare module 'require-dir/test/duplicates/b/1.js' {
  declare module.exports: $Exports<'require-dir/test/duplicates/b/1'>;
}
declare module 'require-dir/test/duplicates/b/2.js' {
  declare module.exports: $Exports<'require-dir/test/duplicates/b/2'>;
}
declare module 'require-dir/test/duplicates/d.js' {
  declare module.exports: $Exports<'require-dir/test/duplicates/d'>;
}
declare module 'require-dir/test/index.js' {
  declare module.exports: $Exports<'require-dir/test/index'>;
}
declare module 'require-dir/test/recurse.js' {
  declare module.exports: $Exports<'require-dir/test/recurse'>;
}
declare module 'require-dir/test/recurse/a.js' {
  declare module.exports: $Exports<'require-dir/test/recurse/a'>;
}
declare module 'require-dir/test/recurse/b/1/foo.js' {
  declare module.exports: $Exports<'require-dir/test/recurse/b/1/foo'>;
}
declare module 'require-dir/test/simple.js' {
  declare module.exports: $Exports<'require-dir/test/simple'>;
}
declare module 'require-dir/test/simple/a.js' {
  declare module.exports: $Exports<'require-dir/test/simple/a'>;
}
