// flow-typed signature: d5721241446c22d2e0e7467b6d11c3c5
// flow-typed version: <<STUB>>/sinon-as-promised_v^4.0.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sinon-as-promised'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sinon-as-promised' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'sinon-as-promised/index' {
  declare module.exports: $Exports<'sinon-as-promised'>;
}
declare module 'sinon-as-promised/index.js' {
  declare module.exports: $Exports<'sinon-as-promised'>;
}
