// flow-typed signature: c9a0200e59009d18d04d23c518baea36
// flow-typed version: <<STUB>>/slate-plain-serializer_v^0.6.2/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slate-plain-serializer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slate-plain-serializer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slate-plain-serializer/dist/slate-plain-serializer' {
  declare module.exports: any;
}

declare module 'slate-plain-serializer/dist/slate-plain-serializer.min' {
  declare module.exports: any;
}

declare module 'slate-plain-serializer/lib/slate-plain-serializer.es' {
  declare module.exports: any;
}

declare module 'slate-plain-serializer/lib/slate-plain-serializer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slate-plain-serializer/dist/slate-plain-serializer.js' {
  declare module.exports: $Exports<'slate-plain-serializer/dist/slate-plain-serializer'>;
}
declare module 'slate-plain-serializer/dist/slate-plain-serializer.min.js' {
  declare module.exports: $Exports<'slate-plain-serializer/dist/slate-plain-serializer.min'>;
}
declare module 'slate-plain-serializer/lib/slate-plain-serializer.es.js' {
  declare module.exports: $Exports<'slate-plain-serializer/lib/slate-plain-serializer.es'>;
}
declare module 'slate-plain-serializer/lib/slate-plain-serializer.js' {
  declare module.exports: $Exports<'slate-plain-serializer/lib/slate-plain-serializer'>;
}
