// flow-typed signature: e6ecf46e0a0239737d3c4260fee37189
// flow-typed version: <<STUB>>/slate_v^0.43.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slate' {
  // TL;DR: Currently copy-pasting is indeed the best practice.
  // https://github.com/flow-typed/flow-typed/issues/2842#issuecomment-429974407
  declare export type SlateValue = Object;
  declare export var Value: SlateValue;
  declare export var KeyUtils: {
    resetGenerator: () => void,
  };
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slate/dist/slate' {
  declare module.exports: any;
}

declare module 'slate/dist/slate.min' {
  declare module.exports: any;
}

declare module 'slate/lib/slate.es' {
  declare module.exports: any;
}

declare module 'slate/lib/slate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slate/dist/slate.js' {
  declare module.exports: $Exports<'slate/dist/slate'>;
}
declare module 'slate/dist/slate.min.js' {
  declare module.exports: $Exports<'slate/dist/slate.min'>;
}
declare module 'slate/lib/slate.es.js' {
  declare module.exports: $Exports<'slate/lib/slate.es'>;
}
declare module 'slate/lib/slate.js' {
  declare module.exports: $Exports<'slate/lib/slate'>;
}
