// flow-typed signature: 7c2ca9f5ea3475a9dd5155ee8c18d96c
// flow-typed version: <<STUB>>/slate-react_v^0.21.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slate-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slate-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slate-react/dist/slate-react' {
  declare module.exports: any;
}

declare module 'slate-react/dist/slate-react.min' {
  declare module.exports: any;
}

declare module 'slate-react/lib/slate-react.es' {
  declare module.exports: any;
}

declare module 'slate-react/lib/slate-react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slate-react/dist/slate-react.js' {
  declare module.exports: $Exports<'slate-react/dist/slate-react'>;
}
declare module 'slate-react/dist/slate-react.min.js' {
  declare module.exports: $Exports<'slate-react/dist/slate-react.min'>;
}
declare module 'slate-react/lib/slate-react.es.js' {
  declare module.exports: $Exports<'slate-react/lib/slate-react.es'>;
}
declare module 'slate-react/lib/slate-react.js' {
  declare module.exports: $Exports<'slate-react/lib/slate-react'>;
}
