// flow-typed signature: 48d6499a6de3333162673764d2ce29a2
// flow-typed version: <<STUB>>/smoothscroll-polyfill_v^0.4.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'smoothscroll-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'smoothscroll-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'smoothscroll-polyfill/dist/smoothscroll' {
  declare module.exports: any;
}

declare module 'smoothscroll-polyfill/dist/smoothscroll.min' {
  declare module.exports: any;
}

declare module 'smoothscroll-polyfill/gulpfile' {
  declare module.exports: any;
}

declare module 'smoothscroll-polyfill/rollup.config' {
  declare module.exports: any;
}

declare module 'smoothscroll-polyfill/src/smoothscroll' {
  declare module.exports: any;
}

// Filename aliases
declare module 'smoothscroll-polyfill/dist/smoothscroll.js' {
  declare module.exports: $Exports<'smoothscroll-polyfill/dist/smoothscroll'>;
}
declare module 'smoothscroll-polyfill/dist/smoothscroll.min.js' {
  declare module.exports: $Exports<'smoothscroll-polyfill/dist/smoothscroll.min'>;
}
declare module 'smoothscroll-polyfill/gulpfile.js' {
  declare module.exports: $Exports<'smoothscroll-polyfill/gulpfile'>;
}
declare module 'smoothscroll-polyfill/rollup.config.js' {
  declare module.exports: $Exports<'smoothscroll-polyfill/rollup.config'>;
}
declare module 'smoothscroll-polyfill/src/smoothscroll.js' {
  declare module.exports: $Exports<'smoothscroll-polyfill/src/smoothscroll'>;
}
