// flow-typed signature: fb6590d2cafa266cedb00acf1e53962f
// flow-typed version: <<STUB>>/through2_v^2.0.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'through2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'through2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'through2/through2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'through2/through2.js' {
  declare module.exports: $Exports<'through2/through2'>;
}
