// flow-typed signature: 7b0ea453f754fb747d3701fa1f4d850b
// flow-typed version: <<STUB>>/url_v^0.11.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'url/test' {
  declare module.exports: any;
}

declare module 'url/url' {
  declare module.exports: any;
}

declare module 'url/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'url/test.js' {
  declare module.exports: $Exports<'url/test'>;
}
declare module 'url/url.js' {
  declare module.exports: $Exports<'url/url'>;
}
declare module 'url/util.js' {
  declare module.exports: $Exports<'url/util'>;
}
