// flow-typed signature: 8b9b84ec884eba8d4fef2aaff30ef5d0
// flow-typed version: <<STUB>>/webpack-isomorphic-tools_v^2.2.24/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-isomorphic-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-isomorphic-tools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-isomorphic-tools/babel-transpiled-modules/common' {
  declare module.exports: any;
}

declare module 'webpack-isomorphic-tools/babel-transpiled-modules/helpers' {
  declare module.exports: any;
}

declare module 'webpack-isomorphic-tools/babel-transpiled-modules/index' {
  declare module.exports: any;
}

declare module 'webpack-isomorphic-tools/babel-transpiled-modules/plugin/notify stats' {
  declare module.exports: any;
}

declare module 'webpack-isomorphic-tools/babel-transpiled-modules/plugin/plugin' {
  declare module.exports: any;
}

declare module 'webpack-isomorphic-tools/babel-transpiled-modules/plugin/write assets' {
  declare module.exports: any;
}

declare module 'webpack-isomorphic-tools/babel-transpiled-modules/tools/log' {
  declare module.exports: any;
}

declare module 'webpack-isomorphic-tools/babel-transpiled-modules/tools/serialize-javascript' {
  declare module.exports: any;
}

declare module 'webpack-isomorphic-tools/babel-transpiled-modules/tools/synchronous http' {
  declare module.exports: any;
}

declare module 'webpack-isomorphic-tools/context' {
  declare module.exports: any;
}

declare module 'webpack-isomorphic-tools/ensure' {
  declare module.exports: any;
}

declare module 'webpack-isomorphic-tools/plugin' {
  declare module.exports: any;
}

declare module 'webpack-isomorphic-tools/source/common' {
  declare module.exports: any;
}

declare module 'webpack-isomorphic-tools/source/helpers' {
  declare module.exports: any;
}

declare module 'webpack-isomorphic-tools/source/index' {
  declare module.exports: any;
}

declare module 'webpack-isomorphic-tools/source/plugin/notify stats' {
  declare module.exports: any;
}

declare module 'webpack-isomorphic-tools/source/plugin/plugin' {
  declare module.exports: any;
}

declare module 'webpack-isomorphic-tools/source/plugin/write assets' {
  declare module.exports: any;
}

declare module 'webpack-isomorphic-tools/source/tools/log' {
  declare module.exports: any;
}

declare module 'webpack-isomorphic-tools/source/tools/serialize-javascript' {
  declare module.exports: any;
}

declare module 'webpack-isomorphic-tools/source/tools/synchronous http' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-isomorphic-tools/babel-transpiled-modules/common.js' {
  declare module.exports: $Exports<'webpack-isomorphic-tools/babel-transpiled-modules/common'>;
}
declare module 'webpack-isomorphic-tools/babel-transpiled-modules/helpers.js' {
  declare module.exports: $Exports<'webpack-isomorphic-tools/babel-transpiled-modules/helpers'>;
}
declare module 'webpack-isomorphic-tools/babel-transpiled-modules/index.js' {
  declare module.exports: $Exports<'webpack-isomorphic-tools/babel-transpiled-modules/index'>;
}
declare module 'webpack-isomorphic-tools/babel-transpiled-modules/plugin/notify stats.js' {
  declare module.exports: $Exports<'webpack-isomorphic-tools/babel-transpiled-modules/plugin/notify stats'>;
}
declare module 'webpack-isomorphic-tools/babel-transpiled-modules/plugin/plugin.js' {
  declare module.exports: $Exports<'webpack-isomorphic-tools/babel-transpiled-modules/plugin/plugin'>;
}
declare module 'webpack-isomorphic-tools/babel-transpiled-modules/plugin/write assets.js' {
  declare module.exports: $Exports<'webpack-isomorphic-tools/babel-transpiled-modules/plugin/write assets'>;
}
declare module 'webpack-isomorphic-tools/babel-transpiled-modules/tools/log.js' {
  declare module.exports: $Exports<'webpack-isomorphic-tools/babel-transpiled-modules/tools/log'>;
}
declare module 'webpack-isomorphic-tools/babel-transpiled-modules/tools/serialize-javascript.js' {
  declare module.exports: $Exports<'webpack-isomorphic-tools/babel-transpiled-modules/tools/serialize-javascript'>;
}
declare module 'webpack-isomorphic-tools/babel-transpiled-modules/tools/synchronous http.js' {
  declare module.exports: $Exports<'webpack-isomorphic-tools/babel-transpiled-modules/tools/synchronous http'>;
}
declare module 'webpack-isomorphic-tools/context.js' {
  declare module.exports: $Exports<'webpack-isomorphic-tools/context'>;
}
declare module 'webpack-isomorphic-tools/ensure.js' {
  declare module.exports: $Exports<'webpack-isomorphic-tools/ensure'>;
}
declare module 'webpack-isomorphic-tools/plugin.js' {
  declare module.exports: $Exports<'webpack-isomorphic-tools/plugin'>;
}
declare module 'webpack-isomorphic-tools/source/common.js' {
  declare module.exports: $Exports<'webpack-isomorphic-tools/source/common'>;
}
declare module 'webpack-isomorphic-tools/source/helpers.js' {
  declare module.exports: $Exports<'webpack-isomorphic-tools/source/helpers'>;
}
declare module 'webpack-isomorphic-tools/source/index.js' {
  declare module.exports: $Exports<'webpack-isomorphic-tools/source/index'>;
}
declare module 'webpack-isomorphic-tools/source/plugin/notify stats.js' {
  declare module.exports: $Exports<'webpack-isomorphic-tools/source/plugin/notify stats'>;
}
declare module 'webpack-isomorphic-tools/source/plugin/plugin.js' {
  declare module.exports: $Exports<'webpack-isomorphic-tools/source/plugin/plugin'>;
}
declare module 'webpack-isomorphic-tools/source/plugin/write assets.js' {
  declare module.exports: $Exports<'webpack-isomorphic-tools/source/plugin/write assets'>;
}
declare module 'webpack-isomorphic-tools/source/tools/log.js' {
  declare module.exports: $Exports<'webpack-isomorphic-tools/source/tools/log'>;
}
declare module 'webpack-isomorphic-tools/source/tools/serialize-javascript.js' {
  declare module.exports: $Exports<'webpack-isomorphic-tools/source/tools/serialize-javascript'>;
}
declare module 'webpack-isomorphic-tools/source/tools/synchronous http.js' {
  declare module.exports: $Exports<'webpack-isomorphic-tools/source/tools/synchronous http'>;
}
