/* @flow */

// CSSStyleDeclaration
// github.com/facebook/flow/blob/master/lib/cssom.js
// cssreference.io
// TODO: Finish enums, replace strings with numbers, handle custom Fela syntax.
export type Style = {
  /* DOM CSS Properties */
  alignContent?: 'stretch' | 'flex-start' | 'flex-end' | 'center' | 'space-between' | 'space-around',
  alignItems?: 'flex-start' | 'flex-end' | 'center' | 'baseline' | 'stretch',
  alignSelf?: 'flex-start' | 'flex-end' | 'center' | 'baseline' | 'stretch',
  // all?: string,
  // animation?: string,
  // animationDelay?: string,
  // animationDirection?: string,
  // animationDuration?: string,
  // animationFillMode?: string,
  // animationIterationCount?: string,
  // animationName?: string,
  // animationPlayState?: string,
  // animationTimingFunction?: string,
  backdropFilter?: string,
  webkitBackdropFilter?: string,
  backfaceVisibility?: string,
  background?: string,
  backgroundAttachment?: string,
  backgroundBlendMode?: string,
  backgroundClip?: string,
  backgroundColor?: string,
  backgroundImage?: string,
  backgroundOrigin?: string,
  backgroundPosition?: string,
  backgroundRepeat?: string,
  backgroundSize?: string,
  blockSize?: string,
  border?: string,
  borderBlockEnd?: string,
  borderBlockEndColor?: string,
  borderBlockEndStyle?: string,
  borderBlockEndWidth?: string,
  borderBlockStart?: string,
  borderBlockStartColor?: string,
  borderBlockStartStyle?: string,
  borderBlockStartWidth?: string,
  borderBottom?: string,
  borderBottomColor?: string,
  borderBottomLeftRadius?: string,
  borderBottomRightRadius?: string,
  borderBottomStyle?: string,
  borderBottomWidth?: string,
  borderCollapse?: string,
  borderColor?: string,
  borderImage?: string,
  borderImageOutset?: string,
  borderImageRepeat?: string,
  borderImageSlice?: string,
  borderImageSource?: string,
  borderImageWidth?: string,
  borderInlineEnd?: string,
  borderInlineEndColor?: string,
  borderInlineEndStyle?: string,
  borderInlineEndWidth?: string,
  borderInlineStart?: string,
  borderInlineStartColor?: string,
  borderInlineStartStyle?: string,
  borderInlineStartWidth?: string,
  borderLeft?: string,
  borderLeftColor?: string,
  borderLeftStyle?: string,
  borderLeftWidth?: string,
  borderRadius?: string,
  borderRight?: string,
  borderRightColor?: string,
  borderRightStyle?: string,
  borderRightWidth?: string,
  borderSpacing?: string,
  borderStyle?: string,
  borderTop?: string,
  borderTopColor?: string,
  borderTopLeftRadius?: string,
  borderTopRightRadius?: string,
  borderTopStyle?: string,
  borderTopWidth?: string,
  borderWidth?: string,
  bottom?: string,
  boxDecorationBreak?: string,
  boxShadow?: string,
  boxSizing?: string,
  breakAfter?: string,
  breakBefore?: string,
  breakInside?: string,
  captionSide?: string,
  clear?: string,
  clip?: string,
  clipPath?: string,
  color?: string,
  columns?: string,
  columnCount?: string,
  columnFill?: string,
  columnGap?: string,
  columnRule?: string,
  columnRuleColor?: string,
  columnRuleStyle?: string,
  columnRuleWidth?: string,
  columnSpan?: string,
  columnWidth?: string,
  contain?: string,
  content?: string,
  counterIncrement?: string,
  counterReset?: string,
  cursor?: string,
  direction?: string,
  display?: 'none' | 'inline' | 'block' | 'inline-block' | 'list-item' | 'table' | 'table-cell' | 'table-row' | 'flex' | 'inline-flex',
  emptyCells?: string,
  filter?: string,
  flex?: number | string,
  flexBasis?: string,
  flexDirection?: 'row' | 'row-reverse' | 'column' | 'column-reverse',
  flexFlow?: string,
  flexGrow?: number,
  flexShrink?: string,
  flexWrap?: 'nowrap' | 'wrap' | 'wrap-reverse',
  float?: 'none' | 'left' | 'right',
  font?: string,
  fontFamily?: string,
  fontFeatureSettings?: string,
  fontKerning?: string,
  fontLanguageOverride?: string,
  fontSize?: string,
  fontSizeAdjust?: string,
  fontStretch?: string,
  fontStyle?: string,
  fontSynthesis?: string,
  fontVariant?: string,
  fontVariantAlternates?: string,
  fontVariantCaps?: string,
  fontVariantEastAsian?: string,
  fontVariantLigatures?: string,
  fontVariantNumeric?: string,
  fontVariantPosition?: string,
  fontWeight?: 'normal' | 'bold' | 'lighter' | 'bolder' | number,
  grad?: string,
  grid?: string,
  gridArea?: string,
  gridAutoColumns?: string,
  gridAutoFlow?: string,
  gridAutoPosition?: string,
  gridAutoRows?: string,
  gridColumn?: string,
  gridColumnStart?: string,
  gridColumnEnd?: string,
  gridRow?: string,
  gridRowStart?: string,
  gridRowEnd?: string,
  gridTemplate?: string,
  gridTemplateAreas?: string,
  gridTemplateRows?: string,
  gridTemplateColumns?: string,
  height?: string,
  hyphens?: string,
  imageRendering?: string,
  imageResolution?: string,
  imageOrientation?: string,
  imeMode?: string,
  inherit?: string,
  initial?: string,
  inlineSize?: string,
  isolation?: string,
  justifyContent?: string,
  left?: string,
  letterSpacing?: string,
  lineBreak?: string,
  lineHeight?: 'normal' | number | string,
  listStyle?: string,
  listStyleImage?: string,
  listStylePosition?: string,
  listStyleType?: string,
  margin?: number | string,
  marginBlockEnd?: string,
  marginBlockStart?: string,
  marginBottom?: number | string,
  marginInlineEnd?: string,
  marginInlineStart?: string,
  marginLeft?: number | string,
  marginRight?: number | string,
  marginTop?: number | string,
  marks?: string,
  mask?: string,
  maskType?: string,
  maxBlockSize?: string,
  maxHeight?: number | string,
  maxInlineSize?: string,
  maxWidth?: number | string,
  minBlockSize?: string,
  minHeight?: number | string,
  minInlineSize?: string,
  minWidth?: number | string,
  mixBlendMode?: string,
  mozTransform?: string,
  mozTransformOrigin?: string,
  mozTransitionDelay?: string,
  mozTransitionDuration?: string,
  mozTransitionProperty?: string,
  mozTransitionTimingFunction?: string,
  objectFit?: string,
  objectPosition?: string,
  offsetBlockEnd?: string,
  offsetBlockStart?: string,
  offsetInlineEnd?: string,
  offsetInlineStart?: string,
  opacity?: string,
  order?: string,
  orphans?: string,
  outline?: string,
  outlineColor?: string,
  outlineOffset?: string,
  outlineStyle?: string,
  outlineWidth?: string,
  overflow?: string,
  overflowWrap?: string,
  overflowX?: string,
  overflowY?: string,
  padding?: string,
  paddingBlockEnd?: string,
  paddingBlockStart?: string,
  paddingBottom?: number | string,
  paddingInlineEnd?: string,
  paddingInlineStart?: string,
  paddingLeft?: number | string,
  paddingRight?: number | string,
  paddingTop?: number | string,
  pageBreakAfter?: string,
  pageBreakBefore?: string,
  pageBreakInside?: string,
  perspective?: string,
  perspectiveOrigin?: string,
  pointerEvents?: string,
  position?: string,
  quotes?: string,
  rad?: string,
  resize?: string,
  right?: string,
  rubyAlign?: string,
  rubyMerge?: string,
  rubyPosition?: string,
  scrollBehavior?: string,
  scrollSnapCoordinate?: string,
  scrollSnapDestination?: string,
  scrollSnapPointsX?: string,
  scrollSnapPointsY?: string,
  scrollSnapType?: string,
  shapeImageThreshold?: string,
  shapeMargin?: string,
  shapeOutside?: string,
  tableLayout?: string,
  tabSize?: string,
  textAlign?: string,
  textAlignLast?: string,
  textCombineUpright?: string,
  textDecoration?: string,
  textDecorationColor?: string,
  textDecorationLine?: string,
  textDecorationStyle?: string,
  textIndent?: string,
  textOrientation?: string,
  textOverflow?: string,
  textRendering?: string,
  textShadow?: string,
  textTransform?: string,
  textUnderlinePosition?: string,
  top?: string,
  touchAction?: string,
  transform?: string,
  transformOrigin?: string,
  transformStyle?: string,
  transition?: string,
  transitionDelay?: string,
  transitionDuration?: string,
  transitionProperty?: string,
  transitionTimingFunction?: string,
  turn?: string,
  unicodeBidi?: string,
  unicodeRange?: string,
  verticalAlign?: string,
  visibility?: string,
  webkitOverflowScrolling?: string,
  webkitTransform?: string,
  webkitTransformOrigin?: string,
  webkitTransitionDelay?: string,
  webkitTransitionDuration?: string,
  webkitTransitionProperty?: string,
  webkitTransitionTimingFunction?: string,
  whiteSpace?: string,
  widows?: string,
  width?: string,
  willChange?: string,
  wordBreak?: string,
  wordSpacing?: string,
  wordWrap?: string,
  writingMode?: string,
  zIndex?: number,
};
